[2024-06-14 22:09:02,727: INFO: main: welcome]
[2024-06-17 00:01:45,736: INFO: main: welcome]
[2024-06-24 10:42:56,790: INFO: main: welcome]
[2024-06-24 12:19:26,990: INFO: main: >>>>>> stage Data Ingestion stage started <<<<<<]
[2024-06-24 12:19:26,990: INFO: common: yaml file: config\config.yaml loaded successfully]
[2024-06-24 12:19:27,006: INFO: common: yaml file: params.yaml loaded successfully]
[2024-06-24 12:19:27,006: INFO: common: created directory at: artifacts]
[2024-06-24 12:19:27,013: INFO: common: created directory at: artifacts/data_ingestion]
[2024-06-24 12:19:27,014: INFO: data_ingestion: Downloading data from https://drive.google.com/file/d/1OEpd0JqL1RE6IryAtUSLmY_M2MBXg_1g/view?usp=drive_link into file artifacts/data_ingestion/data.zip]
[2024-06-24 12:21:36,286: INFO: data_ingestion: Downloaded data from https://drive.google.com/file/d/1OEpd0JqL1RE6IryAtUSLmY_M2MBXg_1g/view?usp=drive_link into file artifacts/data_ingestion/data.zip]
[2024-06-24 12:21:45,543: INFO: main: >>>>>> stage Data Ingestion stage completed <<<<<<

x==========x]
[2024-06-24 15:51:59,334: INFO: common: yaml file: config\config.yaml loaded successfully]
[2024-06-24 15:51:59,351: INFO: common: yaml file: params.yaml loaded successfully]
[2024-06-24 15:51:59,353: INFO: common: created directory at: artifacts]
[2024-06-24 15:51:59,354: INFO: common: created directory at: artifacts/prepare_base_model]
[2024-06-24 15:52:11,130: WARNING: saving_utils: Compiled the loaded model, but the compiled metrics have yet to be built. `model.compile_metrics` will be empty until you train or evaluate the model.]
[2024-06-24 16:14:45,808: INFO: main: >>>>>> stage Data Ingestion stage started <<<<<<]
[2024-06-24 16:14:45,808: INFO: common: yaml file: config\config.yaml loaded successfully]
[2024-06-24 16:14:45,808: INFO: common: yaml file: params.yaml loaded successfully]
[2024-06-24 16:14:45,808: INFO: common: created directory at: artifacts]
[2024-06-24 16:14:45,808: INFO: common: created directory at: artifacts/data_ingestion]
[2024-06-24 16:14:45,808: INFO: data_ingestion: Downloading data from https://drive.google.com/file/d/1OEpd0JqL1RE6IryAtUSLmY_M2MBXg_1g/view?usp=drive_link into file artifacts/data_ingestion/data.zip]
[2024-06-24 16:17:01,149: INFO: data_ingestion: Downloaded data from https://drive.google.com/file/d/1OEpd0JqL1RE6IryAtUSLmY_M2MBXg_1g/view?usp=drive_link into file artifacts/data_ingestion/data.zip]
[2024-06-24 16:17:09,983: INFO: main: >>>>>> stage Data Ingestion stage completed <<<<<<

x==========x]
[2024-06-24 16:17:09,983: INFO: main: >>>>>> stage Data Ingestion stage started <<<<<<]
[2024-06-24 16:17:09,983: INFO: common: yaml file: config\config.yaml loaded successfully]
[2024-06-24 16:17:09,983: INFO: common: yaml file: params.yaml loaded successfully]
[2024-06-24 16:17:09,983: INFO: common: created directory at: artifacts]
[2024-06-24 16:17:09,983: INFO: common: created directory at: artifacts/prepare_base_model]
[2024-06-24 16:17:10,627: WARNING: saving_utils: Compiled the loaded model, but the compiled metrics have yet to be built. `model.compile_metrics` will be empty until you train or evaluate the model.]
[2024-06-24 16:17:10,912: INFO: main: >>>>>> stage Data Ingestion stage completed <<<<<<

x==========x]
[2024-06-24 18:33:52,503: INFO: main: >>>>>> stage Data Ingestion stage started <<<<<<]
[2024-06-24 18:33:52,503: INFO: common: yaml file: config\config.yaml loaded successfully]
[2024-06-24 18:33:52,503: INFO: common: yaml file: params.yaml loaded successfully]
[2024-06-24 18:33:52,503: INFO: common: created directory at: artifacts]
[2024-06-24 18:33:52,518: INFO: common: created directory at: artifacts/data_ingestion]
[2024-06-24 18:33:52,518: INFO: data_ingestion: Downloading data from https://drive.google.com/file/d/1OEpd0JqL1RE6IryAtUSLmY_M2MBXg_1g/view?usp=drive_link into file artifacts/data_ingestion/data.zip]
[2024-06-24 18:37:12,484: INFO: main: >>>>>> stage Data Ingestion stage started <<<<<<]
[2024-06-24 18:37:12,501: INFO: common: yaml file: config\config.yaml loaded successfully]
[2024-06-24 18:37:12,501: INFO: common: yaml file: params.yaml loaded successfully]
[2024-06-24 18:37:12,501: INFO: common: created directory at: artifacts]
[2024-06-24 18:37:12,501: INFO: common: created directory at: artifacts/data_ingestion]
[2024-06-24 18:37:12,501: INFO: data_ingestion: Downloading data from https://drive.google.com/file/d/1OEpd0JqL1RE6IryAtUSLmY_M2MBXg_1g/view?usp=drive_link into file artifacts/data_ingestion/data.zip]
[2024-06-24 18:39:30,426: INFO: data_ingestion: Downloaded data from https://drive.google.com/file/d/1OEpd0JqL1RE6IryAtUSLmY_M2MBXg_1g/view?usp=drive_link into file artifacts/data_ingestion/data.zip]
[2024-06-24 18:39:38,887: INFO: main: >>>>>> stage Data Ingestion stage completed <<<<<<

x==========x]
[2024-06-24 18:39:38,887: INFO: main: >>>>>> stage Prepare base model started <<<<<<]
[2024-06-24 18:39:38,887: INFO: common: yaml file: config\config.yaml loaded successfully]
[2024-06-24 18:39:38,887: INFO: common: yaml file: params.yaml loaded successfully]
[2024-06-24 18:39:38,887: INFO: common: created directory at: artifacts]
[2024-06-24 18:39:38,887: INFO: common: created directory at: artifacts/prepare_base_model]
[2024-06-24 18:39:39,491: WARNING: saving_utils: Compiled the loaded model, but the compiled metrics have yet to be built. `model.compile_metrics` will be empty until you train or evaluate the model.]
[2024-06-24 18:39:39,765: INFO: main: >>>>>> stage Prepare base model completed <<<<<<

x==========x]
[2024-06-24 18:39:39,766: INFO: main: >>>>>> stage Model training started <<<<<<]
[2024-06-24 18:39:39,769: INFO: common: yaml file: config\config.yaml loaded successfully]
[2024-06-24 18:39:39,771: INFO: common: yaml file: params.yaml loaded successfully]
[2024-06-24 18:39:39,771: INFO: common: created directory at: artifacts]
[2024-06-24 18:39:39,772: INFO: common: created directory at: artifacts\training]
[2024-06-24 18:39:40,190: ERROR: main: [WinError 3] The system cannot find the path specified: 'artifacts\\data_ingestion\\kidney-ct-scan-image']
Traceback (most recent call last):
  File "main.py", line 36, in <module>
    train.main()
  File "d:\git\deeplearning_classification\src\cnnClassifier\pipeline\stage_03_model_training.py", line 18, in main
    training.train_valid_generator()
  File "d:\git\deeplearning_classification\src\cnnClassifier\components\model_training.py", line 37, in train_valid_generator
    self.valid_generator = valid_datagenerator.flow_from_directory(
  File "C:\Users\ASUS\anaconda3\envs\kidney\lib\site-packages\keras\preprocessing\image.py", line 1648, in flow_from_directory
    return DirectoryIterator(
  File "C:\Users\ASUS\anaconda3\envs\kidney\lib\site-packages\keras\preprocessing\image.py", line 563, in __init__
    for subdir in sorted(os.listdir(directory)):
FileNotFoundError: [WinError 3] The system cannot find the path specified: 'artifacts\\data_ingestion\\kidney-ct-scan-image'
[2024-06-24 19:00:13,218: INFO: main: >>>>>> stage Data Ingestion stage started <<<<<<]
[2024-06-24 19:00:13,233: INFO: common: yaml file: config\config.yaml loaded successfully]
[2024-06-24 19:00:13,244: INFO: common: yaml file: params.yaml loaded successfully]
[2024-06-24 19:00:13,245: INFO: common: created directory at: artifacts]
[2024-06-24 19:00:13,246: INFO: common: created directory at: artifacts/data_ingestion]
[2024-06-24 19:00:13,246: INFO: data_ingestion: Downloading data from https://drive.google.com/file/d/1OEpd0JqL1RE6IryAtUSLmY_M2MBXg_1g/view?usp=drive_link into file artifacts/data_ingestion/data.zip]
[2024-06-24 19:01:42,960: INFO: main: >>>>>> stage Data Ingestion stage started <<<<<<]
[2024-06-24 19:01:42,963: INFO: common: yaml file: config\config.yaml loaded successfully]
[2024-06-24 19:01:42,965: INFO: common: yaml file: params.yaml loaded successfully]
[2024-06-24 19:01:42,965: INFO: common: created directory at: artifacts]
[2024-06-24 19:01:42,966: INFO: common: created directory at: artifacts/data_ingestion]
[2024-06-24 19:01:42,967: INFO: data_ingestion: Downloading data from https://drive.google.com/file/d/1OEpd0JqL1RE6IryAtUSLmY_M2MBXg_1g/view?usp=drive_link into file artifacts/data_ingestion/data.zip]
[2024-06-24 19:04:02,511: INFO: data_ingestion: Downloaded data from https://drive.google.com/file/d/1OEpd0JqL1RE6IryAtUSLmY_M2MBXg_1g/view?usp=drive_link into file artifacts/data_ingestion/data.zip]
[2024-06-24 19:04:11,230: INFO: main: >>>>>> stage Data Ingestion stage completed <<<<<<

x==========x]
[2024-06-24 19:04:11,230: INFO: main: >>>>>> stage Prepare base model started <<<<<<]
[2024-06-24 19:04:11,246: INFO: common: yaml file: config\config.yaml loaded successfully]
[2024-06-24 19:04:11,246: INFO: common: yaml file: params.yaml loaded successfully]
[2024-06-24 19:04:11,246: INFO: common: created directory at: artifacts]
[2024-06-24 19:04:11,254: INFO: common: created directory at: artifacts/prepare_base_model]
[2024-06-24 19:04:11,998: WARNING: saving_utils: Compiled the loaded model, but the compiled metrics have yet to be built. `model.compile_metrics` will be empty until you train or evaluate the model.]
[2024-06-24 19:04:12,276: INFO: main: >>>>>> stage Prepare base model completed <<<<<<

x==========x]
[2024-06-24 19:04:12,277: INFO: main: >>>>>> stage Model training started <<<<<<]
[2024-06-24 19:04:12,280: INFO: common: yaml file: config\config.yaml loaded successfully]
[2024-06-24 19:04:12,280: INFO: common: yaml file: params.yaml loaded successfully]
[2024-06-24 19:04:12,280: INFO: common: created directory at: artifacts]
[2024-06-24 19:04:12,284: INFO: common: created directory at: artifacts\training]
[2024-06-24 19:04:12,768: ERROR: main: [WinError 3] The system cannot find the path specified: 'artifacts\\data_ingestion\\ct-scan-image\\ct-scan-image']
Traceback (most recent call last):
  File "main.py", line 36, in <module>
    train.main()
  File "d:\git\deeplearning_classification\src\cnnClassifier\pipeline\stage_03_model_training.py", line 18, in main
    training.train_valid_generator()
  File "d:\git\deeplearning_classification\src\cnnClassifier\components\model_training.py", line 37, in train_valid_generator
    self.valid_generator = valid_datagenerator.flow_from_directory(
  File "C:\Users\ASUS\anaconda3\envs\kidney\lib\site-packages\keras\preprocessing\image.py", line 1648, in flow_from_directory
    return DirectoryIterator(
  File "C:\Users\ASUS\anaconda3\envs\kidney\lib\site-packages\keras\preprocessing\image.py", line 563, in __init__
    for subdir in sorted(os.listdir(directory)):
FileNotFoundError: [WinError 3] The system cannot find the path specified: 'artifacts\\data_ingestion\\ct-scan-image\\ct-scan-image'
[2024-06-24 19:09:34,538: INFO: main: >>>>>> stage Data Ingestion stage started <<<<<<]
[2024-06-24 19:09:34,538: INFO: main: >>>>>> stage Data Ingestion stage completed <<<<<<

x==========x]
[2024-06-24 19:09:34,538: INFO: main: >>>>>> stage Prepare base model started <<<<<<]
[2024-06-24 19:09:34,538: INFO: common: yaml file: config\config.yaml loaded successfully]
[2024-06-24 19:09:34,538: INFO: common: yaml file: params.yaml loaded successfully]
[2024-06-24 19:09:34,538: INFO: common: created directory at: artifacts]
[2024-06-24 19:09:34,538: INFO: common: created directory at: artifacts/prepare_base_model]
[2024-06-24 19:09:35,021: WARNING: saving_utils: Compiled the loaded model, but the compiled metrics have yet to be built. `model.compile_metrics` will be empty until you train or evaluate the model.]
[2024-06-24 19:09:35,252: INFO: main: >>>>>> stage Prepare base model completed <<<<<<

x==========x]
[2024-06-24 19:09:35,252: INFO: main: >>>>>> stage Model training started <<<<<<]
[2024-06-24 19:09:35,255: INFO: common: yaml file: config\config.yaml loaded successfully]
[2024-06-24 19:09:35,257: INFO: common: yaml file: params.yaml loaded successfully]
[2024-06-24 19:09:35,257: INFO: common: created directory at: artifacts]
[2024-06-24 19:09:35,258: INFO: common: created directory at: artifacts\training]
[2024-06-24 19:09:35,609: ERROR: main: [WinError 3] The system cannot find the path specified: 'artifacts\\data_ingestion\\ct-scan-image\\ct-scan-image']
Traceback (most recent call last):
  File "main.py", line 36, in <module>
    train.main()
  File "d:\git\deeplearning_classification\src\cnnClassifier\pipeline\stage_03_model_training.py", line 18, in main
    training.train_valid_generator()
  File "d:\git\deeplearning_classification\src\cnnClassifier\components\model_training.py", line 37, in train_valid_generator
    self.valid_generator = valid_datagenerator.flow_from_directory(
  File "C:\Users\ASUS\anaconda3\envs\kidney\lib\site-packages\keras\preprocessing\image.py", line 1648, in flow_from_directory
    return DirectoryIterator(
  File "C:\Users\ASUS\anaconda3\envs\kidney\lib\site-packages\keras\preprocessing\image.py", line 563, in __init__
    for subdir in sorted(os.listdir(directory)):
FileNotFoundError: [WinError 3] The system cannot find the path specified: 'artifacts\\data_ingestion\\ct-scan-image\\ct-scan-image'
[2024-06-24 19:14:03,088: INFO: main: >>>>>> stage Data Ingestion stage started <<<<<<]
[2024-06-24 19:14:03,088: INFO: common: yaml file: config\config.yaml loaded successfully]
[2024-06-24 19:14:03,088: INFO: common: yaml file: params.yaml loaded successfully]
[2024-06-24 19:14:03,088: INFO: common: created directory at: artifacts]
[2024-06-24 19:14:03,088: INFO: common: created directory at: artifacts/data_ingestion]
[2024-06-24 19:14:03,104: INFO: data_ingestion: Downloading data from https://drive.google.com/file/d/1OEpd0JqL1RE6IryAtUSLmY_M2MBXg_1g/view?usp=drive_link into file artifacts/data_ingestion/data.zip]
[2024-06-24 19:16:30,860: INFO: data_ingestion: Downloaded data from https://drive.google.com/file/d/1OEpd0JqL1RE6IryAtUSLmY_M2MBXg_1g/view?usp=drive_link into file artifacts/data_ingestion/data.zip]
[2024-06-24 19:16:39,315: INFO: main: >>>>>> stage Data Ingestion stage completed <<<<<<

x==========x]
[2024-06-24 19:16:39,316: INFO: main: >>>>>> stage Prepare base model started <<<<<<]
[2024-06-24 19:16:39,318: INFO: common: yaml file: config\config.yaml loaded successfully]
[2024-06-24 19:16:39,320: INFO: common: yaml file: params.yaml loaded successfully]
[2024-06-24 19:16:39,321: INFO: common: created directory at: artifacts]
[2024-06-24 19:16:39,321: INFO: common: created directory at: artifacts/prepare_base_model]
[2024-06-24 19:16:39,992: WARNING: saving_utils: Compiled the loaded model, but the compiled metrics have yet to be built. `model.compile_metrics` will be empty until you train or evaluate the model.]
[2024-06-24 19:16:40,250: INFO: main: >>>>>> stage Prepare base model completed <<<<<<

x==========x]
[2024-06-24 19:16:40,250: INFO: main: >>>>>> stage Model training started <<<<<<]
[2024-06-24 19:16:40,253: INFO: common: yaml file: config\config.yaml loaded successfully]
[2024-06-24 19:16:40,255: INFO: common: yaml file: params.yaml loaded successfully]
[2024-06-24 19:16:40,255: INFO: common: created directory at: artifacts]
[2024-06-24 19:16:40,256: INFO: common: created directory at: artifacts\training]
[2024-06-24 19:16:40,793: ERROR: main: [WinError 3] The system cannot find the path specified: 'artifacts\\data_ingestion\\ct-scan-image\\ct-scan-image']
Traceback (most recent call last):
  File "main.py", line 36, in <module>
    train.main()
  File "d:\git\deeplearning_classification\src\cnnClassifier\pipeline\stage_03_model_training.py", line 18, in main
    training.train_valid_generator()
  File "d:\git\deeplearning_classification\src\cnnClassifier\components\model_training.py", line 37, in train_valid_generator
    self.valid_generator = valid_datagenerator.flow_from_directory(
  File "C:\Users\ASUS\anaconda3\envs\kidney\lib\site-packages\keras\preprocessing\image.py", line 1648, in flow_from_directory
    return DirectoryIterator(
  File "C:\Users\ASUS\anaconda3\envs\kidney\lib\site-packages\keras\preprocessing\image.py", line 563, in __init__
    for subdir in sorted(os.listdir(directory)):
FileNotFoundError: [WinError 3] The system cannot find the path specified: 'artifacts\\data_ingestion\\ct-scan-image\\ct-scan-image'
[2024-06-24 19:30:17,602: INFO: main: >>>>>> stage Data Ingestion stage started <<<<<<]
[2024-06-24 19:30:17,602: INFO: common: yaml file: config\config.yaml loaded successfully]
[2024-06-24 19:30:17,614: INFO: common: yaml file: params.yaml loaded successfully]
[2024-06-24 19:30:17,615: INFO: common: created directory at: artifacts]
[2024-06-24 19:30:17,616: INFO: common: created directory at: artifacts/data_ingestion]
[2024-06-24 19:30:17,616: INFO: data_ingestion: Downloading data from https://drive.google.com/file/d/1OEpd0JqL1RE6IryAtUSLmY_M2MBXg_1g/view?usp=drive_link into file artifacts/data_ingestion/data.zip]
[2024-06-24 19:32:36,281: INFO: data_ingestion: Downloaded data from https://drive.google.com/file/d/1OEpd0JqL1RE6IryAtUSLmY_M2MBXg_1g/view?usp=drive_link into file artifacts/data_ingestion/data.zip]
[2024-06-24 19:32:44,354: INFO: main: >>>>>> stage Data Ingestion stage completed <<<<<<

x==========x]
[2024-06-24 19:32:44,354: INFO: main: >>>>>> stage Prepare base model started <<<<<<]
[2024-06-24 19:32:44,354: INFO: common: yaml file: config\config.yaml loaded successfully]
[2024-06-24 19:32:44,367: INFO: common: yaml file: params.yaml loaded successfully]
[2024-06-24 19:32:44,368: INFO: common: created directory at: artifacts]
[2024-06-24 19:32:44,370: INFO: common: created directory at: artifacts/prepare_base_model]
[2024-06-24 19:32:45,012: WARNING: saving_utils: Compiled the loaded model, but the compiled metrics have yet to be built. `model.compile_metrics` will be empty until you train or evaluate the model.]
[2024-06-24 19:32:45,260: INFO: main: >>>>>> stage Prepare base model completed <<<<<<

x==========x]
[2024-06-24 19:32:45,261: INFO: main: >>>>>> stage Model training started <<<<<<]
[2024-06-24 19:32:45,267: INFO: common: yaml file: config\config.yaml loaded successfully]
[2024-06-24 19:32:45,269: INFO: common: yaml file: params.yaml loaded successfully]
[2024-06-24 19:32:45,270: INFO: common: created directory at: artifacts]
[2024-06-24 19:32:45,270: INFO: common: created directory at: artifacts\training]
[2024-06-24 19:32:45,730: ERROR: main: [WinError 3] The system cannot find the path specified: 'artifacts\\data_ingestion\\kidney-ct-scan-image']
Traceback (most recent call last):
  File "main.py", line 36, in <module>
    train.main()
  File "d:\git\deeplearning_classification\src\cnnClassifier\pipeline\stage_03_model_training.py", line 20, in main
    training.train_valid_generator()
  File "d:\git\deeplearning_classification\src\cnnClassifier\components\model_training.py", line 37, in train_valid_generator
    self.valid_generator = valid_datagenerator.flow_from_directory(
  File "C:\Users\ASUS\anaconda3\envs\kidney\lib\site-packages\keras\preprocessing\image.py", line 1648, in flow_from_directory
    return DirectoryIterator(
  File "C:\Users\ASUS\anaconda3\envs\kidney\lib\site-packages\keras\preprocessing\image.py", line 563, in __init__
    for subdir in sorted(os.listdir(directory)):
FileNotFoundError: [WinError 3] The system cannot find the path specified: 'artifacts\\data_ingestion\\kidney-ct-scan-image'
[2024-06-24 19:43:10,002: INFO: common: yaml file: config\config.yaml loaded successfully]
[2024-06-24 19:43:10,008: INFO: common: yaml file: params.yaml loaded successfully]
[2024-06-24 19:43:10,011: INFO: common: created directory at: artifacts]
[2024-06-24 19:43:10,013: INFO: common: created directory at: artifacts\training]
[2024-06-24 22:54:56,080: INFO: main: >>>>>> stage Data Ingestion stage started <<<<<<]
[2024-06-24 22:54:56,095: INFO: common: yaml file: config\config.yaml loaded successfully]
[2024-06-24 22:54:56,095: INFO: common: yaml file: params.yaml loaded successfully]
[2024-06-24 22:54:56,102: INFO: common: created directory at: artifacts]
[2024-06-24 22:54:56,102: INFO: common: created directory at: artifacts/data_ingestion]
[2024-06-24 22:54:56,103: INFO: data_ingestion: Downloading data from https://drive.google.com/file/d/1OEpd0JqL1RE6IryAtUSLmY_M2MBXg_1g/view?usp=drive_link into file artifacts/data_ingestion/data.zip]
[2024-06-24 22:57:13,201: INFO: data_ingestion: Downloaded data from https://drive.google.com/file/d/1OEpd0JqL1RE6IryAtUSLmY_M2MBXg_1g/view?usp=drive_link into file artifacts/data_ingestion/data.zip]
[2024-06-24 22:57:24,040: INFO: main: >>>>>> stage Data Ingestion stage completed <<<<<<

x==========x]
[2024-06-24 22:57:24,040: INFO: main: >>>>>> stage Prepare base model started <<<<<<]
[2024-06-24 22:57:24,040: INFO: common: yaml file: config\config.yaml loaded successfully]
[2024-06-24 22:57:24,040: INFO: common: yaml file: params.yaml loaded successfully]
[2024-06-24 22:57:24,040: INFO: common: created directory at: artifacts]
[2024-06-24 22:57:24,054: INFO: common: created directory at: artifacts/prepare_base_model]
[2024-06-24 22:57:24,710: WARNING: saving_utils: Compiled the loaded model, but the compiled metrics have yet to be built. `model.compile_metrics` will be empty until you train or evaluate the model.]
[2024-06-24 22:57:25,118: INFO: main: >>>>>> stage Prepare base model completed <<<<<<

x==========x]
[2024-06-24 22:57:25,120: INFO: main: >>>>>> stage Model training started <<<<<<]
[2024-06-24 22:57:25,130: INFO: common: yaml file: config\config.yaml loaded successfully]
[2024-06-24 22:57:25,136: INFO: common: yaml file: params.yaml loaded successfully]
[2024-06-24 22:57:25,136: INFO: common: created directory at: artifacts]
[2024-06-24 22:57:25,139: INFO: common: created directory at: artifacts\training]
[2024-06-24 22:57:25,820: ERROR: main: [WinError 3] The system cannot find the path specified: 'artifacts\\data_ingestion\\kidney-ct-scan-image']
Traceback (most recent call last):
  File "main.py", line 36, in <module>
    train.main()
  File "d:\git\deeplearning_classification\src\cnnClassifier\pipeline\stage_03_model_training.py", line 20, in main
    training.train_valid_generator()
  File "d:\git\deeplearning_classification\src\cnnClassifier\components\model_training.py", line 37, in train_valid_generator
    self.valid_generator = valid_datagenerator.flow_from_directory(
  File "C:\Users\ASUS\anaconda3\envs\kidney\lib\site-packages\keras\preprocessing\image.py", line 1648, in flow_from_directory
    return DirectoryIterator(
  File "C:\Users\ASUS\anaconda3\envs\kidney\lib\site-packages\keras\preprocessing\image.py", line 563, in __init__
    for subdir in sorted(os.listdir(directory)):
FileNotFoundError: [WinError 3] The system cannot find the path specified: 'artifacts\\data_ingestion\\kidney-ct-scan-image'
[2024-06-24 22:58:37,139: INFO: main: >>>>>> stage Data Ingestion stage started <<<<<<]
[2024-06-24 22:58:37,139: INFO: main: >>>>>> stage Data Ingestion stage completed <<<<<<

x==========x]
[2024-06-24 22:58:37,139: INFO: main: >>>>>> stage Prepare base model started <<<<<<]
[2024-06-24 22:58:37,155: INFO: common: yaml file: config\config.yaml loaded successfully]
[2024-06-24 22:58:37,168: INFO: common: yaml file: params.yaml loaded successfully]
[2024-06-24 22:58:37,171: INFO: common: created directory at: artifacts]
[2024-06-24 22:58:37,172: INFO: common: created directory at: artifacts/prepare_base_model]
[2024-06-24 22:58:37,938: WARNING: saving_utils: Compiled the loaded model, but the compiled metrics have yet to be built. `model.compile_metrics` will be empty until you train or evaluate the model.]
[2024-06-24 22:58:38,249: INFO: main: >>>>>> stage Prepare base model completed <<<<<<

x==========x]
[2024-06-24 22:58:38,250: INFO: main: >>>>>> stage Model training started <<<<<<]
[2024-06-24 22:58:38,256: INFO: common: yaml file: config\config.yaml loaded successfully]
[2024-06-24 22:58:38,260: INFO: common: yaml file: params.yaml loaded successfully]
[2024-06-24 22:58:38,261: INFO: common: created directory at: artifacts]
[2024-06-24 22:58:38,261: INFO: common: created directory at: artifacts\training]
[2024-06-24 22:58:38,792: ERROR: main: [WinError 3] The system cannot find the path specified: 'artifacts\\data_ingestion\\kidney-ct-scan-image']
Traceback (most recent call last):
  File "d:\Git\DeepLearning_Classification\main.py", line 36, in <module>
    train.main()
  File "d:\git\deeplearning_classification\src\cnnClassifier\pipeline\stage_03_model_training.py", line 20, in main
    training.train_valid_generator()
  File "d:\git\deeplearning_classification\src\cnnClassifier\components\model_training.py", line 37, in train_valid_generator
    self.valid_generator = valid_datagenerator.flow_from_directory(
  File "c:\Users\ASUS\AppData\Local\Programs\Python\Python310\lib\site-packages\keras\preprocessing\image.py", line 1648, in flow_from_directory
    return DirectoryIterator(
  File "c:\Users\ASUS\AppData\Local\Programs\Python\Python310\lib\site-packages\keras\preprocessing\image.py", line 563, in __init__
    for subdir in sorted(os.listdir(directory)):
FileNotFoundError: [WinError 3] The system cannot find the path specified: 'artifacts\\data_ingestion\\kidney-ct-scan-image'
[2024-06-25 00:16:54,154: INFO: common: yaml file: config\config.yaml loaded successfully]
[2024-06-25 00:16:54,170: INFO: common: yaml file: params.yaml loaded successfully]
[2024-06-25 00:16:54,172: INFO: common: created directory at: artifacts]
[2024-06-25 00:16:54,174: INFO: common: created directory at: artifacts\training]
[2024-06-25 00:19:04,203: INFO: main: >>>>>> stage Data Ingestion stage started <<<<<<]
[2024-06-25 00:19:04,203: INFO: main: >>>>>> stage Data Ingestion stage completed <<<<<<

x==========x]
[2024-06-25 00:19:04,219: INFO: main: >>>>>> stage Prepare base model started <<<<<<]
[2024-06-25 00:19:04,219: INFO: common: yaml file: config\config.yaml loaded successfully]
[2024-06-25 00:19:04,228: INFO: common: yaml file: params.yaml loaded successfully]
[2024-06-25 00:19:04,230: INFO: common: created directory at: artifacts]
[2024-06-25 00:19:04,230: INFO: common: created directory at: artifacts/prepare_base_model]
[2024-06-25 00:19:04,679: WARNING: saving_utils: Compiled the loaded model, but the compiled metrics have yet to be built. `model.compile_metrics` will be empty until you train or evaluate the model.]
[2024-06-25 00:19:04,902: INFO: main: >>>>>> stage Prepare base model completed <<<<<<

x==========x]
[2024-06-25 00:19:04,903: INFO: main: >>>>>> stage Model training started <<<<<<]
[2024-06-25 00:19:04,905: INFO: common: yaml file: config\config.yaml loaded successfully]
[2024-06-25 00:19:04,907: INFO: common: yaml file: params.yaml loaded successfully]
[2024-06-25 00:19:04,908: INFO: common: created directory at: artifacts]
[2024-06-25 00:19:04,908: INFO: common: created directory at: artifacts\training]
[2024-06-25 00:19:05,289: ERROR: main: [WinError 3] The system cannot find the path specified: 'artifacts\\data_ingestion\\ct-scan-image\\kidney-ct-scan-image']
Traceback (most recent call last):
  File "main.py", line 36, in <module>
    train.main()
  File "d:\git\deeplearning_classification\src\cnnClassifier\pipeline\stage_03_model_training.py", line 20, in main
    training.train_valid_generator()
  File "d:\git\deeplearning_classification\src\cnnClassifier\components\model_training.py", line 37, in train_valid_generator
    self.valid_generator = valid_datagenerator.flow_from_directory(
  File "C:\Users\ASUS\anaconda3\envs\kidney\lib\site-packages\keras\preprocessing\image.py", line 1648, in flow_from_directory
    return DirectoryIterator(
  File "C:\Users\ASUS\anaconda3\envs\kidney\lib\site-packages\keras\preprocessing\image.py", line 563, in __init__
    for subdir in sorted(os.listdir(directory)):
FileNotFoundError: [WinError 3] The system cannot find the path specified: 'artifacts\\data_ingestion\\ct-scan-image\\kidney-ct-scan-image'
[2024-06-25 12:14:05,114: INFO: main: >>>>>> stage Data Ingestion stage started <<<<<<]
[2024-06-25 12:14:05,114: INFO: main: >>>>>> stage Data Ingestion stage completed <<<<<<

x==========x]
[2024-06-25 12:14:05,114: INFO: main: >>>>>> stage Prepare base model started <<<<<<]
[2024-06-25 12:14:05,114: INFO: common: yaml file: config\config.yaml loaded successfully]
[2024-06-25 12:14:05,114: INFO: common: yaml file: params.yaml loaded successfully]
[2024-06-25 12:14:05,130: INFO: common: created directory at: artifacts]
[2024-06-25 12:14:05,130: INFO: common: created directory at: artifacts/prepare_base_model]
[2024-06-25 12:14:05,799: WARNING: saving_utils: Compiled the loaded model, but the compiled metrics have yet to be built. `model.compile_metrics` will be empty until you train or evaluate the model.]
[2024-06-25 12:14:06,033: INFO: main: >>>>>> stage Prepare base model completed <<<<<<

x==========x]
[2024-06-25 12:14:06,033: INFO: main: >>>>>> stage Model training started <<<<<<]
[2024-06-25 12:14:06,033: INFO: common: yaml file: config\config.yaml loaded successfully]
[2024-06-25 12:14:06,048: INFO: common: yaml file: params.yaml loaded successfully]
[2024-06-25 12:14:06,049: INFO: common: created directory at: artifacts]
[2024-06-25 12:14:06,049: INFO: common: created directory at: artifacts\training]
[2024-06-25 12:14:06,417: ERROR: main: [WinError 3] The system cannot find the path specified: 'artifacts\\data_ingestion\\ct-scan-image\\CT_SCAN']
Traceback (most recent call last):
  File "main.py", line 36, in <module>
    train.main()
  File "d:\git\deeplearning_classification\src\cnnClassifier\pipeline\stage_03_model_training.py", line 20, in main
    training.train_valid_generator()
  File "d:\git\deeplearning_classification\src\cnnClassifier\components\model_training.py", line 37, in train_valid_generator
    self.valid_generator = valid_datagenerator.flow_from_directory(
  File "C:\Users\ASUS\anaconda3\envs\kidney\lib\site-packages\keras\preprocessing\image.py", line 1648, in flow_from_directory
    return DirectoryIterator(
  File "C:\Users\ASUS\anaconda3\envs\kidney\lib\site-packages\keras\preprocessing\image.py", line 563, in __init__
    for subdir in sorted(os.listdir(directory)):
FileNotFoundError: [WinError 3] The system cannot find the path specified: 'artifacts\\data_ingestion\\ct-scan-image\\CT_SCAN'
[2024-06-25 12:15:11,656: INFO: main: >>>>>> stage Data Ingestion stage started <<<<<<]
[2024-06-25 12:15:11,656: INFO: common: yaml file: config\config.yaml loaded successfully]
[2024-06-25 12:15:11,656: INFO: common: yaml file: params.yaml loaded successfully]
[2024-06-25 12:15:11,656: INFO: common: created directory at: artifacts]
[2024-06-25 12:15:11,656: INFO: common: created directory at: artifacts/data_ingestion]
[2024-06-25 12:15:11,671: INFO: data_ingestion: Downloading data from https://drive.google.com/file/d/1yLiUUVor0xmtWE830IpivUwYUKS43jfV/view?usp=drive_link into file artifacts/data_ingestion/data.zip]
[2024-06-25 12:17:15,480: INFO: data_ingestion: Downloaded data from https://drive.google.com/file/d/1yLiUUVor0xmtWE830IpivUwYUKS43jfV/view?usp=drive_link into file artifacts/data_ingestion/data.zip]
[2024-06-25 12:17:23,725: INFO: main: >>>>>> stage Data Ingestion stage completed <<<<<<

x==========x]
[2024-06-25 12:17:23,725: INFO: main: >>>>>> stage Prepare base model started <<<<<<]
[2024-06-25 12:17:23,725: INFO: common: yaml file: config\config.yaml loaded successfully]
[2024-06-25 12:17:23,725: INFO: common: yaml file: params.yaml loaded successfully]
[2024-06-25 12:17:23,725: INFO: common: created directory at: artifacts]
[2024-06-25 12:17:23,725: INFO: common: created directory at: artifacts/prepare_base_model]
[2024-06-25 12:17:24,264: WARNING: saving_utils: Compiled the loaded model, but the compiled metrics have yet to be built. `model.compile_metrics` will be empty until you train or evaluate the model.]
[2024-06-25 12:17:24,512: INFO: main: >>>>>> stage Prepare base model completed <<<<<<

x==========x]
[2024-06-25 12:17:24,513: INFO: main: >>>>>> stage Model training started <<<<<<]
[2024-06-25 12:17:24,519: INFO: common: yaml file: config\config.yaml loaded successfully]
[2024-06-25 12:17:24,521: INFO: common: yaml file: params.yaml loaded successfully]
[2024-06-25 12:17:24,522: INFO: common: created directory at: artifacts]
[2024-06-25 12:17:24,523: INFO: common: created directory at: artifacts\training]
[2024-06-25 12:17:42,420: ERROR: main: Graph execution error:

FileNotFoundError: [Errno 2] No such file or directory: 'artifacts\\data_ingestion\\CT_SCAN\\Normal\\Normal- (3011).jpg'
Traceback (most recent call last):

  File "C:\Users\ASUS\anaconda3\envs\kidney\lib\site-packages\tensorflow\python\ops\script_ops.py", line 267, in __call__
    ret = func(*args)

  File "C:\Users\ASUS\anaconda3\envs\kidney\lib\site-packages\tensorflow\python\autograph\impl\api.py", line 642, in wrapper
    return func(*args, **kwargs)

  File "C:\Users\ASUS\anaconda3\envs\kidney\lib\site-packages\tensorflow\python\data\ops\from_generator_op.py", line 198, in generator_py_func
    values = next(generator_state.get_iterator(iterator_id))

  File "C:\Users\ASUS\anaconda3\envs\kidney\lib\site-packages\keras\engine\data_adapter.py", line 902, in wrapped_generator
    for data in generator_fn():

  File "C:\Users\ASUS\anaconda3\envs\kidney\lib\site-packages\keras\engine\data_adapter.py", line 1049, in generator_fn
    yield x[i]

  File "C:\Users\ASUS\anaconda3\envs\kidney\lib\site-packages\keras\preprocessing\image.py", line 116, in __getitem__
    return self._get_batches_of_transformed_samples(index_array)

  File "C:\Users\ASUS\anaconda3\envs\kidney\lib\site-packages\keras\preprocessing\image.py", line 370, in _get_batches_of_transformed_samples
    img = image_utils.load_img(

  File "C:\Users\ASUS\anaconda3\envs\kidney\lib\site-packages\keras\utils\image_utils.py", line 422, in load_img
    with open(path, "rb") as f:

FileNotFoundError: [Errno 2] No such file or directory: 'artifacts\\data_ingestion\\CT_SCAN\\Normal\\Normal- (3011).jpg'


	 [[{{node PyFunc}}]]
	 [[IteratorGetNext]] [Op:__inference_train_function_1463]]
Traceback (most recent call last):
  File "main.py", line 36, in <module>
    train.main()
  File "d:\git\deeplearning_classification\src\cnnClassifier\pipeline\stage_03_model_training.py", line 21, in main
    training.train()
  File "d:\git\deeplearning_classification\src\cnnClassifier\components\model_training.py", line 76, in train
    self.model.fit(
  File "C:\Users\ASUS\anaconda3\envs\kidney\lib\site-packages\keras\utils\traceback_utils.py", line 70, in error_handler
    raise e.with_traceback(filtered_tb) from None
  File "C:\Users\ASUS\anaconda3\envs\kidney\lib\site-packages\tensorflow\python\eager\execute.py", line 52, in quick_execute
    tensors = pywrap_tfe.TFE_Py_Execute(ctx._handle, device_name, op_name,
tensorflow.python.framework.errors_impl.UnknownError: Graph execution error:

FileNotFoundError: [Errno 2] No such file or directory: 'artifacts\\data_ingestion\\CT_SCAN\\Normal\\Normal- (3011).jpg'
Traceback (most recent call last):

  File "C:\Users\ASUS\anaconda3\envs\kidney\lib\site-packages\tensorflow\python\ops\script_ops.py", line 267, in __call__
    ret = func(*args)

  File "C:\Users\ASUS\anaconda3\envs\kidney\lib\site-packages\tensorflow\python\autograph\impl\api.py", line 642, in wrapper
    return func(*args, **kwargs)

  File "C:\Users\ASUS\anaconda3\envs\kidney\lib\site-packages\tensorflow\python\data\ops\from_generator_op.py", line 198, in generator_py_func
    values = next(generator_state.get_iterator(iterator_id))

  File "C:\Users\ASUS\anaconda3\envs\kidney\lib\site-packages\keras\engine\data_adapter.py", line 902, in wrapped_generator
    for data in generator_fn():

  File "C:\Users\ASUS\anaconda3\envs\kidney\lib\site-packages\keras\engine\data_adapter.py", line 1049, in generator_fn
    yield x[i]

  File "C:\Users\ASUS\anaconda3\envs\kidney\lib\site-packages\keras\preprocessing\image.py", line 116, in __getitem__
    return self._get_batches_of_transformed_samples(index_array)

  File "C:\Users\ASUS\anaconda3\envs\kidney\lib\site-packages\keras\preprocessing\image.py", line 370, in _get_batches_of_transformed_samples
    img = image_utils.load_img(

  File "C:\Users\ASUS\anaconda3\envs\kidney\lib\site-packages\keras\utils\image_utils.py", line 422, in load_img
    with open(path, "rb") as f:

FileNotFoundError: [Errno 2] No such file or directory: 'artifacts\\data_ingestion\\CT_SCAN\\Normal\\Normal- (3011).jpg'


	 [[{{node PyFunc}}]]
	 [[IteratorGetNext]] [Op:__inference_train_function_1463]
[2024-06-25 12:20:40,411: INFO: main: >>>>>> stage Data Ingestion stage started <<<<<<]
[2024-06-25 12:20:40,411: INFO: common: yaml file: config\config.yaml loaded successfully]
[2024-06-25 12:20:40,411: INFO: common: yaml file: params.yaml loaded successfully]
[2024-06-25 12:20:40,411: INFO: common: created directory at: artifacts]
[2024-06-25 12:20:40,418: INFO: common: created directory at: artifacts/data_ingestion]
[2024-06-25 12:20:40,418: INFO: data_ingestion: Downloading data from https://drive.google.com/file/d/1yLiUUVor0xmtWE830IpivUwYUKS43jfV/view?usp=drive_link into file artifacts/data_ingestion/data.zip]
[2024-06-25 12:22:42,303: INFO: data_ingestion: Downloaded data from https://drive.google.com/file/d/1yLiUUVor0xmtWE830IpivUwYUKS43jfV/view?usp=drive_link into file artifacts/data_ingestion/data.zip]
[2024-06-25 12:22:50,669: INFO: main: >>>>>> stage Data Ingestion stage completed <<<<<<

x==========x]
[2024-06-25 12:22:50,669: INFO: main: >>>>>> stage Prepare base model started <<<<<<]
[2024-06-25 12:22:50,669: INFO: common: yaml file: config\config.yaml loaded successfully]
[2024-06-25 12:22:50,669: INFO: common: yaml file: params.yaml loaded successfully]
[2024-06-25 12:22:50,669: INFO: common: created directory at: artifacts]
[2024-06-25 12:22:50,685: INFO: common: created directory at: artifacts/prepare_base_model]
[2024-06-25 12:22:51,176: WARNING: saving_utils: Compiled the loaded model, but the compiled metrics have yet to be built. `model.compile_metrics` will be empty until you train or evaluate the model.]
[2024-06-25 12:22:51,439: INFO: main: >>>>>> stage Prepare base model completed <<<<<<

x==========x]
[2024-06-25 12:22:51,439: INFO: main: >>>>>> stage Model training started <<<<<<]
[2024-06-25 12:22:51,439: INFO: common: yaml file: config\config.yaml loaded successfully]
[2024-06-25 12:22:51,439: INFO: common: yaml file: params.yaml loaded successfully]
[2024-06-25 12:22:51,439: INFO: common: created directory at: artifacts]
[2024-06-25 12:22:51,453: INFO: common: created directory at: artifacts\training]
[2024-06-25 12:42:54,691: INFO: main: >>>>>> stage Model training completed <<<<<<

x==========x]
[2024-06-26 13:51:08,756: INFO: common: yaml file: config\config.yaml loaded successfully]
[2024-06-26 13:51:08,772: INFO: common: yaml file: params.yaml loaded successfully]
[2024-06-26 13:51:08,775: INFO: common: created directory at: artifacts]
[2024-06-26 15:49:06,467: INFO: common: yaml file: config\config.yaml loaded successfully]
[2024-06-26 15:49:06,488: INFO: common: yaml file: params.yaml loaded successfully]
[2024-06-26 15:49:06,489: INFO: common: created directory at: artifacts]
[2024-06-26 15:55:43,663: INFO: common: yaml file: config\config.yaml loaded successfully]
[2024-06-26 15:55:43,663: INFO: common: yaml file: params.yaml loaded successfully]
[2024-06-26 15:55:43,663: INFO: common: created directory at: artifacts]
[2024-06-26 16:01:41,501: INFO: common: json file saved at: scores.json]
[2024-06-26 16:01:44,535: WARNING: save: Found untraced functions such as _jit_compiled_convolution_op, _jit_compiled_convolution_op, _jit_compiled_convolution_op, _jit_compiled_convolution_op, _jit_compiled_convolution_op while saving (showing 5 of 14). These functions will not be directly callable after loading.]
[2024-06-26 16:01:45,235: INFO: builder_impl: Assets written to: C:\Users\ASUS\AppData\Local\Temp\tmprx57bgsa\model\data\model\assets]
[2024-06-27 11:53:47,693: INFO: common: yaml file: config\config.yaml loaded successfully]
[2024-06-27 11:53:47,708: INFO: common: yaml file: params.yaml loaded successfully]
[2024-06-27 11:53:47,709: INFO: common: created directory at: artifacts]
[2024-06-27 12:00:15,174: INFO: common: json file saved at: scores.json]
[2024-06-27 12:00:20,071: WARNING: save: Found untraced functions such as _jit_compiled_convolution_op, _jit_compiled_convolution_op, _jit_compiled_convolution_op, _jit_compiled_convolution_op, _jit_compiled_convolution_op while saving (showing 5 of 14). These functions will not be directly callable after loading.]
[2024-06-27 12:00:21,634: INFO: builder_impl: Assets written to: C:\Users\ASUS\AppData\Local\Temp\tmpfg7b1nbt\model\data\model\assets]
[2024-06-27 12:35:15,678: INFO: main: >>>>>> stage Data Ingestion stage started <<<<<<]
[2024-06-27 12:35:15,678: INFO: common: yaml file: config\config.yaml loaded successfully]
[2024-06-27 12:35:15,695: INFO: common: yaml file: params.yaml loaded successfully]
[2024-06-27 12:35:15,696: INFO: common: created directory at: artifacts]
[2024-06-27 12:35:15,697: INFO: common: created directory at: artifacts/data_ingestion]
[2024-06-27 12:35:15,697: INFO: data_ingestion: Downloading data from https://drive.google.com/file/d/1yLiUUVor0xmtWE830IpivUwYUKS43jfV/view?usp=drive_link into file artifacts/data_ingestion/data.zip]
[2024-06-27 12:37:23,904: INFO: data_ingestion: Downloaded data from https://drive.google.com/file/d/1yLiUUVor0xmtWE830IpivUwYUKS43jfV/view?usp=drive_link into file artifacts/data_ingestion/data.zip]
[2024-06-27 12:37:39,771: INFO: main: >>>>>> stage Data Ingestion stage completed <<<<<<

x==========x]
[2024-06-27 12:37:39,771: INFO: main: >>>>>> stage Prepare base model started <<<<<<]
[2024-06-27 12:37:39,771: INFO: common: yaml file: config\config.yaml loaded successfully]
[2024-06-27 12:37:39,771: INFO: common: yaml file: params.yaml loaded successfully]
[2024-06-27 12:37:39,771: INFO: common: created directory at: artifacts]
[2024-06-27 12:37:39,787: INFO: common: created directory at: artifacts/prepare_base_model]
[2024-06-27 12:37:40,369: WARNING: saving_utils: Compiled the loaded model, but the compiled metrics have yet to be built. `model.compile_metrics` will be empty until you train or evaluate the model.]
[2024-06-27 12:37:40,663: INFO: main: >>>>>> stage Prepare base model completed <<<<<<

x==========x]
[2024-06-27 12:37:40,664: INFO: main: >>>>>> stage Model training started <<<<<<]
[2024-06-27 12:37:40,667: INFO: common: yaml file: config\config.yaml loaded successfully]
[2024-06-27 12:37:40,667: INFO: common: yaml file: params.yaml loaded successfully]
[2024-06-27 12:37:40,667: INFO: common: created directory at: artifacts]
[2024-06-27 12:37:40,669: INFO: common: created directory at: artifacts\training]
[2024-06-27 12:58:07,560: INFO: main: >>>>>> stage Model training completed <<<<<<

x==========x]
[2024-06-27 12:58:07,560: INFO: main: *******************]
[2024-06-27 12:58:07,560: INFO: main: >>>>>> stage Model Evaluation started <<<<<<]
[2024-06-27 12:58:07,563: INFO: common: yaml file: config\config.yaml loaded successfully]
[2024-06-27 12:58:07,565: INFO: common: yaml file: params.yaml loaded successfully]
[2024-06-27 12:58:07,566: INFO: common: created directory at: artifacts]
[2024-06-27 13:04:19,225: INFO: common: json file saved at: scores.json]
[2024-06-27 13:04:19,225: INFO: common: json file saved at: scores.json]
[2024-06-27 13:04:21,192: WARNING: save: Found untraced functions such as _jit_compiled_convolution_op, _jit_compiled_convolution_op, _jit_compiled_convolution_op, _jit_compiled_convolution_op, _jit_compiled_convolution_op while saving (showing 5 of 14). These functions will not be directly callable after loading.]
[2024-06-27 13:04:21,851: INFO: builder_impl: Assets written to: C:\Users\ASUS\AppData\Local\Temp\tmpryssv4kn\model\data\model\assets]
[2024-06-27 13:04:32,161: INFO: dir_util: creating D:\Git\DeepLearning_Classification\mlruns\0\a6604ed67a724b278e272fe2f2d7f7fe\artifacts\model\data]
[2024-06-27 13:04:32,161: INFO: dir_util: creating D:\Git\DeepLearning_Classification\mlruns\0\a6604ed67a724b278e272fe2f2d7f7fe\artifacts\model\data\model]
[2024-06-27 13:04:32,161: INFO: dir_util: creating D:\Git\DeepLearning_Classification\mlruns\0\a6604ed67a724b278e272fe2f2d7f7fe\artifacts\model\data\model\assets]
[2024-06-27 13:04:32,161: INFO: dir_util: creating D:\Git\DeepLearning_Classification\mlruns\0\a6604ed67a724b278e272fe2f2d7f7fe\artifacts\model\data\model\variables]
[2024-06-27 13:04:32,277: INFO: main: >>>>>> stage Model Evaluation completed <<<<<<

x==========x]
[2024-06-27 13:24:31,877: INFO: main: >>>>>> stage Data Ingestion stage started <<<<<<]
[2024-06-27 13:24:31,877: INFO: main: >>>>>> stage Data Ingestion stage completed <<<<<<

x==========x]
[2024-06-27 13:24:31,877: INFO: main: >>>>>> stage Prepare base model started <<<<<<]
[2024-06-27 13:24:31,893: INFO: common: yaml file: config\config.yaml loaded successfully]
[2024-06-27 13:24:31,893: INFO: common: yaml file: params.yaml loaded successfully]
[2024-06-27 13:24:31,893: INFO: common: created directory at: artifacts]
[2024-06-27 13:24:31,893: INFO: common: created directory at: artifacts/prepare_base_model]
[2024-06-27 13:24:32,349: WARNING: saving_utils: Compiled the loaded model, but the compiled metrics have yet to be built. `model.compile_metrics` will be empty until you train or evaluate the model.]
[2024-06-27 13:24:32,569: INFO: main: >>>>>> stage Prepare base model completed <<<<<<

x==========x]
[2024-06-27 13:24:32,569: INFO: main: >>>>>> stage Model training started <<<<<<]
[2024-06-27 13:24:32,583: INFO: common: yaml file: config\config.yaml loaded successfully]
[2024-06-27 13:24:32,585: INFO: common: yaml file: params.yaml loaded successfully]
[2024-06-27 13:24:32,586: INFO: common: created directory at: artifacts]
[2024-06-27 13:24:32,587: INFO: common: created directory at: artifacts\training]
[2024-06-27 13:43:54,425: INFO: main: >>>>>> stage Model training completed <<<<<<

x==========x]
[2024-06-27 13:43:54,425: INFO: main: *******************]
[2024-06-27 13:43:54,425: INFO: main: >>>>>> stage Model Evaluation started <<<<<<]
[2024-06-27 13:43:54,425: INFO: common: yaml file: config\config.yaml loaded successfully]
[2024-06-27 13:43:54,425: INFO: common: yaml file: params.yaml loaded successfully]
[2024-06-27 13:43:54,425: INFO: common: created directory at: artifacts]
[2024-06-27 13:49:33,123: INFO: common: json file saved at: scores.json]
[2024-06-27 13:49:33,123: INFO: common: json file saved at: scores.json]
[2024-06-27 13:49:34,824: WARNING: save: Found untraced functions such as _jit_compiled_convolution_op, _jit_compiled_convolution_op, _jit_compiled_convolution_op, _jit_compiled_convolution_op, _jit_compiled_convolution_op while saving (showing 5 of 14). These functions will not be directly callable after loading.]
[2024-06-27 13:49:35,500: INFO: builder_impl: Assets written to: C:\Users\ASUS\AppData\Local\Temp\tmphn5vppr9\model\data\model\assets]
[2024-06-27 13:49:46,190: INFO: dir_util: creating D:\Git\DeepLearning_Classification\mlruns\0\52252013d9494aad808dc174299a5016\artifacts\model\data]
[2024-06-27 13:49:46,192: INFO: dir_util: creating D:\Git\DeepLearning_Classification\mlruns\0\52252013d9494aad808dc174299a5016\artifacts\model\data\model]
[2024-06-27 13:49:46,193: INFO: dir_util: creating D:\Git\DeepLearning_Classification\mlruns\0\52252013d9494aad808dc174299a5016\artifacts\model\data\model\assets]
[2024-06-27 13:49:46,202: INFO: dir_util: creating D:\Git\DeepLearning_Classification\mlruns\0\52252013d9494aad808dc174299a5016\artifacts\model\data\model\variables]
[2024-06-27 13:49:46,314: INFO: main: >>>>>> stage Model Evaluation completed <<<<<<

x==========x]
[2024-06-27 16:21:05,018: INFO: main: >>>>>> stage Data Ingestion stage started <<<<<<]
[2024-06-27 16:21:05,018: INFO: main: >>>>>> stage Data Ingestion stage completed <<<<<<

x==========x]
[2024-06-27 16:21:05,018: INFO: main: >>>>>> stage Prepare base model started <<<<<<]
[2024-06-27 16:21:05,034: INFO: common: yaml file: config\config.yaml loaded successfully]
[2024-06-27 16:21:05,040: INFO: common: yaml file: params.yaml loaded successfully]
[2024-06-27 16:21:05,040: INFO: common: created directory at: artifacts]
[2024-06-27 16:21:05,040: INFO: common: created directory at: artifacts/prepare_base_model]
[2024-06-27 16:21:05,601: WARNING: saving_utils: Compiled the loaded model, but the compiled metrics have yet to be built. `model.compile_metrics` will be empty until you train or evaluate the model.]
[2024-06-27 16:21:05,853: INFO: main: >>>>>> stage Prepare base model completed <<<<<<

x==========x]
[2024-06-27 16:21:05,853: INFO: main: >>>>>> stage Model training started <<<<<<]
[2024-06-27 16:21:05,853: INFO: common: yaml file: config\config.yaml loaded successfully]
[2024-06-27 16:21:05,853: INFO: common: yaml file: params.yaml loaded successfully]
[2024-06-27 16:21:05,853: INFO: common: created directory at: artifacts]
[2024-06-27 16:21:05,853: INFO: common: created directory at: artifacts\training]
[2024-06-27 16:40:47,585: INFO: main: >>>>>> stage Model training completed <<<<<<

x==========x]
[2024-06-27 16:40:47,585: INFO: main: *******************]
[2024-06-27 16:40:47,585: INFO: main: >>>>>> stage Model Evaluation started <<<<<<]
[2024-06-27 16:40:47,588: INFO: common: yaml file: config\config.yaml loaded successfully]
[2024-06-27 16:40:47,589: INFO: common: yaml file: params.yaml loaded successfully]
[2024-06-27 16:40:47,590: INFO: common: created directory at: artifacts]
[2024-06-27 16:46:37,292: INFO: common: json file saved at: scores.json]
[2024-06-27 16:46:37,293: INFO: common: json file saved at: scores.json]
[2024-06-27 16:46:39,112: WARNING: save: Found untraced functions such as _jit_compiled_convolution_op, _jit_compiled_convolution_op, _jit_compiled_convolution_op, _jit_compiled_convolution_op, _jit_compiled_convolution_op while saving (showing 5 of 14). These functions will not be directly callable after loading.]
[2024-06-27 16:46:39,865: INFO: builder_impl: Assets written to: C:\Users\ASUS\AppData\Local\Temp\tmpfab4fwhc\model\data\model\assets]
[2024-06-27 16:46:48,541: INFO: dir_util: creating D:\Git\DeepLearning_Classification\mlruns\0\2e496bdd69914490b5ddb5b5774a5ebd\artifacts\model\data]
[2024-06-27 16:46:48,543: INFO: dir_util: creating D:\Git\DeepLearning_Classification\mlruns\0\2e496bdd69914490b5ddb5b5774a5ebd\artifacts\model\data\model]
[2024-06-27 16:46:48,543: INFO: dir_util: creating D:\Git\DeepLearning_Classification\mlruns\0\2e496bdd69914490b5ddb5b5774a5ebd\artifacts\model\data\model\assets]
[2024-06-27 16:46:48,549: INFO: dir_util: creating D:\Git\DeepLearning_Classification\mlruns\0\2e496bdd69914490b5ddb5b5774a5ebd\artifacts\model\data\model\variables]
[2024-06-27 16:46:48,638: INFO: main: >>>>>> stage Model Evaluation completed <<<<<<

x==========x]
[2024-06-27 17:26:03,270: INFO: helpers: Initialized MLflow to track repo "delphineasir/DeepLearning_Classification"]
[2024-06-27 17:26:03,270: INFO: helpers: Repository delphineasir/DeepLearning_Classification initialized!]
[2024-06-27 17:28:04,082: INFO: helpers: Initialized MLflow to track repo "delphineasir/DeepLearning_Classification"]
[2024-06-27 17:28:04,082: INFO: helpers: Repository delphineasir/DeepLearning_Classification initialized!]
[2024-06-27 17:29:11,866: INFO: main: >>>>>> stage Data Ingestion stage started <<<<<<]
[2024-06-27 17:29:11,866: INFO: main: >>>>>> stage Data Ingestion stage completed <<<<<<

x==========x]
[2024-06-27 17:29:11,866: INFO: main: >>>>>> stage Prepare base model started <<<<<<]
[2024-06-27 17:29:11,866: INFO: common: yaml file: config\config.yaml loaded successfully]
[2024-06-27 17:29:11,866: INFO: common: yaml file: params.yaml loaded successfully]
[2024-06-27 17:29:11,866: INFO: common: created directory at: artifacts]
[2024-06-27 17:29:11,881: INFO: common: created directory at: artifacts/prepare_base_model]
[2024-06-27 17:29:12,373: WARNING: saving_utils: Compiled the loaded model, but the compiled metrics have yet to be built. `model.compile_metrics` will be empty until you train or evaluate the model.]
[2024-06-27 17:29:12,604: INFO: main: >>>>>> stage Prepare base model completed <<<<<<

x==========x]
[2024-06-27 17:29:12,604: INFO: main: >>>>>> stage Model training started <<<<<<]
[2024-06-27 17:29:12,607: INFO: common: yaml file: config\config.yaml loaded successfully]
[2024-06-27 17:29:12,609: INFO: common: yaml file: params.yaml loaded successfully]
[2024-06-27 17:29:12,609: INFO: common: created directory at: artifacts]
[2024-06-27 17:29:12,610: INFO: common: created directory at: artifacts\training]
[2024-06-27 17:48:04,386: INFO: main: >>>>>> stage Model training completed <<<<<<

x==========x]
[2024-06-27 17:48:04,387: INFO: main: *******************]
[2024-06-27 17:48:04,387: INFO: main: >>>>>> stage Model Evaluation started <<<<<<]
[2024-06-27 17:48:04,391: INFO: common: yaml file: config\config.yaml loaded successfully]
[2024-06-27 17:48:04,392: INFO: common: yaml file: params.yaml loaded successfully]
[2024-06-27 17:48:04,393: INFO: common: created directory at: artifacts]
[2024-06-27 17:53:42,686: INFO: common: json file saved at: scores.json]
[2024-06-27 17:53:42,687: INFO: common: json file saved at: scores.json]
[2024-06-27 17:53:44,349: WARNING: save: Found untraced functions such as _jit_compiled_convolution_op, _jit_compiled_convolution_op, _jit_compiled_convolution_op, _jit_compiled_convolution_op, _jit_compiled_convolution_op while saving (showing 5 of 14). These functions will not be directly callable after loading.]
[2024-06-27 17:53:45,044: INFO: builder_impl: Assets written to: C:\Users\ASUS\AppData\Local\Temp\tmp7bnwimbs\model\data\model\assets]
[2024-06-27 17:53:53,433: INFO: dir_util: creating D:\Git\DeepLearning_Classification\mlruns\0\9058b5246e0647bab90065dbd73b26b9\artifacts\model\data]
[2024-06-27 17:53:53,435: INFO: dir_util: creating D:\Git\DeepLearning_Classification\mlruns\0\9058b5246e0647bab90065dbd73b26b9\artifacts\model\data\model]
[2024-06-27 17:53:53,435: INFO: dir_util: creating D:\Git\DeepLearning_Classification\mlruns\0\9058b5246e0647bab90065dbd73b26b9\artifacts\model\data\model\assets]
[2024-06-27 17:53:53,438: INFO: dir_util: creating D:\Git\DeepLearning_Classification\mlruns\0\9058b5246e0647bab90065dbd73b26b9\artifacts\model\data\model\variables]
[2024-06-27 17:53:53,521: INFO: main: >>>>>> stage Model Evaluation completed <<<<<<

x==========x]
[2024-06-27 19:00:55,269: INFO: main: >>>>>> stage Data Ingestion stage started <<<<<<]
[2024-06-27 19:00:55,269: INFO: main: >>>>>> stage Data Ingestion stage completed <<<<<<

x==========x]
[2024-06-27 19:00:55,269: INFO: main: >>>>>> stage Prepare base model started <<<<<<]
[2024-06-27 19:00:55,285: INFO: common: yaml file: config\config.yaml loaded successfully]
[2024-06-27 19:00:55,285: INFO: common: yaml file: params.yaml loaded successfully]
[2024-06-27 19:00:55,285: INFO: common: created directory at: artifacts]
[2024-06-27 19:00:55,285: INFO: common: created directory at: artifacts/prepare_base_model]
[2024-06-27 19:00:55,728: WARNING: saving_utils: Compiled the loaded model, but the compiled metrics have yet to be built. `model.compile_metrics` will be empty until you train or evaluate the model.]
[2024-06-27 19:00:55,984: INFO: main: >>>>>> stage Prepare base model completed <<<<<<

x==========x]
[2024-06-27 19:00:55,985: INFO: main: >>>>>> stage Model training started <<<<<<]
[2024-06-27 19:00:55,988: INFO: common: yaml file: config\config.yaml loaded successfully]
[2024-06-27 19:00:55,990: INFO: common: yaml file: params.yaml loaded successfully]
[2024-06-27 19:00:55,990: INFO: common: created directory at: artifacts]
[2024-06-27 19:00:55,991: INFO: common: created directory at: artifacts\training]
[2024-06-27 19:20:35,579: INFO: main: >>>>>> stage Model training completed <<<<<<

x==========x]
[2024-06-27 19:20:35,579: INFO: main: *******************]
[2024-06-27 19:20:35,579: INFO: main: >>>>>> stage Model Evaluation started <<<<<<]
[2024-06-27 19:20:35,579: INFO: common: yaml file: config\config.yaml loaded successfully]
[2024-06-27 19:20:35,594: INFO: common: yaml file: params.yaml loaded successfully]
[2024-06-27 19:20:35,596: INFO: common: created directory at: artifacts]
[2024-06-27 19:26:29,998: INFO: common: json file saved at: scores.json]
[2024-06-27 19:26:29,998: INFO: common: json file saved at: scores.json]
[2024-06-27 19:26:31,843: WARNING: save: Found untraced functions such as _jit_compiled_convolution_op, _jit_compiled_convolution_op, _jit_compiled_convolution_op, _jit_compiled_convolution_op, _jit_compiled_convolution_op while saving (showing 5 of 14). These functions will not be directly callable after loading.]
[2024-06-27 19:26:32,509: INFO: builder_impl: Assets written to: C:\Users\ASUS\AppData\Local\Temp\tmpulsicrqp\model\data\model\assets]
[2024-06-27 19:26:41,331: INFO: dir_util: creating D:\Git\DeepLearning_Classification\mlruns\0\84c743e589ea48139206fb95abddcdf6\artifacts\model\data]
[2024-06-27 19:26:41,345: INFO: dir_util: creating D:\Git\DeepLearning_Classification\mlruns\0\84c743e589ea48139206fb95abddcdf6\artifacts\model\data\model]
[2024-06-27 19:26:41,345: INFO: dir_util: creating D:\Git\DeepLearning_Classification\mlruns\0\84c743e589ea48139206fb95abddcdf6\artifacts\model\data\model\assets]
[2024-06-27 19:26:41,345: INFO: dir_util: creating D:\Git\DeepLearning_Classification\mlruns\0\84c743e589ea48139206fb95abddcdf6\artifacts\model\data\model\variables]
[2024-06-27 19:26:41,429: INFO: main: >>>>>> stage Model Evaluation completed <<<<<<

x==========x]
[2024-06-27 21:30:04,244: INFO: main: >>>>>> stage Data Ingestion stage started <<<<<<]
[2024-06-27 21:30:04,244: INFO: main: >>>>>> stage Data Ingestion stage completed <<<<<<

x==========x]
[2024-06-27 21:30:04,244: INFO: main: >>>>>> stage Prepare base model started <<<<<<]
[2024-06-27 21:30:04,244: INFO: common: yaml file: config\config.yaml loaded successfully]
[2024-06-27 21:30:04,244: INFO: common: yaml file: params.yaml loaded successfully]
[2024-06-27 21:30:04,244: INFO: common: created directory at: artifacts]
[2024-06-27 21:30:04,244: INFO: common: created directory at: artifacts/prepare_base_model]
[2024-06-27 21:30:04,714: WARNING: saving_utils: Compiled the loaded model, but the compiled metrics have yet to be built. `model.compile_metrics` will be empty until you train or evaluate the model.]
[2024-06-27 21:30:04,979: INFO: main: >>>>>> stage Prepare base model completed <<<<<<

x==========x]
[2024-06-27 21:30:04,980: INFO: main: >>>>>> stage Model training started <<<<<<]
[2024-06-27 21:30:04,982: INFO: common: yaml file: config\config.yaml loaded successfully]
[2024-06-27 21:30:04,984: INFO: common: yaml file: params.yaml loaded successfully]
[2024-06-27 21:30:04,984: INFO: common: created directory at: artifacts]
[2024-06-27 21:30:04,985: INFO: common: created directory at: artifacts\training]
[2024-06-27 21:49:02,804: INFO: main: >>>>>> stage Model training completed <<<<<<

x==========x]
[2024-06-27 21:49:02,804: INFO: main: *******************]
[2024-06-27 21:49:02,804: INFO: main: >>>>>> stage Model Evaluation started <<<<<<]
[2024-06-27 21:49:02,804: INFO: common: yaml file: config\config.yaml loaded successfully]
[2024-06-27 21:49:02,804: INFO: common: yaml file: params.yaml loaded successfully]
[2024-06-27 21:49:02,804: INFO: common: created directory at: artifacts]
[2024-06-27 21:54:41,941: INFO: common: json file saved at: scores.json]
[2024-06-27 21:54:41,941: INFO: common: json file saved at: scores.json]
[2024-06-27 21:54:43,926: INFO: helpers: Initialized MLflow to track repo "delphineasir/DeepLearning_Classification"]
[2024-06-27 21:54:43,926: INFO: helpers: Repository delphineasir/DeepLearning_Classification initialized!]
[2024-06-27 21:54:44,657: ERROR: main: INVALID_PARAMETER_VALUE: Response: {'error_code': 'INVALID_PARAMETER_VALUE'}]
Traceback (most recent call last):
  File "main.py", line 48, in <module>
    obj.main()
  File "d:\git\deeplearning_classification\src\cnnClassifier\pipeline\stage_04_model_evaluation.py", line 21, in main
    evaluation.log_into_mlflow()
  File "d:\git\deeplearning_classification\src\cnnClassifier\components\model_evaluation_mlflow.py", line 63, in log_into_mlflow
    with mlflow.start_run():
  File "C:\Users\ASUS\anaconda3\envs\kidney\lib\site-packages\mlflow\tracking\fluent.py", line 350, in start_run
    active_run_obj = client.create_run(
  File "C:\Users\ASUS\anaconda3\envs\kidney\lib\site-packages\mlflow\tracking\client.py", line 275, in create_run
    return self._tracking_client.create_run(experiment_id, start_time, tags, run_name)
  File "C:\Users\ASUS\anaconda3\envs\kidney\lib\site-packages\mlflow\tracking\_tracking_service\client.py", line 131, in create_run
    return self.store.create_run(
  File "C:\Users\ASUS\anaconda3\envs\kidney\lib\site-packages\mlflow\store\tracking\rest_store.py", line 175, in create_run
    response_proto = self._call_endpoint(CreateRun, req_body)
  File "C:\Users\ASUS\anaconda3\envs\kidney\lib\site-packages\mlflow\store\tracking\rest_store.py", line 56, in _call_endpoint
    return call_endpoint(self.get_host_creds(), endpoint, method, json_body, response_proto)
  File "C:\Users\ASUS\anaconda3\envs\kidney\lib\site-packages\mlflow\utils\rest_utils.py", line 281, in call_endpoint
    response = verify_rest_response(response, endpoint)
  File "C:\Users\ASUS\anaconda3\envs\kidney\lib\site-packages\mlflow\utils\rest_utils.py", line 207, in verify_rest_response
    raise RestException(json.loads(response.text))
mlflow.exceptions.RestException: INVALID_PARAMETER_VALUE: Response: {'error_code': 'INVALID_PARAMETER_VALUE'}
