[2024-06-14 22:09:02,727: INFO: main: welcome]
[2024-06-17 00:01:45,736: INFO: main: welcome]
[2024-06-24 10:42:56,790: INFO: main: welcome]
[2024-06-24 12:19:26,990: INFO: main: >>>>>> stage Data Ingestion stage started <<<<<<]
[2024-06-24 12:19:26,990: INFO: common: yaml file: config\config.yaml loaded successfully]
[2024-06-24 12:19:27,006: INFO: common: yaml file: params.yaml loaded successfully]
[2024-06-24 12:19:27,006: INFO: common: created directory at: artifacts]
[2024-06-24 12:19:27,013: INFO: common: created directory at: artifacts/data_ingestion]
[2024-06-24 12:19:27,014: INFO: data_ingestion: Downloading data from https://drive.google.com/file/d/1OEpd0JqL1RE6IryAtUSLmY_M2MBXg_1g/view?usp=drive_link into file artifacts/data_ingestion/data.zip]
[2024-06-24 12:21:36,286: INFO: data_ingestion: Downloaded data from https://drive.google.com/file/d/1OEpd0JqL1RE6IryAtUSLmY_M2MBXg_1g/view?usp=drive_link into file artifacts/data_ingestion/data.zip]
[2024-06-24 12:21:45,543: INFO: main: >>>>>> stage Data Ingestion stage completed <<<<<<

x==========x]
[2024-06-24 15:51:59,334: INFO: common: yaml file: config\config.yaml loaded successfully]
[2024-06-24 15:51:59,351: INFO: common: yaml file: params.yaml loaded successfully]
[2024-06-24 15:51:59,353: INFO: common: created directory at: artifacts]
[2024-06-24 15:51:59,354: INFO: common: created directory at: artifacts/prepare_base_model]
[2024-06-24 15:52:11,130: WARNING: saving_utils: Compiled the loaded model, but the compiled metrics have yet to be built. `model.compile_metrics` will be empty until you train or evaluate the model.]
[2024-06-24 16:14:45,808: INFO: main: >>>>>> stage Data Ingestion stage started <<<<<<]
[2024-06-24 16:14:45,808: INFO: common: yaml file: config\config.yaml loaded successfully]
[2024-06-24 16:14:45,808: INFO: common: yaml file: params.yaml loaded successfully]
[2024-06-24 16:14:45,808: INFO: common: created directory at: artifacts]
[2024-06-24 16:14:45,808: INFO: common: created directory at: artifacts/data_ingestion]
[2024-06-24 16:14:45,808: INFO: data_ingestion: Downloading data from https://drive.google.com/file/d/1OEpd0JqL1RE6IryAtUSLmY_M2MBXg_1g/view?usp=drive_link into file artifacts/data_ingestion/data.zip]
[2024-06-24 16:17:01,149: INFO: data_ingestion: Downloaded data from https://drive.google.com/file/d/1OEpd0JqL1RE6IryAtUSLmY_M2MBXg_1g/view?usp=drive_link into file artifacts/data_ingestion/data.zip]
[2024-06-24 16:17:09,983: INFO: main: >>>>>> stage Data Ingestion stage completed <<<<<<

x==========x]
[2024-06-24 16:17:09,983: INFO: main: >>>>>> stage Data Ingestion stage started <<<<<<]
[2024-06-24 16:17:09,983: INFO: common: yaml file: config\config.yaml loaded successfully]
[2024-06-24 16:17:09,983: INFO: common: yaml file: params.yaml loaded successfully]
[2024-06-24 16:17:09,983: INFO: common: created directory at: artifacts]
[2024-06-24 16:17:09,983: INFO: common: created directory at: artifacts/prepare_base_model]
[2024-06-24 16:17:10,627: WARNING: saving_utils: Compiled the loaded model, but the compiled metrics have yet to be built. `model.compile_metrics` will be empty until you train or evaluate the model.]
[2024-06-24 16:17:10,912: INFO: main: >>>>>> stage Data Ingestion stage completed <<<<<<

x==========x]
[2024-06-24 18:33:52,503: INFO: main: >>>>>> stage Data Ingestion stage started <<<<<<]
[2024-06-24 18:33:52,503: INFO: common: yaml file: config\config.yaml loaded successfully]
[2024-06-24 18:33:52,503: INFO: common: yaml file: params.yaml loaded successfully]
[2024-06-24 18:33:52,503: INFO: common: created directory at: artifacts]
[2024-06-24 18:33:52,518: INFO: common: created directory at: artifacts/data_ingestion]
[2024-06-24 18:33:52,518: INFO: data_ingestion: Downloading data from https://drive.google.com/file/d/1OEpd0JqL1RE6IryAtUSLmY_M2MBXg_1g/view?usp=drive_link into file artifacts/data_ingestion/data.zip]
[2024-06-24 18:37:12,484: INFO: main: >>>>>> stage Data Ingestion stage started <<<<<<]
[2024-06-24 18:37:12,501: INFO: common: yaml file: config\config.yaml loaded successfully]
[2024-06-24 18:37:12,501: INFO: common: yaml file: params.yaml loaded successfully]
[2024-06-24 18:37:12,501: INFO: common: created directory at: artifacts]
[2024-06-24 18:37:12,501: INFO: common: created directory at: artifacts/data_ingestion]
[2024-06-24 18:37:12,501: INFO: data_ingestion: Downloading data from https://drive.google.com/file/d/1OEpd0JqL1RE6IryAtUSLmY_M2MBXg_1g/view?usp=drive_link into file artifacts/data_ingestion/data.zip]
[2024-06-24 18:39:30,426: INFO: data_ingestion: Downloaded data from https://drive.google.com/file/d/1OEpd0JqL1RE6IryAtUSLmY_M2MBXg_1g/view?usp=drive_link into file artifacts/data_ingestion/data.zip]
[2024-06-24 18:39:38,887: INFO: main: >>>>>> stage Data Ingestion stage completed <<<<<<

x==========x]
[2024-06-24 18:39:38,887: INFO: main: >>>>>> stage Prepare base model started <<<<<<]
[2024-06-24 18:39:38,887: INFO: common: yaml file: config\config.yaml loaded successfully]
[2024-06-24 18:39:38,887: INFO: common: yaml file: params.yaml loaded successfully]
[2024-06-24 18:39:38,887: INFO: common: created directory at: artifacts]
[2024-06-24 18:39:38,887: INFO: common: created directory at: artifacts/prepare_base_model]
[2024-06-24 18:39:39,491: WARNING: saving_utils: Compiled the loaded model, but the compiled metrics have yet to be built. `model.compile_metrics` will be empty until you train or evaluate the model.]
[2024-06-24 18:39:39,765: INFO: main: >>>>>> stage Prepare base model completed <<<<<<

x==========x]
[2024-06-24 18:39:39,766: INFO: main: >>>>>> stage Model training started <<<<<<]
[2024-06-24 18:39:39,769: INFO: common: yaml file: config\config.yaml loaded successfully]
[2024-06-24 18:39:39,771: INFO: common: yaml file: params.yaml loaded successfully]
[2024-06-24 18:39:39,771: INFO: common: created directory at: artifacts]
[2024-06-24 18:39:39,772: INFO: common: created directory at: artifacts\training]
[2024-06-24 18:39:40,190: ERROR: main: [WinError 3] The system cannot find the path specified: 'artifacts\\data_ingestion\\kidney-ct-scan-image']
Traceback (most recent call last):
  File "main.py", line 36, in <module>
    train.main()
  File "d:\git\deeplearning_classification\src\cnnClassifier\pipeline\stage_03_model_training.py", line 18, in main
    training.train_valid_generator()
  File "d:\git\deeplearning_classification\src\cnnClassifier\components\model_training.py", line 37, in train_valid_generator
    self.valid_generator = valid_datagenerator.flow_from_directory(
  File "C:\Users\ASUS\anaconda3\envs\kidney\lib\site-packages\keras\preprocessing\image.py", line 1648, in flow_from_directory
    return DirectoryIterator(
  File "C:\Users\ASUS\anaconda3\envs\kidney\lib\site-packages\keras\preprocessing\image.py", line 563, in __init__
    for subdir in sorted(os.listdir(directory)):
FileNotFoundError: [WinError 3] The system cannot find the path specified: 'artifacts\\data_ingestion\\kidney-ct-scan-image'
[2024-06-24 19:00:13,218: INFO: main: >>>>>> stage Data Ingestion stage started <<<<<<]
[2024-06-24 19:00:13,233: INFO: common: yaml file: config\config.yaml loaded successfully]
[2024-06-24 19:00:13,244: INFO: common: yaml file: params.yaml loaded successfully]
[2024-06-24 19:00:13,245: INFO: common: created directory at: artifacts]
[2024-06-24 19:00:13,246: INFO: common: created directory at: artifacts/data_ingestion]
[2024-06-24 19:00:13,246: INFO: data_ingestion: Downloading data from https://drive.google.com/file/d/1OEpd0JqL1RE6IryAtUSLmY_M2MBXg_1g/view?usp=drive_link into file artifacts/data_ingestion/data.zip]
[2024-06-24 19:01:42,960: INFO: main: >>>>>> stage Data Ingestion stage started <<<<<<]
[2024-06-24 19:01:42,963: INFO: common: yaml file: config\config.yaml loaded successfully]
[2024-06-24 19:01:42,965: INFO: common: yaml file: params.yaml loaded successfully]
[2024-06-24 19:01:42,965: INFO: common: created directory at: artifacts]
[2024-06-24 19:01:42,966: INFO: common: created directory at: artifacts/data_ingestion]
[2024-06-24 19:01:42,967: INFO: data_ingestion: Downloading data from https://drive.google.com/file/d/1OEpd0JqL1RE6IryAtUSLmY_M2MBXg_1g/view?usp=drive_link into file artifacts/data_ingestion/data.zip]
[2024-06-24 19:04:02,511: INFO: data_ingestion: Downloaded data from https://drive.google.com/file/d/1OEpd0JqL1RE6IryAtUSLmY_M2MBXg_1g/view?usp=drive_link into file artifacts/data_ingestion/data.zip]
[2024-06-24 19:04:11,230: INFO: main: >>>>>> stage Data Ingestion stage completed <<<<<<

x==========x]
[2024-06-24 19:04:11,230: INFO: main: >>>>>> stage Prepare base model started <<<<<<]
[2024-06-24 19:04:11,246: INFO: common: yaml file: config\config.yaml loaded successfully]
[2024-06-24 19:04:11,246: INFO: common: yaml file: params.yaml loaded successfully]
[2024-06-24 19:04:11,246: INFO: common: created directory at: artifacts]
[2024-06-24 19:04:11,254: INFO: common: created directory at: artifacts/prepare_base_model]
[2024-06-24 19:04:11,998: WARNING: saving_utils: Compiled the loaded model, but the compiled metrics have yet to be built. `model.compile_metrics` will be empty until you train or evaluate the model.]
[2024-06-24 19:04:12,276: INFO: main: >>>>>> stage Prepare base model completed <<<<<<

x==========x]
[2024-06-24 19:04:12,277: INFO: main: >>>>>> stage Model training started <<<<<<]
[2024-06-24 19:04:12,280: INFO: common: yaml file: config\config.yaml loaded successfully]
[2024-06-24 19:04:12,280: INFO: common: yaml file: params.yaml loaded successfully]
[2024-06-24 19:04:12,280: INFO: common: created directory at: artifacts]
[2024-06-24 19:04:12,284: INFO: common: created directory at: artifacts\training]
[2024-06-24 19:04:12,768: ERROR: main: [WinError 3] The system cannot find the path specified: 'artifacts\\data_ingestion\\ct-scan-image\\ct-scan-image']
Traceback (most recent call last):
  File "main.py", line 36, in <module>
    train.main()
  File "d:\git\deeplearning_classification\src\cnnClassifier\pipeline\stage_03_model_training.py", line 18, in main
    training.train_valid_generator()
  File "d:\git\deeplearning_classification\src\cnnClassifier\components\model_training.py", line 37, in train_valid_generator
    self.valid_generator = valid_datagenerator.flow_from_directory(
  File "C:\Users\ASUS\anaconda3\envs\kidney\lib\site-packages\keras\preprocessing\image.py", line 1648, in flow_from_directory
    return DirectoryIterator(
  File "C:\Users\ASUS\anaconda3\envs\kidney\lib\site-packages\keras\preprocessing\image.py", line 563, in __init__
    for subdir in sorted(os.listdir(directory)):
FileNotFoundError: [WinError 3] The system cannot find the path specified: 'artifacts\\data_ingestion\\ct-scan-image\\ct-scan-image'
[2024-06-24 19:09:34,538: INFO: main: >>>>>> stage Data Ingestion stage started <<<<<<]
[2024-06-24 19:09:34,538: INFO: main: >>>>>> stage Data Ingestion stage completed <<<<<<

x==========x]
[2024-06-24 19:09:34,538: INFO: main: >>>>>> stage Prepare base model started <<<<<<]
[2024-06-24 19:09:34,538: INFO: common: yaml file: config\config.yaml loaded successfully]
[2024-06-24 19:09:34,538: INFO: common: yaml file: params.yaml loaded successfully]
[2024-06-24 19:09:34,538: INFO: common: created directory at: artifacts]
[2024-06-24 19:09:34,538: INFO: common: created directory at: artifacts/prepare_base_model]
[2024-06-24 19:09:35,021: WARNING: saving_utils: Compiled the loaded model, but the compiled metrics have yet to be built. `model.compile_metrics` will be empty until you train or evaluate the model.]
[2024-06-24 19:09:35,252: INFO: main: >>>>>> stage Prepare base model completed <<<<<<

x==========x]
[2024-06-24 19:09:35,252: INFO: main: >>>>>> stage Model training started <<<<<<]
[2024-06-24 19:09:35,255: INFO: common: yaml file: config\config.yaml loaded successfully]
[2024-06-24 19:09:35,257: INFO: common: yaml file: params.yaml loaded successfully]
[2024-06-24 19:09:35,257: INFO: common: created directory at: artifacts]
[2024-06-24 19:09:35,258: INFO: common: created directory at: artifacts\training]
[2024-06-24 19:09:35,609: ERROR: main: [WinError 3] The system cannot find the path specified: 'artifacts\\data_ingestion\\ct-scan-image\\ct-scan-image']
Traceback (most recent call last):
  File "main.py", line 36, in <module>
    train.main()
  File "d:\git\deeplearning_classification\src\cnnClassifier\pipeline\stage_03_model_training.py", line 18, in main
    training.train_valid_generator()
  File "d:\git\deeplearning_classification\src\cnnClassifier\components\model_training.py", line 37, in train_valid_generator
    self.valid_generator = valid_datagenerator.flow_from_directory(
  File "C:\Users\ASUS\anaconda3\envs\kidney\lib\site-packages\keras\preprocessing\image.py", line 1648, in flow_from_directory
    return DirectoryIterator(
  File "C:\Users\ASUS\anaconda3\envs\kidney\lib\site-packages\keras\preprocessing\image.py", line 563, in __init__
    for subdir in sorted(os.listdir(directory)):
FileNotFoundError: [WinError 3] The system cannot find the path specified: 'artifacts\\data_ingestion\\ct-scan-image\\ct-scan-image'
[2024-06-24 19:14:03,088: INFO: main: >>>>>> stage Data Ingestion stage started <<<<<<]
[2024-06-24 19:14:03,088: INFO: common: yaml file: config\config.yaml loaded successfully]
[2024-06-24 19:14:03,088: INFO: common: yaml file: params.yaml loaded successfully]
[2024-06-24 19:14:03,088: INFO: common: created directory at: artifacts]
[2024-06-24 19:14:03,088: INFO: common: created directory at: artifacts/data_ingestion]
[2024-06-24 19:14:03,104: INFO: data_ingestion: Downloading data from https://drive.google.com/file/d/1OEpd0JqL1RE6IryAtUSLmY_M2MBXg_1g/view?usp=drive_link into file artifacts/data_ingestion/data.zip]
[2024-06-24 19:16:30,860: INFO: data_ingestion: Downloaded data from https://drive.google.com/file/d/1OEpd0JqL1RE6IryAtUSLmY_M2MBXg_1g/view?usp=drive_link into file artifacts/data_ingestion/data.zip]
[2024-06-24 19:16:39,315: INFO: main: >>>>>> stage Data Ingestion stage completed <<<<<<

x==========x]
[2024-06-24 19:16:39,316: INFO: main: >>>>>> stage Prepare base model started <<<<<<]
[2024-06-24 19:16:39,318: INFO: common: yaml file: config\config.yaml loaded successfully]
[2024-06-24 19:16:39,320: INFO: common: yaml file: params.yaml loaded successfully]
[2024-06-24 19:16:39,321: INFO: common: created directory at: artifacts]
[2024-06-24 19:16:39,321: INFO: common: created directory at: artifacts/prepare_base_model]
[2024-06-24 19:16:39,992: WARNING: saving_utils: Compiled the loaded model, but the compiled metrics have yet to be built. `model.compile_metrics` will be empty until you train or evaluate the model.]
[2024-06-24 19:16:40,250: INFO: main: >>>>>> stage Prepare base model completed <<<<<<

x==========x]
[2024-06-24 19:16:40,250: INFO: main: >>>>>> stage Model training started <<<<<<]
[2024-06-24 19:16:40,253: INFO: common: yaml file: config\config.yaml loaded successfully]
[2024-06-24 19:16:40,255: INFO: common: yaml file: params.yaml loaded successfully]
[2024-06-24 19:16:40,255: INFO: common: created directory at: artifacts]
[2024-06-24 19:16:40,256: INFO: common: created directory at: artifacts\training]
[2024-06-24 19:16:40,793: ERROR: main: [WinError 3] The system cannot find the path specified: 'artifacts\\data_ingestion\\ct-scan-image\\ct-scan-image']
Traceback (most recent call last):
  File "main.py", line 36, in <module>
    train.main()
  File "d:\git\deeplearning_classification\src\cnnClassifier\pipeline\stage_03_model_training.py", line 18, in main
    training.train_valid_generator()
  File "d:\git\deeplearning_classification\src\cnnClassifier\components\model_training.py", line 37, in train_valid_generator
    self.valid_generator = valid_datagenerator.flow_from_directory(
  File "C:\Users\ASUS\anaconda3\envs\kidney\lib\site-packages\keras\preprocessing\image.py", line 1648, in flow_from_directory
    return DirectoryIterator(
  File "C:\Users\ASUS\anaconda3\envs\kidney\lib\site-packages\keras\preprocessing\image.py", line 563, in __init__
    for subdir in sorted(os.listdir(directory)):
FileNotFoundError: [WinError 3] The system cannot find the path specified: 'artifacts\\data_ingestion\\ct-scan-image\\ct-scan-image'
[2024-06-24 19:30:17,602: INFO: main: >>>>>> stage Data Ingestion stage started <<<<<<]
[2024-06-24 19:30:17,602: INFO: common: yaml file: config\config.yaml loaded successfully]
[2024-06-24 19:30:17,614: INFO: common: yaml file: params.yaml loaded successfully]
[2024-06-24 19:30:17,615: INFO: common: created directory at: artifacts]
[2024-06-24 19:30:17,616: INFO: common: created directory at: artifacts/data_ingestion]
[2024-06-24 19:30:17,616: INFO: data_ingestion: Downloading data from https://drive.google.com/file/d/1OEpd0JqL1RE6IryAtUSLmY_M2MBXg_1g/view?usp=drive_link into file artifacts/data_ingestion/data.zip]
[2024-06-24 19:32:36,281: INFO: data_ingestion: Downloaded data from https://drive.google.com/file/d/1OEpd0JqL1RE6IryAtUSLmY_M2MBXg_1g/view?usp=drive_link into file artifacts/data_ingestion/data.zip]
[2024-06-24 19:32:44,354: INFO: main: >>>>>> stage Data Ingestion stage completed <<<<<<

x==========x]
[2024-06-24 19:32:44,354: INFO: main: >>>>>> stage Prepare base model started <<<<<<]
[2024-06-24 19:32:44,354: INFO: common: yaml file: config\config.yaml loaded successfully]
[2024-06-24 19:32:44,367: INFO: common: yaml file: params.yaml loaded successfully]
[2024-06-24 19:32:44,368: INFO: common: created directory at: artifacts]
[2024-06-24 19:32:44,370: INFO: common: created directory at: artifacts/prepare_base_model]
[2024-06-24 19:32:45,012: WARNING: saving_utils: Compiled the loaded model, but the compiled metrics have yet to be built. `model.compile_metrics` will be empty until you train or evaluate the model.]
[2024-06-24 19:32:45,260: INFO: main: >>>>>> stage Prepare base model completed <<<<<<

x==========x]
[2024-06-24 19:32:45,261: INFO: main: >>>>>> stage Model training started <<<<<<]
[2024-06-24 19:32:45,267: INFO: common: yaml file: config\config.yaml loaded successfully]
[2024-06-24 19:32:45,269: INFO: common: yaml file: params.yaml loaded successfully]
[2024-06-24 19:32:45,270: INFO: common: created directory at: artifacts]
[2024-06-24 19:32:45,270: INFO: common: created directory at: artifacts\training]
[2024-06-24 19:32:45,730: ERROR: main: [WinError 3] The system cannot find the path specified: 'artifacts\\data_ingestion\\kidney-ct-scan-image']
Traceback (most recent call last):
  File "main.py", line 36, in <module>
    train.main()
  File "d:\git\deeplearning_classification\src\cnnClassifier\pipeline\stage_03_model_training.py", line 20, in main
    training.train_valid_generator()
  File "d:\git\deeplearning_classification\src\cnnClassifier\components\model_training.py", line 37, in train_valid_generator
    self.valid_generator = valid_datagenerator.flow_from_directory(
  File "C:\Users\ASUS\anaconda3\envs\kidney\lib\site-packages\keras\preprocessing\image.py", line 1648, in flow_from_directory
    return DirectoryIterator(
  File "C:\Users\ASUS\anaconda3\envs\kidney\lib\site-packages\keras\preprocessing\image.py", line 563, in __init__
    for subdir in sorted(os.listdir(directory)):
FileNotFoundError: [WinError 3] The system cannot find the path specified: 'artifacts\\data_ingestion\\kidney-ct-scan-image'
[2024-06-24 19:43:10,002: INFO: common: yaml file: config\config.yaml loaded successfully]
[2024-06-24 19:43:10,008: INFO: common: yaml file: params.yaml loaded successfully]
[2024-06-24 19:43:10,011: INFO: common: created directory at: artifacts]
[2024-06-24 19:43:10,013: INFO: common: created directory at: artifacts\training]
[2024-06-24 22:54:56,080: INFO: main: >>>>>> stage Data Ingestion stage started <<<<<<]
[2024-06-24 22:54:56,095: INFO: common: yaml file: config\config.yaml loaded successfully]
[2024-06-24 22:54:56,095: INFO: common: yaml file: params.yaml loaded successfully]
[2024-06-24 22:54:56,102: INFO: common: created directory at: artifacts]
[2024-06-24 22:54:56,102: INFO: common: created directory at: artifacts/data_ingestion]
[2024-06-24 22:54:56,103: INFO: data_ingestion: Downloading data from https://drive.google.com/file/d/1OEpd0JqL1RE6IryAtUSLmY_M2MBXg_1g/view?usp=drive_link into file artifacts/data_ingestion/data.zip]
[2024-06-24 22:57:13,201: INFO: data_ingestion: Downloaded data from https://drive.google.com/file/d/1OEpd0JqL1RE6IryAtUSLmY_M2MBXg_1g/view?usp=drive_link into file artifacts/data_ingestion/data.zip]
[2024-06-24 22:57:24,040: INFO: main: >>>>>> stage Data Ingestion stage completed <<<<<<

x==========x]
[2024-06-24 22:57:24,040: INFO: main: >>>>>> stage Prepare base model started <<<<<<]
[2024-06-24 22:57:24,040: INFO: common: yaml file: config\config.yaml loaded successfully]
[2024-06-24 22:57:24,040: INFO: common: yaml file: params.yaml loaded successfully]
[2024-06-24 22:57:24,040: INFO: common: created directory at: artifacts]
[2024-06-24 22:57:24,054: INFO: common: created directory at: artifacts/prepare_base_model]
[2024-06-24 22:57:24,710: WARNING: saving_utils: Compiled the loaded model, but the compiled metrics have yet to be built. `model.compile_metrics` will be empty until you train or evaluate the model.]
[2024-06-24 22:57:25,118: INFO: main: >>>>>> stage Prepare base model completed <<<<<<

x==========x]
[2024-06-24 22:57:25,120: INFO: main: >>>>>> stage Model training started <<<<<<]
[2024-06-24 22:57:25,130: INFO: common: yaml file: config\config.yaml loaded successfully]
[2024-06-24 22:57:25,136: INFO: common: yaml file: params.yaml loaded successfully]
[2024-06-24 22:57:25,136: INFO: common: created directory at: artifacts]
[2024-06-24 22:57:25,139: INFO: common: created directory at: artifacts\training]
[2024-06-24 22:57:25,820: ERROR: main: [WinError 3] The system cannot find the path specified: 'artifacts\\data_ingestion\\kidney-ct-scan-image']
Traceback (most recent call last):
  File "main.py", line 36, in <module>
    train.main()
  File "d:\git\deeplearning_classification\src\cnnClassifier\pipeline\stage_03_model_training.py", line 20, in main
    training.train_valid_generator()
  File "d:\git\deeplearning_classification\src\cnnClassifier\components\model_training.py", line 37, in train_valid_generator
    self.valid_generator = valid_datagenerator.flow_from_directory(
  File "C:\Users\ASUS\anaconda3\envs\kidney\lib\site-packages\keras\preprocessing\image.py", line 1648, in flow_from_directory
    return DirectoryIterator(
  File "C:\Users\ASUS\anaconda3\envs\kidney\lib\site-packages\keras\preprocessing\image.py", line 563, in __init__
    for subdir in sorted(os.listdir(directory)):
FileNotFoundError: [WinError 3] The system cannot find the path specified: 'artifacts\\data_ingestion\\kidney-ct-scan-image'
[2024-06-24 22:58:37,139: INFO: main: >>>>>> stage Data Ingestion stage started <<<<<<]
[2024-06-24 22:58:37,139: INFO: main: >>>>>> stage Data Ingestion stage completed <<<<<<

x==========x]
[2024-06-24 22:58:37,139: INFO: main: >>>>>> stage Prepare base model started <<<<<<]
[2024-06-24 22:58:37,155: INFO: common: yaml file: config\config.yaml loaded successfully]
[2024-06-24 22:58:37,168: INFO: common: yaml file: params.yaml loaded successfully]
[2024-06-24 22:58:37,171: INFO: common: created directory at: artifacts]
[2024-06-24 22:58:37,172: INFO: common: created directory at: artifacts/prepare_base_model]
[2024-06-24 22:58:37,938: WARNING: saving_utils: Compiled the loaded model, but the compiled metrics have yet to be built. `model.compile_metrics` will be empty until you train or evaluate the model.]
[2024-06-24 22:58:38,249: INFO: main: >>>>>> stage Prepare base model completed <<<<<<

x==========x]
[2024-06-24 22:58:38,250: INFO: main: >>>>>> stage Model training started <<<<<<]
[2024-06-24 22:58:38,256: INFO: common: yaml file: config\config.yaml loaded successfully]
[2024-06-24 22:58:38,260: INFO: common: yaml file: params.yaml loaded successfully]
[2024-06-24 22:58:38,261: INFO: common: created directory at: artifacts]
[2024-06-24 22:58:38,261: INFO: common: created directory at: artifacts\training]
[2024-06-24 22:58:38,792: ERROR: main: [WinError 3] The system cannot find the path specified: 'artifacts\\data_ingestion\\kidney-ct-scan-image']
Traceback (most recent call last):
  File "d:\Git\DeepLearning_Classification\main.py", line 36, in <module>
    train.main()
  File "d:\git\deeplearning_classification\src\cnnClassifier\pipeline\stage_03_model_training.py", line 20, in main
    training.train_valid_generator()
  File "d:\git\deeplearning_classification\src\cnnClassifier\components\model_training.py", line 37, in train_valid_generator
    self.valid_generator = valid_datagenerator.flow_from_directory(
  File "c:\Users\ASUS\AppData\Local\Programs\Python\Python310\lib\site-packages\keras\preprocessing\image.py", line 1648, in flow_from_directory
    return DirectoryIterator(
  File "c:\Users\ASUS\AppData\Local\Programs\Python\Python310\lib\site-packages\keras\preprocessing\image.py", line 563, in __init__
    for subdir in sorted(os.listdir(directory)):
FileNotFoundError: [WinError 3] The system cannot find the path specified: 'artifacts\\data_ingestion\\kidney-ct-scan-image'
[2024-06-25 00:16:54,154: INFO: common: yaml file: config\config.yaml loaded successfully]
[2024-06-25 00:16:54,170: INFO: common: yaml file: params.yaml loaded successfully]
[2024-06-25 00:16:54,172: INFO: common: created directory at: artifacts]
[2024-06-25 00:16:54,174: INFO: common: created directory at: artifacts\training]
[2024-06-25 00:19:04,203: INFO: main: >>>>>> stage Data Ingestion stage started <<<<<<]
[2024-06-25 00:19:04,203: INFO: main: >>>>>> stage Data Ingestion stage completed <<<<<<

x==========x]
[2024-06-25 00:19:04,219: INFO: main: >>>>>> stage Prepare base model started <<<<<<]
[2024-06-25 00:19:04,219: INFO: common: yaml file: config\config.yaml loaded successfully]
[2024-06-25 00:19:04,228: INFO: common: yaml file: params.yaml loaded successfully]
[2024-06-25 00:19:04,230: INFO: common: created directory at: artifacts]
[2024-06-25 00:19:04,230: INFO: common: created directory at: artifacts/prepare_base_model]
[2024-06-25 00:19:04,679: WARNING: saving_utils: Compiled the loaded model, but the compiled metrics have yet to be built. `model.compile_metrics` will be empty until you train or evaluate the model.]
[2024-06-25 00:19:04,902: INFO: main: >>>>>> stage Prepare base model completed <<<<<<

x==========x]
[2024-06-25 00:19:04,903: INFO: main: >>>>>> stage Model training started <<<<<<]
[2024-06-25 00:19:04,905: INFO: common: yaml file: config\config.yaml loaded successfully]
[2024-06-25 00:19:04,907: INFO: common: yaml file: params.yaml loaded successfully]
[2024-06-25 00:19:04,908: INFO: common: created directory at: artifacts]
[2024-06-25 00:19:04,908: INFO: common: created directory at: artifacts\training]
[2024-06-25 00:19:05,289: ERROR: main: [WinError 3] The system cannot find the path specified: 'artifacts\\data_ingestion\\ct-scan-image\\kidney-ct-scan-image']
Traceback (most recent call last):
  File "main.py", line 36, in <module>
    train.main()
  File "d:\git\deeplearning_classification\src\cnnClassifier\pipeline\stage_03_model_training.py", line 20, in main
    training.train_valid_generator()
  File "d:\git\deeplearning_classification\src\cnnClassifier\components\model_training.py", line 37, in train_valid_generator
    self.valid_generator = valid_datagenerator.flow_from_directory(
  File "C:\Users\ASUS\anaconda3\envs\kidney\lib\site-packages\keras\preprocessing\image.py", line 1648, in flow_from_directory
    return DirectoryIterator(
  File "C:\Users\ASUS\anaconda3\envs\kidney\lib\site-packages\keras\preprocessing\image.py", line 563, in __init__
    for subdir in sorted(os.listdir(directory)):
FileNotFoundError: [WinError 3] The system cannot find the path specified: 'artifacts\\data_ingestion\\ct-scan-image\\kidney-ct-scan-image'
[2024-06-25 12:14:05,114: INFO: main: >>>>>> stage Data Ingestion stage started <<<<<<]
[2024-06-25 12:14:05,114: INFO: main: >>>>>> stage Data Ingestion stage completed <<<<<<

x==========x]
[2024-06-25 12:14:05,114: INFO: main: >>>>>> stage Prepare base model started <<<<<<]
[2024-06-25 12:14:05,114: INFO: common: yaml file: config\config.yaml loaded successfully]
[2024-06-25 12:14:05,114: INFO: common: yaml file: params.yaml loaded successfully]
[2024-06-25 12:14:05,130: INFO: common: created directory at: artifacts]
[2024-06-25 12:14:05,130: INFO: common: created directory at: artifacts/prepare_base_model]
[2024-06-25 12:14:05,799: WARNING: saving_utils: Compiled the loaded model, but the compiled metrics have yet to be built. `model.compile_metrics` will be empty until you train or evaluate the model.]
[2024-06-25 12:14:06,033: INFO: main: >>>>>> stage Prepare base model completed <<<<<<

x==========x]
[2024-06-25 12:14:06,033: INFO: main: >>>>>> stage Model training started <<<<<<]
[2024-06-25 12:14:06,033: INFO: common: yaml file: config\config.yaml loaded successfully]
[2024-06-25 12:14:06,048: INFO: common: yaml file: params.yaml loaded successfully]
[2024-06-25 12:14:06,049: INFO: common: created directory at: artifacts]
[2024-06-25 12:14:06,049: INFO: common: created directory at: artifacts\training]
[2024-06-25 12:14:06,417: ERROR: main: [WinError 3] The system cannot find the path specified: 'artifacts\\data_ingestion\\ct-scan-image\\CT_SCAN']
Traceback (most recent call last):
  File "main.py", line 36, in <module>
    train.main()
  File "d:\git\deeplearning_classification\src\cnnClassifier\pipeline\stage_03_model_training.py", line 20, in main
    training.train_valid_generator()
  File "d:\git\deeplearning_classification\src\cnnClassifier\components\model_training.py", line 37, in train_valid_generator
    self.valid_generator = valid_datagenerator.flow_from_directory(
  File "C:\Users\ASUS\anaconda3\envs\kidney\lib\site-packages\keras\preprocessing\image.py", line 1648, in flow_from_directory
    return DirectoryIterator(
  File "C:\Users\ASUS\anaconda3\envs\kidney\lib\site-packages\keras\preprocessing\image.py", line 563, in __init__
    for subdir in sorted(os.listdir(directory)):
FileNotFoundError: [WinError 3] The system cannot find the path specified: 'artifacts\\data_ingestion\\ct-scan-image\\CT_SCAN'
[2024-06-25 12:15:11,656: INFO: main: >>>>>> stage Data Ingestion stage started <<<<<<]
[2024-06-25 12:15:11,656: INFO: common: yaml file: config\config.yaml loaded successfully]
[2024-06-25 12:15:11,656: INFO: common: yaml file: params.yaml loaded successfully]
[2024-06-25 12:15:11,656: INFO: common: created directory at: artifacts]
[2024-06-25 12:15:11,656: INFO: common: created directory at: artifacts/data_ingestion]
[2024-06-25 12:15:11,671: INFO: data_ingestion: Downloading data from https://drive.google.com/file/d/1yLiUUVor0xmtWE830IpivUwYUKS43jfV/view?usp=drive_link into file artifacts/data_ingestion/data.zip]
[2024-06-25 12:17:15,480: INFO: data_ingestion: Downloaded data from https://drive.google.com/file/d/1yLiUUVor0xmtWE830IpivUwYUKS43jfV/view?usp=drive_link into file artifacts/data_ingestion/data.zip]
[2024-06-25 12:17:23,725: INFO: main: >>>>>> stage Data Ingestion stage completed <<<<<<

x==========x]
[2024-06-25 12:17:23,725: INFO: main: >>>>>> stage Prepare base model started <<<<<<]
[2024-06-25 12:17:23,725: INFO: common: yaml file: config\config.yaml loaded successfully]
[2024-06-25 12:17:23,725: INFO: common: yaml file: params.yaml loaded successfully]
[2024-06-25 12:17:23,725: INFO: common: created directory at: artifacts]
[2024-06-25 12:17:23,725: INFO: common: created directory at: artifacts/prepare_base_model]
[2024-06-25 12:17:24,264: WARNING: saving_utils: Compiled the loaded model, but the compiled metrics have yet to be built. `model.compile_metrics` will be empty until you train or evaluate the model.]
[2024-06-25 12:17:24,512: INFO: main: >>>>>> stage Prepare base model completed <<<<<<

x==========x]
[2024-06-25 12:17:24,513: INFO: main: >>>>>> stage Model training started <<<<<<]
[2024-06-25 12:17:24,519: INFO: common: yaml file: config\config.yaml loaded successfully]
[2024-06-25 12:17:24,521: INFO: common: yaml file: params.yaml loaded successfully]
[2024-06-25 12:17:24,522: INFO: common: created directory at: artifacts]
[2024-06-25 12:17:24,523: INFO: common: created directory at: artifacts\training]
[2024-06-25 12:17:42,420: ERROR: main: Graph execution error:

FileNotFoundError: [Errno 2] No such file or directory: 'artifacts\\data_ingestion\\CT_SCAN\\Normal\\Normal- (3011).jpg'
Traceback (most recent call last):

  File "C:\Users\ASUS\anaconda3\envs\kidney\lib\site-packages\tensorflow\python\ops\script_ops.py", line 267, in __call__
    ret = func(*args)

  File "C:\Users\ASUS\anaconda3\envs\kidney\lib\site-packages\tensorflow\python\autograph\impl\api.py", line 642, in wrapper
    return func(*args, **kwargs)

  File "C:\Users\ASUS\anaconda3\envs\kidney\lib\site-packages\tensorflow\python\data\ops\from_generator_op.py", line 198, in generator_py_func
    values = next(generator_state.get_iterator(iterator_id))

  File "C:\Users\ASUS\anaconda3\envs\kidney\lib\site-packages\keras\engine\data_adapter.py", line 902, in wrapped_generator
    for data in generator_fn():

  File "C:\Users\ASUS\anaconda3\envs\kidney\lib\site-packages\keras\engine\data_adapter.py", line 1049, in generator_fn
    yield x[i]

  File "C:\Users\ASUS\anaconda3\envs\kidney\lib\site-packages\keras\preprocessing\image.py", line 116, in __getitem__
    return self._get_batches_of_transformed_samples(index_array)

  File "C:\Users\ASUS\anaconda3\envs\kidney\lib\site-packages\keras\preprocessing\image.py", line 370, in _get_batches_of_transformed_samples
    img = image_utils.load_img(

  File "C:\Users\ASUS\anaconda3\envs\kidney\lib\site-packages\keras\utils\image_utils.py", line 422, in load_img
    with open(path, "rb") as f:

FileNotFoundError: [Errno 2] No such file or directory: 'artifacts\\data_ingestion\\CT_SCAN\\Normal\\Normal- (3011).jpg'


	 [[{{node PyFunc}}]]
	 [[IteratorGetNext]] [Op:__inference_train_function_1463]]
Traceback (most recent call last):
  File "main.py", line 36, in <module>
    train.main()
  File "d:\git\deeplearning_classification\src\cnnClassifier\pipeline\stage_03_model_training.py", line 21, in main
    training.train()
  File "d:\git\deeplearning_classification\src\cnnClassifier\components\model_training.py", line 76, in train
    self.model.fit(
  File "C:\Users\ASUS\anaconda3\envs\kidney\lib\site-packages\keras\utils\traceback_utils.py", line 70, in error_handler
    raise e.with_traceback(filtered_tb) from None
  File "C:\Users\ASUS\anaconda3\envs\kidney\lib\site-packages\tensorflow\python\eager\execute.py", line 52, in quick_execute
    tensors = pywrap_tfe.TFE_Py_Execute(ctx._handle, device_name, op_name,
tensorflow.python.framework.errors_impl.UnknownError: Graph execution error:

FileNotFoundError: [Errno 2] No such file or directory: 'artifacts\\data_ingestion\\CT_SCAN\\Normal\\Normal- (3011).jpg'
Traceback (most recent call last):

  File "C:\Users\ASUS\anaconda3\envs\kidney\lib\site-packages\tensorflow\python\ops\script_ops.py", line 267, in __call__
    ret = func(*args)

  File "C:\Users\ASUS\anaconda3\envs\kidney\lib\site-packages\tensorflow\python\autograph\impl\api.py", line 642, in wrapper
    return func(*args, **kwargs)

  File "C:\Users\ASUS\anaconda3\envs\kidney\lib\site-packages\tensorflow\python\data\ops\from_generator_op.py", line 198, in generator_py_func
    values = next(generator_state.get_iterator(iterator_id))

  File "C:\Users\ASUS\anaconda3\envs\kidney\lib\site-packages\keras\engine\data_adapter.py", line 902, in wrapped_generator
    for data in generator_fn():

  File "C:\Users\ASUS\anaconda3\envs\kidney\lib\site-packages\keras\engine\data_adapter.py", line 1049, in generator_fn
    yield x[i]

  File "C:\Users\ASUS\anaconda3\envs\kidney\lib\site-packages\keras\preprocessing\image.py", line 116, in __getitem__
    return self._get_batches_of_transformed_samples(index_array)

  File "C:\Users\ASUS\anaconda3\envs\kidney\lib\site-packages\keras\preprocessing\image.py", line 370, in _get_batches_of_transformed_samples
    img = image_utils.load_img(

  File "C:\Users\ASUS\anaconda3\envs\kidney\lib\site-packages\keras\utils\image_utils.py", line 422, in load_img
    with open(path, "rb") as f:

FileNotFoundError: [Errno 2] No such file or directory: 'artifacts\\data_ingestion\\CT_SCAN\\Normal\\Normal- (3011).jpg'


	 [[{{node PyFunc}}]]
	 [[IteratorGetNext]] [Op:__inference_train_function_1463]
[2024-06-25 12:20:40,411: INFO: main: >>>>>> stage Data Ingestion stage started <<<<<<]
[2024-06-25 12:20:40,411: INFO: common: yaml file: config\config.yaml loaded successfully]
[2024-06-25 12:20:40,411: INFO: common: yaml file: params.yaml loaded successfully]
[2024-06-25 12:20:40,411: INFO: common: created directory at: artifacts]
[2024-06-25 12:20:40,418: INFO: common: created directory at: artifacts/data_ingestion]
[2024-06-25 12:20:40,418: INFO: data_ingestion: Downloading data from https://drive.google.com/file/d/1yLiUUVor0xmtWE830IpivUwYUKS43jfV/view?usp=drive_link into file artifacts/data_ingestion/data.zip]
[2024-06-25 12:22:42,303: INFO: data_ingestion: Downloaded data from https://drive.google.com/file/d/1yLiUUVor0xmtWE830IpivUwYUKS43jfV/view?usp=drive_link into file artifacts/data_ingestion/data.zip]
[2024-06-25 12:22:50,669: INFO: main: >>>>>> stage Data Ingestion stage completed <<<<<<

x==========x]
[2024-06-25 12:22:50,669: INFO: main: >>>>>> stage Prepare base model started <<<<<<]
[2024-06-25 12:22:50,669: INFO: common: yaml file: config\config.yaml loaded successfully]
[2024-06-25 12:22:50,669: INFO: common: yaml file: params.yaml loaded successfully]
[2024-06-25 12:22:50,669: INFO: common: created directory at: artifacts]
[2024-06-25 12:22:50,685: INFO: common: created directory at: artifacts/prepare_base_model]
[2024-06-25 12:22:51,176: WARNING: saving_utils: Compiled the loaded model, but the compiled metrics have yet to be built. `model.compile_metrics` will be empty until you train or evaluate the model.]
[2024-06-25 12:22:51,439: INFO: main: >>>>>> stage Prepare base model completed <<<<<<

x==========x]
[2024-06-25 12:22:51,439: INFO: main: >>>>>> stage Model training started <<<<<<]
[2024-06-25 12:22:51,439: INFO: common: yaml file: config\config.yaml loaded successfully]
[2024-06-25 12:22:51,439: INFO: common: yaml file: params.yaml loaded successfully]
[2024-06-25 12:22:51,439: INFO: common: created directory at: artifacts]
[2024-06-25 12:22:51,453: INFO: common: created directory at: artifacts\training]
[2024-06-25 12:42:54,691: INFO: main: >>>>>> stage Model training completed <<<<<<

x==========x]
[2024-06-26 13:51:08,756: INFO: common: yaml file: config\config.yaml loaded successfully]
[2024-06-26 13:51:08,772: INFO: common: yaml file: params.yaml loaded successfully]
[2024-06-26 13:51:08,775: INFO: common: created directory at: artifacts]
[2024-06-26 15:49:06,467: INFO: common: yaml file: config\config.yaml loaded successfully]
[2024-06-26 15:49:06,488: INFO: common: yaml file: params.yaml loaded successfully]
[2024-06-26 15:49:06,489: INFO: common: created directory at: artifacts]
[2024-06-26 15:55:43,663: INFO: common: yaml file: config\config.yaml loaded successfully]
[2024-06-26 15:55:43,663: INFO: common: yaml file: params.yaml loaded successfully]
[2024-06-26 15:55:43,663: INFO: common: created directory at: artifacts]
[2024-06-26 16:01:41,501: INFO: common: json file saved at: scores.json]
[2024-06-26 16:01:44,535: WARNING: save: Found untraced functions such as _jit_compiled_convolution_op, _jit_compiled_convolution_op, _jit_compiled_convolution_op, _jit_compiled_convolution_op, _jit_compiled_convolution_op while saving (showing 5 of 14). These functions will not be directly callable after loading.]
[2024-06-26 16:01:45,235: INFO: builder_impl: Assets written to: C:\Users\ASUS\AppData\Local\Temp\tmprx57bgsa\model\data\model\assets]
[2024-06-27 11:53:47,693: INFO: common: yaml file: config\config.yaml loaded successfully]
[2024-06-27 11:53:47,708: INFO: common: yaml file: params.yaml loaded successfully]
[2024-06-27 11:53:47,709: INFO: common: created directory at: artifacts]
[2024-06-27 12:00:15,174: INFO: common: json file saved at: scores.json]
[2024-06-27 12:00:20,071: WARNING: save: Found untraced functions such as _jit_compiled_convolution_op, _jit_compiled_convolution_op, _jit_compiled_convolution_op, _jit_compiled_convolution_op, _jit_compiled_convolution_op while saving (showing 5 of 14). These functions will not be directly callable after loading.]
[2024-06-27 12:00:21,634: INFO: builder_impl: Assets written to: C:\Users\ASUS\AppData\Local\Temp\tmpfg7b1nbt\model\data\model\assets]
[2024-06-27 12:35:15,678: INFO: main: >>>>>> stage Data Ingestion stage started <<<<<<]
[2024-06-27 12:35:15,678: INFO: common: yaml file: config\config.yaml loaded successfully]
[2024-06-27 12:35:15,695: INFO: common: yaml file: params.yaml loaded successfully]
[2024-06-27 12:35:15,696: INFO: common: created directory at: artifacts]
[2024-06-27 12:35:15,697: INFO: common: created directory at: artifacts/data_ingestion]
[2024-06-27 12:35:15,697: INFO: data_ingestion: Downloading data from https://drive.google.com/file/d/1yLiUUVor0xmtWE830IpivUwYUKS43jfV/view?usp=drive_link into file artifacts/data_ingestion/data.zip]
[2024-06-27 12:37:23,904: INFO: data_ingestion: Downloaded data from https://drive.google.com/file/d/1yLiUUVor0xmtWE830IpivUwYUKS43jfV/view?usp=drive_link into file artifacts/data_ingestion/data.zip]
[2024-06-27 12:37:39,771: INFO: main: >>>>>> stage Data Ingestion stage completed <<<<<<

x==========x]
[2024-06-27 12:37:39,771: INFO: main: >>>>>> stage Prepare base model started <<<<<<]
[2024-06-27 12:37:39,771: INFO: common: yaml file: config\config.yaml loaded successfully]
[2024-06-27 12:37:39,771: INFO: common: yaml file: params.yaml loaded successfully]
[2024-06-27 12:37:39,771: INFO: common: created directory at: artifacts]
[2024-06-27 12:37:39,787: INFO: common: created directory at: artifacts/prepare_base_model]
[2024-06-27 12:37:40,369: WARNING: saving_utils: Compiled the loaded model, but the compiled metrics have yet to be built. `model.compile_metrics` will be empty until you train or evaluate the model.]
[2024-06-27 12:37:40,663: INFO: main: >>>>>> stage Prepare base model completed <<<<<<

x==========x]
[2024-06-27 12:37:40,664: INFO: main: >>>>>> stage Model training started <<<<<<]
[2024-06-27 12:37:40,667: INFO: common: yaml file: config\config.yaml loaded successfully]
[2024-06-27 12:37:40,667: INFO: common: yaml file: params.yaml loaded successfully]
[2024-06-27 12:37:40,667: INFO: common: created directory at: artifacts]
[2024-06-27 12:37:40,669: INFO: common: created directory at: artifacts\training]
[2024-06-27 12:58:07,560: INFO: main: >>>>>> stage Model training completed <<<<<<

x==========x]
[2024-06-27 12:58:07,560: INFO: main: *******************]
[2024-06-27 12:58:07,560: INFO: main: >>>>>> stage Model Evaluation started <<<<<<]
[2024-06-27 12:58:07,563: INFO: common: yaml file: config\config.yaml loaded successfully]
[2024-06-27 12:58:07,565: INFO: common: yaml file: params.yaml loaded successfully]
[2024-06-27 12:58:07,566: INFO: common: created directory at: artifacts]
[2024-06-27 13:04:19,225: INFO: common: json file saved at: scores.json]
[2024-06-27 13:04:19,225: INFO: common: json file saved at: scores.json]
[2024-06-27 13:04:21,192: WARNING: save: Found untraced functions such as _jit_compiled_convolution_op, _jit_compiled_convolution_op, _jit_compiled_convolution_op, _jit_compiled_convolution_op, _jit_compiled_convolution_op while saving (showing 5 of 14). These functions will not be directly callable after loading.]
[2024-06-27 13:04:21,851: INFO: builder_impl: Assets written to: C:\Users\ASUS\AppData\Local\Temp\tmpryssv4kn\model\data\model\assets]
[2024-06-27 13:04:32,161: INFO: dir_util: creating D:\Git\DeepLearning_Classification\mlruns\0\a6604ed67a724b278e272fe2f2d7f7fe\artifacts\model\data]
[2024-06-27 13:04:32,161: INFO: dir_util: creating D:\Git\DeepLearning_Classification\mlruns\0\a6604ed67a724b278e272fe2f2d7f7fe\artifacts\model\data\model]
[2024-06-27 13:04:32,161: INFO: dir_util: creating D:\Git\DeepLearning_Classification\mlruns\0\a6604ed67a724b278e272fe2f2d7f7fe\artifacts\model\data\model\assets]
[2024-06-27 13:04:32,161: INFO: dir_util: creating D:\Git\DeepLearning_Classification\mlruns\0\a6604ed67a724b278e272fe2f2d7f7fe\artifacts\model\data\model\variables]
[2024-06-27 13:04:32,277: INFO: main: >>>>>> stage Model Evaluation completed <<<<<<

x==========x]
[2024-06-27 13:24:31,877: INFO: main: >>>>>> stage Data Ingestion stage started <<<<<<]
[2024-06-27 13:24:31,877: INFO: main: >>>>>> stage Data Ingestion stage completed <<<<<<

x==========x]
[2024-06-27 13:24:31,877: INFO: main: >>>>>> stage Prepare base model started <<<<<<]
[2024-06-27 13:24:31,893: INFO: common: yaml file: config\config.yaml loaded successfully]
[2024-06-27 13:24:31,893: INFO: common: yaml file: params.yaml loaded successfully]
[2024-06-27 13:24:31,893: INFO: common: created directory at: artifacts]
[2024-06-27 13:24:31,893: INFO: common: created directory at: artifacts/prepare_base_model]
[2024-06-27 13:24:32,349: WARNING: saving_utils: Compiled the loaded model, but the compiled metrics have yet to be built. `model.compile_metrics` will be empty until you train or evaluate the model.]
[2024-06-27 13:24:32,569: INFO: main: >>>>>> stage Prepare base model completed <<<<<<

x==========x]
[2024-06-27 13:24:32,569: INFO: main: >>>>>> stage Model training started <<<<<<]
[2024-06-27 13:24:32,583: INFO: common: yaml file: config\config.yaml loaded successfully]
[2024-06-27 13:24:32,585: INFO: common: yaml file: params.yaml loaded successfully]
[2024-06-27 13:24:32,586: INFO: common: created directory at: artifacts]
[2024-06-27 13:24:32,587: INFO: common: created directory at: artifacts\training]
[2024-06-27 13:43:54,425: INFO: main: >>>>>> stage Model training completed <<<<<<

x==========x]
[2024-06-27 13:43:54,425: INFO: main: *******************]
[2024-06-27 13:43:54,425: INFO: main: >>>>>> stage Model Evaluation started <<<<<<]
[2024-06-27 13:43:54,425: INFO: common: yaml file: config\config.yaml loaded successfully]
[2024-06-27 13:43:54,425: INFO: common: yaml file: params.yaml loaded successfully]
[2024-06-27 13:43:54,425: INFO: common: created directory at: artifacts]
[2024-06-27 13:49:33,123: INFO: common: json file saved at: scores.json]
[2024-06-27 13:49:33,123: INFO: common: json file saved at: scores.json]
[2024-06-27 13:49:34,824: WARNING: save: Found untraced functions such as _jit_compiled_convolution_op, _jit_compiled_convolution_op, _jit_compiled_convolution_op, _jit_compiled_convolution_op, _jit_compiled_convolution_op while saving (showing 5 of 14). These functions will not be directly callable after loading.]
[2024-06-27 13:49:35,500: INFO: builder_impl: Assets written to: C:\Users\ASUS\AppData\Local\Temp\tmphn5vppr9\model\data\model\assets]
[2024-06-27 13:49:46,190: INFO: dir_util: creating D:\Git\DeepLearning_Classification\mlruns\0\52252013d9494aad808dc174299a5016\artifacts\model\data]
[2024-06-27 13:49:46,192: INFO: dir_util: creating D:\Git\DeepLearning_Classification\mlruns\0\52252013d9494aad808dc174299a5016\artifacts\model\data\model]
[2024-06-27 13:49:46,193: INFO: dir_util: creating D:\Git\DeepLearning_Classification\mlruns\0\52252013d9494aad808dc174299a5016\artifacts\model\data\model\assets]
[2024-06-27 13:49:46,202: INFO: dir_util: creating D:\Git\DeepLearning_Classification\mlruns\0\52252013d9494aad808dc174299a5016\artifacts\model\data\model\variables]
[2024-06-27 13:49:46,314: INFO: main: >>>>>> stage Model Evaluation completed <<<<<<

x==========x]
[2024-06-27 16:21:05,018: INFO: main: >>>>>> stage Data Ingestion stage started <<<<<<]
[2024-06-27 16:21:05,018: INFO: main: >>>>>> stage Data Ingestion stage completed <<<<<<

x==========x]
[2024-06-27 16:21:05,018: INFO: main: >>>>>> stage Prepare base model started <<<<<<]
[2024-06-27 16:21:05,034: INFO: common: yaml file: config\config.yaml loaded successfully]
[2024-06-27 16:21:05,040: INFO: common: yaml file: params.yaml loaded successfully]
[2024-06-27 16:21:05,040: INFO: common: created directory at: artifacts]
[2024-06-27 16:21:05,040: INFO: common: created directory at: artifacts/prepare_base_model]
[2024-06-27 16:21:05,601: WARNING: saving_utils: Compiled the loaded model, but the compiled metrics have yet to be built. `model.compile_metrics` will be empty until you train or evaluate the model.]
[2024-06-27 16:21:05,853: INFO: main: >>>>>> stage Prepare base model completed <<<<<<

x==========x]
[2024-06-27 16:21:05,853: INFO: main: >>>>>> stage Model training started <<<<<<]
[2024-06-27 16:21:05,853: INFO: common: yaml file: config\config.yaml loaded successfully]
[2024-06-27 16:21:05,853: INFO: common: yaml file: params.yaml loaded successfully]
[2024-06-27 16:21:05,853: INFO: common: created directory at: artifacts]
[2024-06-27 16:21:05,853: INFO: common: created directory at: artifacts\training]
[2024-06-27 16:40:47,585: INFO: main: >>>>>> stage Model training completed <<<<<<

x==========x]
[2024-06-27 16:40:47,585: INFO: main: *******************]
[2024-06-27 16:40:47,585: INFO: main: >>>>>> stage Model Evaluation started <<<<<<]
[2024-06-27 16:40:47,588: INFO: common: yaml file: config\config.yaml loaded successfully]
[2024-06-27 16:40:47,589: INFO: common: yaml file: params.yaml loaded successfully]
[2024-06-27 16:40:47,590: INFO: common: created directory at: artifacts]
[2024-06-27 16:46:37,292: INFO: common: json file saved at: scores.json]
[2024-06-27 16:46:37,293: INFO: common: json file saved at: scores.json]
[2024-06-27 16:46:39,112: WARNING: save: Found untraced functions such as _jit_compiled_convolution_op, _jit_compiled_convolution_op, _jit_compiled_convolution_op, _jit_compiled_convolution_op, _jit_compiled_convolution_op while saving (showing 5 of 14). These functions will not be directly callable after loading.]
[2024-06-27 16:46:39,865: INFO: builder_impl: Assets written to: C:\Users\ASUS\AppData\Local\Temp\tmpfab4fwhc\model\data\model\assets]
[2024-06-27 16:46:48,541: INFO: dir_util: creating D:\Git\DeepLearning_Classification\mlruns\0\2e496bdd69914490b5ddb5b5774a5ebd\artifacts\model\data]
[2024-06-27 16:46:48,543: INFO: dir_util: creating D:\Git\DeepLearning_Classification\mlruns\0\2e496bdd69914490b5ddb5b5774a5ebd\artifacts\model\data\model]
[2024-06-27 16:46:48,543: INFO: dir_util: creating D:\Git\DeepLearning_Classification\mlruns\0\2e496bdd69914490b5ddb5b5774a5ebd\artifacts\model\data\model\assets]
[2024-06-27 16:46:48,549: INFO: dir_util: creating D:\Git\DeepLearning_Classification\mlruns\0\2e496bdd69914490b5ddb5b5774a5ebd\artifacts\model\data\model\variables]
[2024-06-27 16:46:48,638: INFO: main: >>>>>> stage Model Evaluation completed <<<<<<

x==========x]
[2024-06-27 17:26:03,270: INFO: helpers: Initialized MLflow to track repo "delphineasir/DeepLearning_Classification"]
[2024-06-27 17:26:03,270: INFO: helpers: Repository delphineasir/DeepLearning_Classification initialized!]
[2024-06-27 17:28:04,082: INFO: helpers: Initialized MLflow to track repo "delphineasir/DeepLearning_Classification"]
[2024-06-27 17:28:04,082: INFO: helpers: Repository delphineasir/DeepLearning_Classification initialized!]
[2024-06-27 17:29:11,866: INFO: main: >>>>>> stage Data Ingestion stage started <<<<<<]
[2024-06-27 17:29:11,866: INFO: main: >>>>>> stage Data Ingestion stage completed <<<<<<

x==========x]
[2024-06-27 17:29:11,866: INFO: main: >>>>>> stage Prepare base model started <<<<<<]
[2024-06-27 17:29:11,866: INFO: common: yaml file: config\config.yaml loaded successfully]
[2024-06-27 17:29:11,866: INFO: common: yaml file: params.yaml loaded successfully]
[2024-06-27 17:29:11,866: INFO: common: created directory at: artifacts]
[2024-06-27 17:29:11,881: INFO: common: created directory at: artifacts/prepare_base_model]
[2024-06-27 17:29:12,373: WARNING: saving_utils: Compiled the loaded model, but the compiled metrics have yet to be built. `model.compile_metrics` will be empty until you train or evaluate the model.]
[2024-06-27 17:29:12,604: INFO: main: >>>>>> stage Prepare base model completed <<<<<<

x==========x]
[2024-06-27 17:29:12,604: INFO: main: >>>>>> stage Model training started <<<<<<]
[2024-06-27 17:29:12,607: INFO: common: yaml file: config\config.yaml loaded successfully]
[2024-06-27 17:29:12,609: INFO: common: yaml file: params.yaml loaded successfully]
[2024-06-27 17:29:12,609: INFO: common: created directory at: artifacts]
[2024-06-27 17:29:12,610: INFO: common: created directory at: artifacts\training]
[2024-06-27 17:48:04,386: INFO: main: >>>>>> stage Model training completed <<<<<<

x==========x]
[2024-06-27 17:48:04,387: INFO: main: *******************]
[2024-06-27 17:48:04,387: INFO: main: >>>>>> stage Model Evaluation started <<<<<<]
[2024-06-27 17:48:04,391: INFO: common: yaml file: config\config.yaml loaded successfully]
[2024-06-27 17:48:04,392: INFO: common: yaml file: params.yaml loaded successfully]
[2024-06-27 17:48:04,393: INFO: common: created directory at: artifacts]
[2024-06-27 17:53:42,686: INFO: common: json file saved at: scores.json]
[2024-06-27 17:53:42,687: INFO: common: json file saved at: scores.json]
[2024-06-27 17:53:44,349: WARNING: save: Found untraced functions such as _jit_compiled_convolution_op, _jit_compiled_convolution_op, _jit_compiled_convolution_op, _jit_compiled_convolution_op, _jit_compiled_convolution_op while saving (showing 5 of 14). These functions will not be directly callable after loading.]
[2024-06-27 17:53:45,044: INFO: builder_impl: Assets written to: C:\Users\ASUS\AppData\Local\Temp\tmp7bnwimbs\model\data\model\assets]
[2024-06-27 17:53:53,433: INFO: dir_util: creating D:\Git\DeepLearning_Classification\mlruns\0\9058b5246e0647bab90065dbd73b26b9\artifacts\model\data]
[2024-06-27 17:53:53,435: INFO: dir_util: creating D:\Git\DeepLearning_Classification\mlruns\0\9058b5246e0647bab90065dbd73b26b9\artifacts\model\data\model]
[2024-06-27 17:53:53,435: INFO: dir_util: creating D:\Git\DeepLearning_Classification\mlruns\0\9058b5246e0647bab90065dbd73b26b9\artifacts\model\data\model\assets]
[2024-06-27 17:53:53,438: INFO: dir_util: creating D:\Git\DeepLearning_Classification\mlruns\0\9058b5246e0647bab90065dbd73b26b9\artifacts\model\data\model\variables]
[2024-06-27 17:53:53,521: INFO: main: >>>>>> stage Model Evaluation completed <<<<<<

x==========x]
[2024-06-27 19:00:55,269: INFO: main: >>>>>> stage Data Ingestion stage started <<<<<<]
[2024-06-27 19:00:55,269: INFO: main: >>>>>> stage Data Ingestion stage completed <<<<<<

x==========x]
[2024-06-27 19:00:55,269: INFO: main: >>>>>> stage Prepare base model started <<<<<<]
[2024-06-27 19:00:55,285: INFO: common: yaml file: config\config.yaml loaded successfully]
[2024-06-27 19:00:55,285: INFO: common: yaml file: params.yaml loaded successfully]
[2024-06-27 19:00:55,285: INFO: common: created directory at: artifacts]
[2024-06-27 19:00:55,285: INFO: common: created directory at: artifacts/prepare_base_model]
[2024-06-27 19:00:55,728: WARNING: saving_utils: Compiled the loaded model, but the compiled metrics have yet to be built. `model.compile_metrics` will be empty until you train or evaluate the model.]
[2024-06-27 19:00:55,984: INFO: main: >>>>>> stage Prepare base model completed <<<<<<

x==========x]
[2024-06-27 19:00:55,985: INFO: main: >>>>>> stage Model training started <<<<<<]
[2024-06-27 19:00:55,988: INFO: common: yaml file: config\config.yaml loaded successfully]
[2024-06-27 19:00:55,990: INFO: common: yaml file: params.yaml loaded successfully]
[2024-06-27 19:00:55,990: INFO: common: created directory at: artifacts]
[2024-06-27 19:00:55,991: INFO: common: created directory at: artifacts\training]
[2024-06-27 19:20:35,579: INFO: main: >>>>>> stage Model training completed <<<<<<

x==========x]
[2024-06-27 19:20:35,579: INFO: main: *******************]
[2024-06-27 19:20:35,579: INFO: main: >>>>>> stage Model Evaluation started <<<<<<]
[2024-06-27 19:20:35,579: INFO: common: yaml file: config\config.yaml loaded successfully]
[2024-06-27 19:20:35,594: INFO: common: yaml file: params.yaml loaded successfully]
[2024-06-27 19:20:35,596: INFO: common: created directory at: artifacts]
[2024-06-27 19:26:29,998: INFO: common: json file saved at: scores.json]
[2024-06-27 19:26:29,998: INFO: common: json file saved at: scores.json]
[2024-06-27 19:26:31,843: WARNING: save: Found untraced functions such as _jit_compiled_convolution_op, _jit_compiled_convolution_op, _jit_compiled_convolution_op, _jit_compiled_convolution_op, _jit_compiled_convolution_op while saving (showing 5 of 14). These functions will not be directly callable after loading.]
[2024-06-27 19:26:32,509: INFO: builder_impl: Assets written to: C:\Users\ASUS\AppData\Local\Temp\tmpulsicrqp\model\data\model\assets]
[2024-06-27 19:26:41,331: INFO: dir_util: creating D:\Git\DeepLearning_Classification\mlruns\0\84c743e589ea48139206fb95abddcdf6\artifacts\model\data]
[2024-06-27 19:26:41,345: INFO: dir_util: creating D:\Git\DeepLearning_Classification\mlruns\0\84c743e589ea48139206fb95abddcdf6\artifacts\model\data\model]
[2024-06-27 19:26:41,345: INFO: dir_util: creating D:\Git\DeepLearning_Classification\mlruns\0\84c743e589ea48139206fb95abddcdf6\artifacts\model\data\model\assets]
[2024-06-27 19:26:41,345: INFO: dir_util: creating D:\Git\DeepLearning_Classification\mlruns\0\84c743e589ea48139206fb95abddcdf6\artifacts\model\data\model\variables]
[2024-06-27 19:26:41,429: INFO: main: >>>>>> stage Model Evaluation completed <<<<<<

x==========x]
[2024-06-27 21:30:04,244: INFO: main: >>>>>> stage Data Ingestion stage started <<<<<<]
[2024-06-27 21:30:04,244: INFO: main: >>>>>> stage Data Ingestion stage completed <<<<<<

x==========x]
[2024-06-27 21:30:04,244: INFO: main: >>>>>> stage Prepare base model started <<<<<<]
[2024-06-27 21:30:04,244: INFO: common: yaml file: config\config.yaml loaded successfully]
[2024-06-27 21:30:04,244: INFO: common: yaml file: params.yaml loaded successfully]
[2024-06-27 21:30:04,244: INFO: common: created directory at: artifacts]
[2024-06-27 21:30:04,244: INFO: common: created directory at: artifacts/prepare_base_model]
[2024-06-27 21:30:04,714: WARNING: saving_utils: Compiled the loaded model, but the compiled metrics have yet to be built. `model.compile_metrics` will be empty until you train or evaluate the model.]
[2024-06-27 21:30:04,979: INFO: main: >>>>>> stage Prepare base model completed <<<<<<

x==========x]
[2024-06-27 21:30:04,980: INFO: main: >>>>>> stage Model training started <<<<<<]
[2024-06-27 21:30:04,982: INFO: common: yaml file: config\config.yaml loaded successfully]
[2024-06-27 21:30:04,984: INFO: common: yaml file: params.yaml loaded successfully]
[2024-06-27 21:30:04,984: INFO: common: created directory at: artifacts]
[2024-06-27 21:30:04,985: INFO: common: created directory at: artifacts\training]
[2024-06-27 21:49:02,804: INFO: main: >>>>>> stage Model training completed <<<<<<

x==========x]
[2024-06-27 21:49:02,804: INFO: main: *******************]
[2024-06-27 21:49:02,804: INFO: main: >>>>>> stage Model Evaluation started <<<<<<]
[2024-06-27 21:49:02,804: INFO: common: yaml file: config\config.yaml loaded successfully]
[2024-06-27 21:49:02,804: INFO: common: yaml file: params.yaml loaded successfully]
[2024-06-27 21:49:02,804: INFO: common: created directory at: artifacts]
[2024-06-27 21:54:41,941: INFO: common: json file saved at: scores.json]
[2024-06-27 21:54:41,941: INFO: common: json file saved at: scores.json]
[2024-06-27 21:54:43,926: INFO: helpers: Initialized MLflow to track repo "delphineasir/DeepLearning_Classification"]
[2024-06-27 21:54:43,926: INFO: helpers: Repository delphineasir/DeepLearning_Classification initialized!]
[2024-06-27 21:54:44,657: ERROR: main: INVALID_PARAMETER_VALUE: Response: {'error_code': 'INVALID_PARAMETER_VALUE'}]
Traceback (most recent call last):
  File "main.py", line 48, in <module>
    obj.main()
  File "d:\git\deeplearning_classification\src\cnnClassifier\pipeline\stage_04_model_evaluation.py", line 21, in main
    evaluation.log_into_mlflow()
  File "d:\git\deeplearning_classification\src\cnnClassifier\components\model_evaluation_mlflow.py", line 63, in log_into_mlflow
    with mlflow.start_run():
  File "C:\Users\ASUS\anaconda3\envs\kidney\lib\site-packages\mlflow\tracking\fluent.py", line 350, in start_run
    active_run_obj = client.create_run(
  File "C:\Users\ASUS\anaconda3\envs\kidney\lib\site-packages\mlflow\tracking\client.py", line 275, in create_run
    return self._tracking_client.create_run(experiment_id, start_time, tags, run_name)
  File "C:\Users\ASUS\anaconda3\envs\kidney\lib\site-packages\mlflow\tracking\_tracking_service\client.py", line 131, in create_run
    return self.store.create_run(
  File "C:\Users\ASUS\anaconda3\envs\kidney\lib\site-packages\mlflow\store\tracking\rest_store.py", line 175, in create_run
    response_proto = self._call_endpoint(CreateRun, req_body)
  File "C:\Users\ASUS\anaconda3\envs\kidney\lib\site-packages\mlflow\store\tracking\rest_store.py", line 56, in _call_endpoint
    return call_endpoint(self.get_host_creds(), endpoint, method, json_body, response_proto)
  File "C:\Users\ASUS\anaconda3\envs\kidney\lib\site-packages\mlflow\utils\rest_utils.py", line 281, in call_endpoint
    response = verify_rest_response(response, endpoint)
  File "C:\Users\ASUS\anaconda3\envs\kidney\lib\site-packages\mlflow\utils\rest_utils.py", line 207, in verify_rest_response
    raise RestException(json.loads(response.text))
mlflow.exceptions.RestException: INVALID_PARAMETER_VALUE: Response: {'error_code': 'INVALID_PARAMETER_VALUE'}
[2024-06-27 22:57:28,366: INFO: main: >>>>>> stage Data Ingestion stage started <<<<<<]
[2024-06-27 22:57:28,366: INFO: main: >>>>>> stage Data Ingestion stage completed <<<<<<

x==========x]
[2024-06-27 22:57:28,366: INFO: main: >>>>>> stage Prepare base model started <<<<<<]
[2024-06-27 22:57:28,366: INFO: common: yaml file: config\config.yaml loaded successfully]
[2024-06-27 22:57:28,381: INFO: common: yaml file: params.yaml loaded successfully]
[2024-06-27 22:57:28,381: INFO: common: created directory at: artifacts]
[2024-06-27 22:57:28,383: INFO: common: created directory at: artifacts/prepare_base_model]
[2024-06-27 22:57:28,841: WARNING: saving_utils: Compiled the loaded model, but the compiled metrics have yet to be built. `model.compile_metrics` will be empty until you train or evaluate the model.]
[2024-06-27 22:57:29,079: INFO: main: >>>>>> stage Prepare base model completed <<<<<<

x==========x]
[2024-06-27 22:57:29,079: INFO: main: >>>>>> stage Model training started <<<<<<]
[2024-06-27 22:57:29,079: INFO: common: yaml file: config\config.yaml loaded successfully]
[2024-06-27 22:57:29,079: INFO: common: yaml file: params.yaml loaded successfully]
[2024-06-27 22:57:29,079: INFO: common: created directory at: artifacts]
[2024-06-27 22:57:29,091: INFO: common: created directory at: artifacts\training]
[2024-06-27 23:16:33,266: INFO: main: >>>>>> stage Model training completed <<<<<<

x==========x]
[2024-06-27 23:16:33,267: INFO: main: *******************]
[2024-06-27 23:16:33,267: INFO: main: >>>>>> stage Model Evaluation started <<<<<<]
[2024-06-27 23:16:33,270: INFO: common: yaml file: config\config.yaml loaded successfully]
[2024-06-27 23:16:33,272: INFO: common: yaml file: params.yaml loaded successfully]
[2024-06-27 23:16:33,272: INFO: common: created directory at: artifacts]
[2024-06-27 23:22:14,519: INFO: common: json file saved at: scores.json]
[2024-06-27 23:22:14,519: INFO: common: json file saved at: scores.json]
[2024-06-27 23:22:16,302: WARNING: save: Found untraced functions such as _jit_compiled_convolution_op, _jit_compiled_convolution_op, _jit_compiled_convolution_op, _jit_compiled_convolution_op, _jit_compiled_convolution_op while saving (showing 5 of 14). These functions will not be directly callable after loading.]
[2024-06-27 23:22:17,002: INFO: builder_impl: Assets written to: C:\Users\ASUS\AppData\Local\Temp\tmpb6fmso0l\model\data\model\assets]
[2024-06-27 23:22:25,374: ERROR: main: The configured tracking uri scheme: 'file' is invalid for use with the proxy mlflow-artifact scheme. The allowed tracking schemes are: {'http', 'https'}]
Traceback (most recent call last):
  File "main.py", line 48, in <module>
    obj.main()
  File "d:\git\deeplearning_classification\src\cnnClassifier\pipeline\stage_04_model_evaluation.py", line 21, in main
    evaluation.log_into_mlflow()
  File "d:\git\deeplearning_classification\src\cnnClassifier\components\model_evaluation_mlflow.py", line 76, in log_into_mlflow
    mlflow.keras.log_model(self.model, "model")
  File "C:\Users\ASUS\anaconda3\envs\kidney\lib\site-packages\mlflow\tensorflow\__init__.py", line 222, in log_model
    return Model.log(
  File "C:\Users\ASUS\anaconda3\envs\kidney\lib\site-packages\mlflow\models\model.py", line 552, in log
    mlflow.tracking.fluent.log_artifacts(local_path, mlflow_model.artifact_path)
  File "C:\Users\ASUS\anaconda3\envs\kidney\lib\site-packages\mlflow\tracking\fluent.py", line 817, in log_artifacts
    MlflowClient().log_artifacts(run_id, local_dir, artifact_path)
  File "C:\Users\ASUS\anaconda3\envs\kidney\lib\site-packages\mlflow\tracking\client.py", line 1069, in log_artifacts
    self._tracking_client.log_artifacts(run_id, local_dir, artifact_path)
  File "C:\Users\ASUS\anaconda3\envs\kidney\lib\site-packages\mlflow\tracking\_tracking_service\client.py", line 448, in log_artifacts
    self._get_artifact_repo(run_id).log_artifacts(local_dir, artifact_path)
  File "C:\Users\ASUS\anaconda3\envs\kidney\lib\site-packages\mlflow\tracking\_tracking_service\client.py", line 416, in _get_artifact_repo
    artifact_repo = get_artifact_repository(artifact_uri)
  File "C:\Users\ASUS\anaconda3\envs\kidney\lib\site-packages\mlflow\store\artifact\artifact_repository_registry.py", line 106, in get_artifact_repository
    return _artifact_repository_registry.get_artifact_repository(artifact_uri)
  File "C:\Users\ASUS\anaconda3\envs\kidney\lib\site-packages\mlflow\store\artifact\artifact_repository_registry.py", line 72, in get_artifact_repository
    return repository(artifact_uri)
  File "C:\Users\ASUS\anaconda3\envs\kidney\lib\site-packages\mlflow\store\artifact\mlflow_artifacts_repo.py", line 45, in __init__
    super().__init__(self.resolve_uri(artifact_uri, get_tracking_uri()))
  File "C:\Users\ASUS\anaconda3\envs\kidney\lib\site-packages\mlflow\store\artifact\mlflow_artifacts_repo.py", line 59, in resolve_uri
    _validate_uri_scheme(track_parse.scheme)
  File "C:\Users\ASUS\anaconda3\envs\kidney\lib\site-packages\mlflow\store\artifact\mlflow_artifacts_repo.py", line 35, in _validate_uri_scheme
    raise MlflowException(
mlflow.exceptions.MlflowException: The configured tracking uri scheme: 'file' is invalid for use with the proxy mlflow-artifact scheme. The allowed tracking schemes are: {'http', 'https'}
[2024-06-27 23:23:47,676: INFO: main: >>>>>> stage Data Ingestion stage started <<<<<<]
[2024-06-27 23:23:47,676: INFO: main: >>>>>> stage Data Ingestion stage completed <<<<<<

x==========x]
[2024-06-27 23:23:47,676: INFO: main: >>>>>> stage Prepare base model started <<<<<<]
[2024-06-27 23:23:47,676: INFO: common: yaml file: config\config.yaml loaded successfully]
[2024-06-27 23:23:47,692: INFO: common: yaml file: params.yaml loaded successfully]
[2024-06-27 23:23:47,693: INFO: common: created directory at: artifacts]
[2024-06-27 23:23:47,694: INFO: common: created directory at: artifacts/prepare_base_model]
[2024-06-27 23:23:48,107: WARNING: saving_utils: Compiled the loaded model, but the compiled metrics have yet to be built. `model.compile_metrics` will be empty until you train or evaluate the model.]
[2024-06-27 23:23:48,327: INFO: main: >>>>>> stage Prepare base model completed <<<<<<

x==========x]
[2024-06-27 23:23:48,327: INFO: main: >>>>>> stage Model training started <<<<<<]
[2024-06-27 23:23:48,327: INFO: common: yaml file: config\config.yaml loaded successfully]
[2024-06-27 23:23:48,327: INFO: common: yaml file: params.yaml loaded successfully]
[2024-06-27 23:23:48,327: INFO: common: created directory at: artifacts]
[2024-06-27 23:23:48,327: INFO: common: created directory at: artifacts\training]
[2024-06-28 00:02:06,664: INFO: main: >>>>>> stage Model training completed <<<<<<

x==========x]
[2024-06-28 00:02:06,664: INFO: main: *******************]
[2024-06-28 00:02:06,664: INFO: main: >>>>>> stage Model Evaluation started <<<<<<]
[2024-06-28 00:02:06,680: INFO: common: yaml file: config\config.yaml loaded successfully]
[2024-06-28 00:02:06,680: INFO: common: yaml file: params.yaml loaded successfully]
[2024-06-28 00:02:06,680: INFO: common: created directory at: artifacts]
[2024-06-28 10:47:33,616: INFO: main: >>>>>> stage Data Ingestion stage started <<<<<<]
[2024-06-28 10:47:33,617: INFO: main: >>>>>> stage Data Ingestion stage completed <<<<<<

x==========x]
[2024-06-28 10:47:33,618: INFO: main: >>>>>> stage Prepare base model started <<<<<<]
[2024-06-28 10:47:33,628: INFO: common: yaml file: config\config.yaml loaded successfully]
[2024-06-28 10:47:33,634: INFO: common: yaml file: params.yaml loaded successfully]
[2024-06-28 10:47:33,636: INFO: common: created directory at: artifacts]
[2024-06-28 10:47:33,636: INFO: common: created directory at: artifacts/prepare_base_model]
[2024-06-28 10:47:34,388: WARNING: saving_utils: Compiled the loaded model, but the compiled metrics have yet to be built. `model.compile_metrics` will be empty until you train or evaluate the model.]
[2024-06-28 10:47:34,670: INFO: main: >>>>>> stage Prepare base model completed <<<<<<

x==========x]
[2024-06-28 10:47:34,671: INFO: main: >>>>>> stage Model training started <<<<<<]
[2024-06-28 10:47:34,673: INFO: common: yaml file: config\config.yaml loaded successfully]
[2024-06-28 10:47:34,675: INFO: common: yaml file: params.yaml loaded successfully]
[2024-06-28 10:47:34,676: INFO: common: created directory at: artifacts]
[2024-06-28 10:47:34,676: INFO: common: created directory at: artifacts\training]
[2024-06-28 11:31:21,553: INFO: main: >>>>>> stage Model training completed <<<<<<

x==========x]
[2024-06-28 11:31:21,563: INFO: main: *******************]
[2024-06-28 11:31:21,563: INFO: main: >>>>>> stage Model Evaluation started <<<<<<]
[2024-06-28 11:31:21,581: INFO: common: yaml file: config\config.yaml loaded successfully]
[2024-06-28 11:31:21,588: INFO: common: yaml file: params.yaml loaded successfully]
[2024-06-28 11:31:21,589: INFO: common: created directory at: artifacts]
[2024-06-28 11:38:57,834: INFO: common: json file saved at: scores.json]
[2024-06-28 11:38:57,834: INFO: common: json file saved at: scores.json]
[2024-06-28 11:39:00,475: WARNING: save: Found untraced functions such as _jit_compiled_convolution_op, _jit_compiled_convolution_op, _jit_compiled_convolution_op, _jit_compiled_convolution_op, _jit_compiled_convolution_op while saving (showing 5 of 14). These functions will not be directly callable after loading.]
[2024-06-28 11:39:01,225: INFO: builder_impl: Assets written to: C:\Users\ASUS\AppData\Local\Temp\tmpt5kp_pgp\model\data\model\assets]
[2024-06-28 11:39:13,860: ERROR: main: The configured tracking uri scheme: 'file' is invalid for use with the proxy mlflow-artifact scheme. The allowed tracking schemes are: {'http', 'https'}]
Traceback (most recent call last):
  File "main.py", line 48, in <module>
    obj.main()
  File "d:\git\deeplearning_classification\src\cnnClassifier\pipeline\stage_04_model_evaluation.py", line 21, in main
    evaluation.log_into_mlflow()
  File "d:\git\deeplearning_classification\src\cnnClassifier\components\model_evaluation_mlflow.py", line 76, in log_into_mlflow
    mlflow.keras.log_model(self.model, "model")
  File "C:\Users\ASUS\anaconda3\envs\kidney\lib\site-packages\mlflow\tensorflow\__init__.py", line 222, in log_model
    return Model.log(
  File "C:\Users\ASUS\anaconda3\envs\kidney\lib\site-packages\mlflow\models\model.py", line 552, in log
    mlflow.tracking.fluent.log_artifacts(local_path, mlflow_model.artifact_path)
  File "C:\Users\ASUS\anaconda3\envs\kidney\lib\site-packages\mlflow\tracking\fluent.py", line 817, in log_artifacts
    MlflowClient().log_artifacts(run_id, local_dir, artifact_path)
  File "C:\Users\ASUS\anaconda3\envs\kidney\lib\site-packages\mlflow\tracking\client.py", line 1069, in log_artifacts
    self._tracking_client.log_artifacts(run_id, local_dir, artifact_path)
  File "C:\Users\ASUS\anaconda3\envs\kidney\lib\site-packages\mlflow\tracking\_tracking_service\client.py", line 448, in log_artifacts
    self._get_artifact_repo(run_id).log_artifacts(local_dir, artifact_path)
  File "C:\Users\ASUS\anaconda3\envs\kidney\lib\site-packages\mlflow\tracking\_tracking_service\client.py", line 416, in _get_artifact_repo
    artifact_repo = get_artifact_repository(artifact_uri)
  File "C:\Users\ASUS\anaconda3\envs\kidney\lib\site-packages\mlflow\store\artifact\artifact_repository_registry.py", line 106, in get_artifact_repository
    return _artifact_repository_registry.get_artifact_repository(artifact_uri)
  File "C:\Users\ASUS\anaconda3\envs\kidney\lib\site-packages\mlflow\store\artifact\artifact_repository_registry.py", line 72, in get_artifact_repository
    return repository(artifact_uri)
  File "C:\Users\ASUS\anaconda3\envs\kidney\lib\site-packages\mlflow\store\artifact\mlflow_artifacts_repo.py", line 45, in __init__
    super().__init__(self.resolve_uri(artifact_uri, get_tracking_uri()))
  File "C:\Users\ASUS\anaconda3\envs\kidney\lib\site-packages\mlflow\store\artifact\mlflow_artifacts_repo.py", line 59, in resolve_uri
    _validate_uri_scheme(track_parse.scheme)
  File "C:\Users\ASUS\anaconda3\envs\kidney\lib\site-packages\mlflow\store\artifact\mlflow_artifacts_repo.py", line 35, in _validate_uri_scheme
    raise MlflowException(
mlflow.exceptions.MlflowException: The configured tracking uri scheme: 'file' is invalid for use with the proxy mlflow-artifact scheme. The allowed tracking schemes are: {'http', 'https'}
[2024-06-28 11:59:24,721: INFO: main: >>>>>> stage Data Ingestion stage started <<<<<<]
[2024-06-28 11:59:24,721: INFO: main: >>>>>> stage Data Ingestion stage completed <<<<<<

x==========x]
[2024-06-28 11:59:24,721: INFO: main: >>>>>> stage Prepare base model started <<<<<<]
[2024-06-28 11:59:24,721: INFO: common: yaml file: config\config.yaml loaded successfully]
[2024-06-28 11:59:24,721: INFO: common: yaml file: params.yaml loaded successfully]
[2024-06-28 11:59:24,721: INFO: common: created directory at: artifacts]
[2024-06-28 11:59:24,721: INFO: common: created directory at: artifacts/prepare_base_model]
[2024-06-28 11:59:25,190: WARNING: saving_utils: Compiled the loaded model, but the compiled metrics have yet to be built. `model.compile_metrics` will be empty until you train or evaluate the model.]
[2024-06-28 11:59:25,440: INFO: main: >>>>>> stage Prepare base model completed <<<<<<

x==========x]
[2024-06-28 11:59:25,440: INFO: main: >>>>>> stage Model training started <<<<<<]
[2024-06-28 11:59:25,456: INFO: common: yaml file: config\config.yaml loaded successfully]
[2024-06-28 11:59:25,456: INFO: common: yaml file: params.yaml loaded successfully]
[2024-06-28 11:59:25,456: INFO: common: created directory at: artifacts]
[2024-06-28 11:59:25,456: INFO: common: created directory at: artifacts\training]
[2024-06-28 12:59:58,125: INFO: main: >>>>>> stage Model training completed <<<<<<

x==========x]
[2024-06-28 12:59:58,125: INFO: main: *******************]
[2024-06-28 12:59:58,125: INFO: main: >>>>>> stage Model Evaluation started <<<<<<]
[2024-06-28 12:59:58,156: INFO: common: yaml file: config\config.yaml loaded successfully]
[2024-06-28 12:59:58,156: INFO: common: yaml file: params.yaml loaded successfully]
[2024-06-28 12:59:58,156: INFO: common: created directory at: artifacts]
[2024-06-28 13:06:14,828: INFO: common: json file saved at: scores.json]
[2024-06-28 13:06:14,829: INFO: common: json file saved at: scores.json]
[2024-06-28 13:06:15,542: WARNING: connectionpool: Retrying (Retry(total=4, connect=4, read=5, redirect=5, status=5)) after connection broken by 'NewConnectionError('<urllib3.connection.HTTPSConnection object at 0x0000022D42077F10>: Failed to establish a new connection: [Errno 11001] getaddrinfo failed')': /delphineasir/DeepLearning_Classification.mlflow/api/2.0/mlflow/runs/create]
[2024-06-28 13:06:19,558: WARNING: connectionpool: Retrying (Retry(total=3, connect=3, read=5, redirect=5, status=5)) after connection broken by 'NewConnectionError('<urllib3.connection.HTTPSConnection object at 0x0000022D420776A0>: Failed to establish a new connection: [Errno 11001] getaddrinfo failed')': /delphineasir/DeepLearning_Classification.mlflow/api/2.0/mlflow/runs/create]
[2024-06-28 13:06:27,571: WARNING: connectionpool: Retrying (Retry(total=2, connect=2, read=5, redirect=5, status=5)) after connection broken by 'NewConnectionError('<urllib3.connection.HTTPSConnection object at 0x0000022D42077DC0>: Failed to establish a new connection: [Errno 11001] getaddrinfo failed')': /delphineasir/DeepLearning_Classification.mlflow/api/2.0/mlflow/runs/create]
[2024-06-28 13:06:28,149: ERROR: main: API request to endpoint /api/2.0/mlflow/runs/create failed with error code 403 != 200. Response body: '']
Traceback (most recent call last):
  File "main.py", line 48, in <module>
    obj.main()
  File "d:\git\deeplearning_classification\src\cnnClassifier\pipeline\stage_04_model_evaluation.py", line 21, in main
    evaluation.log_into_mlflow()
  File "d:\git\deeplearning_classification\src\cnnClassifier\components\model_evaluation_mlflow.py", line 62, in log_into_mlflow
    with mlflow.start_run():
  File "C:\Users\ASUS\anaconda3\envs\kidney\lib\site-packages\mlflow\tracking\fluent.py", line 350, in start_run
    active_run_obj = client.create_run(
  File "C:\Users\ASUS\anaconda3\envs\kidney\lib\site-packages\mlflow\tracking\client.py", line 275, in create_run
    return self._tracking_client.create_run(experiment_id, start_time, tags, run_name)
  File "C:\Users\ASUS\anaconda3\envs\kidney\lib\site-packages\mlflow\tracking\_tracking_service\client.py", line 131, in create_run
    return self.store.create_run(
  File "C:\Users\ASUS\anaconda3\envs\kidney\lib\site-packages\mlflow\store\tracking\rest_store.py", line 175, in create_run
    response_proto = self._call_endpoint(CreateRun, req_body)
  File "C:\Users\ASUS\anaconda3\envs\kidney\lib\site-packages\mlflow\store\tracking\rest_store.py", line 56, in _call_endpoint
    return call_endpoint(self.get_host_creds(), endpoint, method, json_body, response_proto)
  File "C:\Users\ASUS\anaconda3\envs\kidney\lib\site-packages\mlflow\utils\rest_utils.py", line 281, in call_endpoint
    response = verify_rest_response(response, endpoint)
  File "C:\Users\ASUS\anaconda3\envs\kidney\lib\site-packages\mlflow\utils\rest_utils.py", line 213, in verify_rest_response
    raise MlflowException(
mlflow.exceptions.MlflowException: API request to endpoint /api/2.0/mlflow/runs/create failed with error code 403 != 200. Response body: ''
[2024-06-28 15:27:48,462: INFO: main: >>>>>> stage Data Ingestion stage started <<<<<<]
[2024-06-28 15:27:48,479: INFO: main: >>>>>> stage Data Ingestion stage completed <<<<<<

x==========x]
[2024-06-28 15:27:48,479: INFO: main: >>>>>> stage Prepare base model started <<<<<<]
[2024-06-28 15:27:48,479: INFO: common: yaml file: config\config.yaml loaded successfully]
[2024-06-28 15:27:48,479: INFO: common: yaml file: params.yaml loaded successfully]
[2024-06-28 15:27:48,479: INFO: common: created directory at: artifacts]
[2024-06-28 15:27:48,479: INFO: common: created directory at: artifacts/prepare_base_model]
[2024-06-28 15:27:49,053: WARNING: saving_utils: Compiled the loaded model, but the compiled metrics have yet to be built. `model.compile_metrics` will be empty until you train or evaluate the model.]
[2024-06-28 15:27:49,320: INFO: main: >>>>>> stage Prepare base model completed <<<<<<

x==========x]
[2024-06-28 15:27:49,320: INFO: main: >>>>>> stage Model training started <<<<<<]
[2024-06-28 15:27:49,320: INFO: common: yaml file: config\config.yaml loaded successfully]
[2024-06-28 15:27:49,320: INFO: common: yaml file: params.yaml loaded successfully]
[2024-06-28 15:27:49,320: INFO: common: created directory at: artifacts]
[2024-06-28 15:27:49,320: INFO: common: created directory at: artifacts\training]
[2024-06-28 15:30:32,591: INFO: main: >>>>>> stage Data Ingestion stage started <<<<<<]
[2024-06-28 15:30:32,591: INFO: main: >>>>>> stage Data Ingestion stage completed <<<<<<

x==========x]
[2024-06-28 15:30:32,591: INFO: main: >>>>>> stage Prepare base model started <<<<<<]
[2024-06-28 15:30:32,591: INFO: common: yaml file: config\config.yaml loaded successfully]
[2024-06-28 15:30:32,591: INFO: common: yaml file: params.yaml loaded successfully]
[2024-06-28 15:30:32,591: INFO: common: created directory at: artifacts]
[2024-06-28 15:30:32,591: INFO: common: created directory at: artifacts/prepare_base_model]
[2024-06-28 15:30:33,055: WARNING: saving_utils: Compiled the loaded model, but the compiled metrics have yet to be built. `model.compile_metrics` will be empty until you train or evaluate the model.]
[2024-06-28 15:30:33,313: INFO: main: >>>>>> stage Prepare base model completed <<<<<<

x==========x]
[2024-06-28 15:30:33,313: INFO: main: >>>>>> stage Model training started <<<<<<]
[2024-06-28 15:30:33,313: INFO: common: yaml file: config\config.yaml loaded successfully]
[2024-06-28 15:30:33,323: INFO: common: yaml file: params.yaml loaded successfully]
[2024-06-28 15:30:33,324: INFO: common: created directory at: artifacts]
[2024-06-28 15:30:33,324: INFO: common: created directory at: artifacts\training]
[2024-06-28 15:52:37,293: INFO: main: >>>>>> stage Model training completed <<<<<<

x==========x]
[2024-06-28 15:52:37,293: INFO: main: *******************]
[2024-06-28 15:52:37,293: INFO: main: >>>>>> stage Model Evaluation started <<<<<<]
[2024-06-28 15:52:37,310: INFO: common: yaml file: config\config.yaml loaded successfully]
[2024-06-28 15:52:37,310: INFO: common: yaml file: params.yaml loaded successfully]
[2024-06-28 15:52:37,310: INFO: common: created directory at: artifacts]
[2024-06-28 15:58:16,453: INFO: common: json file saved at: scores.json]
[2024-06-28 15:58:16,453: INFO: common: json file saved at: scores.json]
[2024-06-28 15:58:17,693: ERROR: main: INVALID_PARAMETER_VALUE: Response: {'error_code': 'INVALID_PARAMETER_VALUE'}]
Traceback (most recent call last):
  File "main.py", line 48, in <module>
    obj.main()
  File "d:\git\deeplearning_classification\src\cnnClassifier\pipeline\stage_04_model_evaluation.py", line 21, in main
    evaluation.log_into_mlflow()
  File "d:\git\deeplearning_classification\src\cnnClassifier\components\model_evaluation_mlflow.py", line 62, in log_into_mlflow
    with mlflow.start_run():
  File "C:\Users\ASUS\anaconda3\envs\kidney\lib\site-packages\mlflow\tracking\fluent.py", line 350, in start_run
    active_run_obj = client.create_run(
  File "C:\Users\ASUS\anaconda3\envs\kidney\lib\site-packages\mlflow\tracking\client.py", line 275, in create_run
    return self._tracking_client.create_run(experiment_id, start_time, tags, run_name)
  File "C:\Users\ASUS\anaconda3\envs\kidney\lib\site-packages\mlflow\tracking\_tracking_service\client.py", line 131, in create_run
    return self.store.create_run(
  File "C:\Users\ASUS\anaconda3\envs\kidney\lib\site-packages\mlflow\store\tracking\rest_store.py", line 175, in create_run
    response_proto = self._call_endpoint(CreateRun, req_body)
  File "C:\Users\ASUS\anaconda3\envs\kidney\lib\site-packages\mlflow\store\tracking\rest_store.py", line 56, in _call_endpoint
    return call_endpoint(self.get_host_creds(), endpoint, method, json_body, response_proto)
  File "C:\Users\ASUS\anaconda3\envs\kidney\lib\site-packages\mlflow\utils\rest_utils.py", line 281, in call_endpoint
    response = verify_rest_response(response, endpoint)
  File "C:\Users\ASUS\anaconda3\envs\kidney\lib\site-packages\mlflow\utils\rest_utils.py", line 207, in verify_rest_response
    raise RestException(json.loads(response.text))
mlflow.exceptions.RestException: INVALID_PARAMETER_VALUE: Response: {'error_code': 'INVALID_PARAMETER_VALUE'}
[2024-06-28 17:13:11,292: INFO: main: >>>>>> stage Data Ingestion stage started <<<<<<]
[2024-06-28 17:13:11,292: INFO: main: >>>>>> stage Data Ingestion stage completed <<<<<<

x==========x]
[2024-06-28 17:13:11,292: INFO: main: >>>>>> stage Prepare base model started <<<<<<]
[2024-06-28 17:13:11,306: INFO: common: yaml file: config\config.yaml loaded successfully]
[2024-06-28 17:13:11,311: INFO: common: yaml file: params.yaml loaded successfully]
[2024-06-28 17:13:11,312: INFO: common: created directory at: artifacts]
[2024-06-28 17:13:11,312: INFO: common: created directory at: artifacts/prepare_base_model]
[2024-06-28 17:13:12,205: WARNING: saving_utils: Compiled the loaded model, but the compiled metrics have yet to be built. `model.compile_metrics` will be empty until you train or evaluate the model.]
[2024-06-28 17:13:12,457: INFO: main: >>>>>> stage Prepare base model completed <<<<<<

x==========x]
[2024-06-28 17:13:12,457: INFO: main: >>>>>> stage Model training started <<<<<<]
[2024-06-28 17:13:12,475: INFO: common: yaml file: config\config.yaml loaded successfully]
[2024-06-28 17:13:12,477: INFO: common: yaml file: params.yaml loaded successfully]
[2024-06-28 17:13:12,478: INFO: common: created directory at: artifacts]
[2024-06-28 17:13:12,478: INFO: common: created directory at: artifacts\training]
[2024-06-28 19:07:17,075: INFO: main: >>>>>> stage Model training completed <<<<<<

x==========x]
[2024-06-28 19:07:17,075: INFO: main: *******************]
[2024-06-28 19:07:17,076: INFO: main: >>>>>> stage Model Evaluation started <<<<<<]
[2024-06-28 19:07:17,078: INFO: common: yaml file: config\config.yaml loaded successfully]
[2024-06-28 19:07:17,082: INFO: common: yaml file: params.yaml loaded successfully]
[2024-06-28 19:07:17,082: INFO: common: created directory at: artifacts]
[2024-06-28 19:12:56,322: INFO: common: json file saved at: scores.json]
[2024-06-28 19:12:56,322: INFO: common: json file saved at: scores.json]
[2024-06-28 19:12:57,512: ERROR: main: INVALID_PARAMETER_VALUE: Response: {'error_code': 'INVALID_PARAMETER_VALUE'}]
Traceback (most recent call last):
  File "main.py", line 48, in <module>
    obj.main()
  File "d:\git\deeplearning_classification\src\cnnClassifier\pipeline\stage_04_model_evaluation.py", line 21, in main
    evaluation.log_into_mlflow()
  File "d:\git\deeplearning_classification\src\cnnClassifier\components\model_evaluation_mlflow.py", line 62, in log_into_mlflow
    with mlflow.start_run():
  File "C:\Users\ASUS\anaconda3\envs\kidney\lib\site-packages\mlflow\tracking\fluent.py", line 350, in start_run
    active_run_obj = client.create_run(
  File "C:\Users\ASUS\anaconda3\envs\kidney\lib\site-packages\mlflow\tracking\client.py", line 275, in create_run
    return self._tracking_client.create_run(experiment_id, start_time, tags, run_name)
  File "C:\Users\ASUS\anaconda3\envs\kidney\lib\site-packages\mlflow\tracking\_tracking_service\client.py", line 131, in create_run
    return self.store.create_run(
  File "C:\Users\ASUS\anaconda3\envs\kidney\lib\site-packages\mlflow\store\tracking\rest_store.py", line 175, in create_run
    response_proto = self._call_endpoint(CreateRun, req_body)
  File "C:\Users\ASUS\anaconda3\envs\kidney\lib\site-packages\mlflow\store\tracking\rest_store.py", line 56, in _call_endpoint
    return call_endpoint(self.get_host_creds(), endpoint, method, json_body, response_proto)
  File "C:\Users\ASUS\anaconda3\envs\kidney\lib\site-packages\mlflow\utils\rest_utils.py", line 281, in call_endpoint
    response = verify_rest_response(response, endpoint)
  File "C:\Users\ASUS\anaconda3\envs\kidney\lib\site-packages\mlflow\utils\rest_utils.py", line 207, in verify_rest_response
    raise RestException(json.loads(response.text))
mlflow.exceptions.RestException: INVALID_PARAMETER_VALUE: Response: {'error_code': 'INVALID_PARAMETER_VALUE'}
[2024-06-28 19:19:26,861: INFO: main: >>>>>> stage Data Ingestion stage started <<<<<<]
[2024-06-28 19:19:26,861: INFO: main: >>>>>> stage Data Ingestion stage completed <<<<<<

x==========x]
[2024-06-28 19:19:26,861: INFO: main: >>>>>> stage Prepare base model started <<<<<<]
[2024-06-28 19:19:26,861: INFO: main: >>>>>> stage Prepare base model completed <<<<<<

x==========x]
[2024-06-28 19:19:26,861: INFO: main: >>>>>> stage Model training started <<<<<<]
[2024-06-28 19:19:26,861: INFO: main: >>>>>> stage Model training completed <<<<<<

x==========x]
[2024-06-28 19:19:26,861: INFO: main: *******************]
[2024-06-28 19:19:26,861: INFO: main: >>>>>> stage Model Evaluation started <<<<<<]
[2024-06-28 19:19:26,861: INFO: common: yaml file: config\config.yaml loaded successfully]
[2024-06-28 19:19:26,871: INFO: common: yaml file: params.yaml loaded successfully]
[2024-06-28 19:19:26,872: INFO: common: created directory at: artifacts]
[2024-06-28 19:21:36,659: INFO: main: >>>>>> stage Data Ingestion stage started <<<<<<]
[2024-06-28 19:21:36,659: INFO: main: >>>>>> stage Data Ingestion stage completed <<<<<<

x==========x]
[2024-06-28 19:21:36,659: INFO: main: >>>>>> stage Prepare base model started <<<<<<]
[2024-06-28 19:21:36,659: INFO: main: >>>>>> stage Prepare base model completed <<<<<<

x==========x]
[2024-06-28 19:21:36,659: INFO: main: >>>>>> stage Model training started <<<<<<]
[2024-06-28 19:21:36,659: INFO: main: >>>>>> stage Model training completed <<<<<<

x==========x]
[2024-06-28 19:21:36,659: INFO: main: *******************]
[2024-06-28 19:21:36,659: INFO: main: >>>>>> stage Model Evaluation started <<<<<<]
[2024-06-28 19:21:36,675: INFO: common: yaml file: config\config.yaml loaded successfully]
[2024-06-28 19:21:36,679: INFO: common: yaml file: params.yaml loaded successfully]
[2024-06-28 19:21:36,680: INFO: common: created directory at: artifacts]
[2024-06-28 19:27:40,017: INFO: common: json file saved at: scores.json]
[2024-06-28 19:27:40,017: INFO: common: json file saved at: scores.json]
[2024-06-28 19:27:41,139: ERROR: main: INVALID_PARAMETER_VALUE: Response: {'error_code': 'INVALID_PARAMETER_VALUE'}]
Traceback (most recent call last):
  File "main.py", line 48, in <module>
    obj.main()
  File "d:\git\deeplearning_classification\src\cnnClassifier\pipeline\stage_04_model_evaluation.py", line 21, in main
    evaluation.log_into_mlflow()
  File "d:\git\deeplearning_classification\src\cnnClassifier\components\model_evaluation_mlflow.py", line 62, in log_into_mlflow
    with mlflow.start_run():
  File "C:\Users\ASUS\anaconda3\envs\kidney\lib\site-packages\mlflow\tracking\fluent.py", line 382, in start_run
    active_run_obj = client.create_run(
  File "C:\Users\ASUS\anaconda3\envs\kidney\lib\site-packages\mlflow\tracking\client.py", line 393, in create_run
    return self._tracking_client.create_run(experiment_id, start_time, tags, run_name)
  File "C:\Users\ASUS\anaconda3\envs\kidney\lib\site-packages\mlflow\tracking\_tracking_service\client.py", line 165, in create_run
    return self.store.create_run(
  File "C:\Users\ASUS\anaconda3\envs\kidney\lib\site-packages\mlflow\store\tracking\rest_store.py", line 208, in create_run
    response_proto = self._call_endpoint(CreateRun, req_body)
  File "C:\Users\ASUS\anaconda3\envs\kidney\lib\site-packages\mlflow\store\tracking\rest_store.py", line 81, in _call_endpoint
    return call_endpoint(self.get_host_creds(), endpoint, method, json_body, response_proto)
  File "C:\Users\ASUS\anaconda3\envs\kidney\lib\site-packages\mlflow\utils\rest_utils.py", line 304, in call_endpoint
    response = verify_rest_response(response, endpoint)
  File "C:\Users\ASUS\anaconda3\envs\kidney\lib\site-packages\mlflow\utils\rest_utils.py", line 174, in verify_rest_response
    raise RestException(json.loads(response.text))
mlflow.exceptions.RestException: INVALID_PARAMETER_VALUE: Response: {'error_code': 'INVALID_PARAMETER_VALUE'}
[2024-06-28 23:05:33,055: INFO: main: >>>>>> stage Data Ingestion stage started <<<<<<]
[2024-06-28 23:05:33,055: INFO: main: >>>>>> stage Data Ingestion stage completed <<<<<<

x==========x]
[2024-06-28 23:05:33,055: INFO: main: >>>>>> stage Prepare base model started <<<<<<]
[2024-06-28 23:05:33,055: INFO: main: >>>>>> stage Prepare base model completed <<<<<<

x==========x]
[2024-06-28 23:05:33,055: INFO: main: >>>>>> stage Model training started <<<<<<]
[2024-06-28 23:05:33,055: INFO: main: >>>>>> stage Model training completed <<<<<<

x==========x]
[2024-06-28 23:05:33,055: INFO: main: *******************]
[2024-06-28 23:05:33,055: INFO: main: >>>>>> stage Model Evaluation started <<<<<<]
[2024-06-28 23:05:33,076: INFO: common: yaml file: config\config.yaml loaded successfully]
[2024-06-28 23:05:33,077: INFO: common: yaml file: params.yaml loaded successfully]
[2024-06-28 23:05:33,077: INFO: common: created directory at: artifacts]
[2024-06-28 23:11:31,822: INFO: common: json file saved at: scores.json]
[2024-06-28 23:11:31,838: INFO: common: json file saved at: scores.json]
[2024-06-28 23:11:32,967: ERROR: main: INVALID_PARAMETER_VALUE: Response: {'error_code': 'INVALID_PARAMETER_VALUE'}]
Traceback (most recent call last):
  File "main.py", line 48, in <module>
    obj.main()
  File "d:\git\deeplearning_classification\src\cnnClassifier\pipeline\stage_04_model_evaluation.py", line 21, in main
    evaluation.log_into_mlflow()
  File "d:\git\deeplearning_classification\src\cnnClassifier\components\model_evaluation_mlflow.py", line 62, in log_into_mlflow
    with mlflow.start_run():
  File "C:\Users\ASUS\anaconda3\envs\kidney\lib\site-packages\mlflow\tracking\fluent.py", line 382, in start_run
    active_run_obj = client.create_run(
  File "C:\Users\ASUS\anaconda3\envs\kidney\lib\site-packages\mlflow\tracking\client.py", line 393, in create_run
    return self._tracking_client.create_run(experiment_id, start_time, tags, run_name)
  File "C:\Users\ASUS\anaconda3\envs\kidney\lib\site-packages\mlflow\tracking\_tracking_service\client.py", line 165, in create_run
    return self.store.create_run(
  File "C:\Users\ASUS\anaconda3\envs\kidney\lib\site-packages\mlflow\store\tracking\rest_store.py", line 208, in create_run
    response_proto = self._call_endpoint(CreateRun, req_body)
  File "C:\Users\ASUS\anaconda3\envs\kidney\lib\site-packages\mlflow\store\tracking\rest_store.py", line 81, in _call_endpoint
    return call_endpoint(self.get_host_creds(), endpoint, method, json_body, response_proto)
  File "C:\Users\ASUS\anaconda3\envs\kidney\lib\site-packages\mlflow\utils\rest_utils.py", line 304, in call_endpoint
    response = verify_rest_response(response, endpoint)
  File "C:\Users\ASUS\anaconda3\envs\kidney\lib\site-packages\mlflow\utils\rest_utils.py", line 174, in verify_rest_response
    raise RestException(json.loads(response.text))
mlflow.exceptions.RestException: INVALID_PARAMETER_VALUE: Response: {'error_code': 'INVALID_PARAMETER_VALUE'}
[2024-06-29 09:52:53,607: INFO: main: >>>>>> stage Data Ingestion stage started <<<<<<]
[2024-06-29 09:52:53,609: INFO: main: >>>>>> stage Data Ingestion stage completed <<<<<<

x==========x]
[2024-06-29 09:52:53,609: INFO: main: >>>>>> stage Prepare base model started <<<<<<]
[2024-06-29 09:52:53,609: INFO: main: >>>>>> stage Prepare base model completed <<<<<<

x==========x]
[2024-06-29 09:52:53,609: INFO: main: >>>>>> stage Model training started <<<<<<]
[2024-06-29 09:52:53,609: INFO: main: >>>>>> stage Model training completed <<<<<<

x==========x]
[2024-06-29 09:52:53,609: INFO: main: *******************]
[2024-06-29 09:52:53,609: INFO: main: >>>>>> stage Model Evaluation started <<<<<<]
[2024-06-29 09:52:53,609: INFO: common: yaml file: config\config.yaml loaded successfully]
[2024-06-29 09:52:53,634: INFO: common: yaml file: params.yaml loaded successfully]
[2024-06-29 09:52:53,636: INFO: common: created directory at: artifacts]
[2024-06-29 09:58:48,064: INFO: common: json file saved at: scores.json]
[2024-06-29 09:58:48,065: INFO: common: json file saved at: scores.json]
[2024-06-29 09:58:51,611: WARNING: save: Found untraced functions such as _jit_compiled_convolution_op, _jit_compiled_convolution_op, _jit_compiled_convolution_op, _jit_compiled_convolution_op, _jit_compiled_convolution_op while saving (showing 5 of 14). These functions will not be directly callable after loading.]
[2024-06-29 09:58:52,298: INFO: builder_impl: Assets written to: C:\Users\ASUS\AppData\Local\Temp\tmprfdrti0o\model\data\model\assets]
[2024-06-29 09:59:38,030: INFO: main: >>>>>> stage Model Evaluation completed <<<<<<

x==========x]
[2024-06-29 10:01:21,511: INFO: main: >>>>>> stage Data Ingestion stage started <<<<<<]
[2024-06-29 10:01:21,511: INFO: main: >>>>>> stage Data Ingestion stage completed <<<<<<

x==========x]
[2024-06-29 10:01:21,511: INFO: main: >>>>>> stage Prepare base model started <<<<<<]
[2024-06-29 10:01:21,527: INFO: common: yaml file: config\config.yaml loaded successfully]
[2024-06-29 10:01:21,527: INFO: common: yaml file: params.yaml loaded successfully]
[2024-06-29 10:01:21,527: INFO: common: created directory at: artifacts]
[2024-06-29 10:01:21,527: INFO: common: created directory at: artifacts/prepare_base_model]
[2024-06-29 10:01:22,058: WARNING: saving_utils: Compiled the loaded model, but the compiled metrics have yet to be built. `model.compile_metrics` will be empty until you train or evaluate the model.]
[2024-06-29 10:01:22,342: INFO: main: >>>>>> stage Prepare base model completed <<<<<<

x==========x]
[2024-06-29 10:01:22,342: INFO: main: >>>>>> stage Model training started <<<<<<]
[2024-06-29 10:01:22,348: INFO: common: yaml file: config\config.yaml loaded successfully]
[2024-06-29 10:01:22,351: INFO: common: yaml file: params.yaml loaded successfully]
[2024-06-29 10:01:22,352: INFO: common: created directory at: artifacts]
[2024-06-29 10:01:22,353: INFO: common: created directory at: artifacts\training]
[2024-06-29 10:20:56,112: INFO: main: >>>>>> stage Model training completed <<<<<<

x==========x]
[2024-06-29 10:20:56,112: INFO: main: *******************]
[2024-06-29 10:20:56,112: INFO: main: >>>>>> stage Model Evaluation started <<<<<<]
[2024-06-29 10:20:56,112: INFO: common: yaml file: config\config.yaml loaded successfully]
[2024-06-29 10:20:56,112: INFO: common: yaml file: params.yaml loaded successfully]
[2024-06-29 10:20:56,112: INFO: common: created directory at: artifacts]
[2024-06-29 10:26:44,805: INFO: common: json file saved at: scores.json]
[2024-06-29 10:26:44,805: INFO: common: json file saved at: scores.json]
[2024-06-29 10:26:48,022: WARNING: save: Found untraced functions such as _jit_compiled_convolution_op, _jit_compiled_convolution_op, _jit_compiled_convolution_op, _jit_compiled_convolution_op, _jit_compiled_convolution_op while saving (showing 5 of 14). These functions will not be directly callable after loading.]
[2024-06-29 10:26:48,769: INFO: builder_impl: Assets written to: C:\Users\ASUS\AppData\Local\Temp\tmpd_w7vzew\model\data\model\assets]
[2024-06-29 10:27:33,319: INFO: main: >>>>>> stage Model Evaluation completed <<<<<<

x==========x]
[2024-06-29 10:29:35,244: INFO: main: >>>>>> stage Data Ingestion stage started <<<<<<]
[2024-06-29 10:29:35,244: INFO: main: >>>>>> stage Data Ingestion stage completed <<<<<<

x==========x]
[2024-06-29 10:29:35,244: INFO: main: >>>>>> stage Prepare base model started <<<<<<]
[2024-06-29 10:29:35,244: INFO: common: yaml file: config\config.yaml loaded successfully]
[2024-06-29 10:29:35,269: INFO: common: yaml file: params.yaml loaded successfully]
[2024-06-29 10:29:35,271: INFO: common: created directory at: artifacts]
[2024-06-29 10:29:35,272: INFO: common: created directory at: artifacts/prepare_base_model]
[2024-06-29 10:29:35,869: WARNING: saving_utils: Compiled the loaded model, but the compiled metrics have yet to be built. `model.compile_metrics` will be empty until you train or evaluate the model.]
[2024-06-29 10:29:36,152: INFO: main: >>>>>> stage Prepare base model completed <<<<<<

x==========x]
[2024-06-29 10:29:36,153: INFO: main: >>>>>> stage Model training started <<<<<<]
[2024-06-29 10:29:36,156: INFO: common: yaml file: config\config.yaml loaded successfully]
[2024-06-29 10:29:36,160: INFO: common: yaml file: params.yaml loaded successfully]
[2024-06-29 10:29:36,161: INFO: common: created directory at: artifacts]
[2024-06-29 10:29:36,162: INFO: common: created directory at: artifacts\training]
[2024-06-29 11:09:53,185: INFO: main: >>>>>> stage Model training completed <<<<<<

x==========x]
[2024-06-29 11:09:53,188: INFO: main: *******************]
[2024-06-29 11:09:53,188: INFO: main: >>>>>> stage Model Evaluation started <<<<<<]
[2024-06-29 11:09:53,194: INFO: common: yaml file: config\config.yaml loaded successfully]
[2024-06-29 11:09:53,197: INFO: common: yaml file: params.yaml loaded successfully]
[2024-06-29 11:09:53,198: INFO: common: created directory at: artifacts]
[2024-06-29 11:15:54,477: INFO: common: json file saved at: scores.json]
[2024-06-29 11:15:54,478: INFO: common: json file saved at: scores.json]
[2024-06-29 11:15:57,957: WARNING: save: Found untraced functions such as _jit_compiled_convolution_op, _jit_compiled_convolution_op, _jit_compiled_convolution_op, _jit_compiled_convolution_op, _jit_compiled_convolution_op while saving (showing 5 of 14). These functions will not be directly callable after loading.]
[2024-06-29 11:15:58,653: INFO: builder_impl: Assets written to: C:\Users\ASUS\AppData\Local\Temp\tmpgmycr76k\model\data\model\assets]
[2024-06-29 11:16:49,730: INFO: main: >>>>>> stage Model Evaluation completed <<<<<<

x==========x]
[2024-06-29 11:22:03,676: INFO: main: >>>>>> stage Data Ingestion stage started <<<<<<]
[2024-06-29 11:22:03,676: INFO: main: >>>>>> stage Data Ingestion stage completed <<<<<<

x==========x]
[2024-06-29 11:22:03,676: INFO: main: >>>>>> stage Prepare base model started <<<<<<]
[2024-06-29 11:22:03,693: INFO: common: yaml file: config\config.yaml loaded successfully]
[2024-06-29 11:22:03,693: INFO: common: yaml file: params.yaml loaded successfully]
[2024-06-29 11:22:03,693: INFO: common: created directory at: artifacts]
[2024-06-29 11:22:03,693: INFO: common: created directory at: artifacts/prepare_base_model]
[2024-06-29 11:22:04,310: WARNING: saving_utils: Compiled the loaded model, but the compiled metrics have yet to be built. `model.compile_metrics` will be empty until you train or evaluate the model.]
[2024-06-29 11:22:04,633: INFO: main: >>>>>> stage Prepare base model completed <<<<<<

x==========x]
[2024-06-29 11:22:04,649: INFO: main: >>>>>> stage Model training started <<<<<<]
[2024-06-29 11:22:04,649: INFO: common: yaml file: config\config.yaml loaded successfully]
[2024-06-29 11:22:04,649: INFO: common: yaml file: params.yaml loaded successfully]
[2024-06-29 11:22:04,649: INFO: common: created directory at: artifacts]
[2024-06-29 11:22:04,649: INFO: common: created directory at: artifacts\training]
[2024-06-29 12:20:12,293: INFO: main: >>>>>> stage Model training completed <<<<<<

x==========x]
[2024-06-29 12:20:12,293: INFO: main: *******************]
[2024-06-29 12:20:12,293: INFO: main: >>>>>> stage Model Evaluation started <<<<<<]
[2024-06-29 12:20:12,293: INFO: common: yaml file: config\config.yaml loaded successfully]
[2024-06-29 12:20:12,310: INFO: common: yaml file: params.yaml loaded successfully]
[2024-06-29 12:20:12,312: INFO: common: created directory at: artifacts]
[2024-06-29 12:25:48,937: INFO: common: json file saved at: scores.json]
[2024-06-29 12:25:48,937: INFO: common: json file saved at: scores.json]
[2024-06-29 12:25:52,288: WARNING: save: Found untraced functions such as _jit_compiled_convolution_op, _jit_compiled_convolution_op, _jit_compiled_convolution_op, _jit_compiled_convolution_op, _jit_compiled_convolution_op while saving (showing 5 of 14). These functions will not be directly callable after loading.]
[2024-06-29 12:25:52,982: INFO: builder_impl: Assets written to: C:\Users\ASUS\AppData\Local\Temp\tmp3bpo4zqg\model\data\model\assets]
[2024-06-29 12:26:37,233: INFO: main: >>>>>> stage Model Evaluation completed <<<<<<

x==========x]
[2024-06-29 13:02:14,726: INFO: main: >>>>>> stage Data Ingestion stage started <<<<<<]
[2024-06-29 13:02:14,726: INFO: main: >>>>>> stage Data Ingestion stage completed <<<<<<

x==========x]
[2024-06-29 13:02:14,726: INFO: main: >>>>>> stage Prepare base model started <<<<<<]
[2024-06-29 13:02:14,726: INFO: common: yaml file: config\config.yaml loaded successfully]
[2024-06-29 13:02:14,742: INFO: common: yaml file: params.yaml loaded successfully]
[2024-06-29 13:02:14,742: INFO: common: created directory at: artifacts]
[2024-06-29 13:02:14,742: INFO: common: created directory at: artifacts/prepare_base_model]
[2024-06-29 13:02:15,805: WARNING: saving_utils: Compiled the loaded model, but the compiled metrics have yet to be built. `model.compile_metrics` will be empty until you train or evaluate the model.]
[2024-06-29 13:02:16,180: INFO: main: >>>>>> stage Prepare base model completed <<<<<<

x==========x]
[2024-06-29 13:02:16,180: INFO: main: >>>>>> stage Model training started <<<<<<]
[2024-06-29 13:02:16,180: INFO: common: yaml file: config\config.yaml loaded successfully]
[2024-06-29 13:02:16,180: INFO: common: yaml file: params.yaml loaded successfully]
[2024-06-29 13:02:16,180: INFO: common: created directory at: artifacts]
[2024-06-29 13:02:16,180: INFO: common: created directory at: artifacts\training]
[2024-06-29 13:41:56,349: INFO: main: >>>>>> stage Model training completed <<<<<<

x==========x]
[2024-06-29 13:41:56,355: INFO: main: *******************]
[2024-06-29 13:41:56,356: INFO: main: >>>>>> stage Model Evaluation started <<<<<<]
[2024-06-29 13:41:56,379: INFO: common: yaml file: config\config.yaml loaded successfully]
[2024-06-29 13:41:56,383: INFO: common: yaml file: params.yaml loaded successfully]
[2024-06-29 13:41:56,389: INFO: common: created directory at: artifacts]
[2024-06-29 16:21:25,165: INFO: main: >>>>>> stage Data Ingestion stage started <<<<<<]
[2024-06-29 16:21:25,166: INFO: main: >>>>>> stage Data Ingestion stage completed <<<<<<

x==========x]
[2024-06-29 16:21:25,167: INFO: main: >>>>>> stage Prepare base model started <<<<<<]
[2024-06-29 16:21:25,169: INFO: common: yaml file: config\config.yaml loaded successfully]
[2024-06-29 16:21:25,169: INFO: common: yaml file: params.yaml loaded successfully]
[2024-06-29 16:21:25,176: INFO: common: created directory at: artifacts]
[2024-06-29 16:21:25,176: INFO: common: created directory at: artifacts/prepare_base_model]
[2024-06-29 16:21:26,113: WARNING: saving_utils: Compiled the loaded model, but the compiled metrics have yet to be built. `model.compile_metrics` will be empty until you train or evaluate the model.]
[2024-06-29 16:21:26,419: INFO: main: >>>>>> stage Prepare base model completed <<<<<<

x==========x]
[2024-06-29 16:21:26,419: INFO: main: >>>>>> stage Model training started <<<<<<]
[2024-06-29 16:21:26,423: INFO: common: yaml file: config\config.yaml loaded successfully]
[2024-06-29 16:21:26,425: INFO: common: yaml file: params.yaml loaded successfully]
[2024-06-29 16:21:26,425: INFO: common: created directory at: artifacts]
[2024-06-29 16:21:26,426: INFO: common: created directory at: artifacts\training]
[2024-06-29 17:03:26,641: INFO: main: >>>>>> stage Model training completed <<<<<<

x==========x]
[2024-06-29 17:03:26,643: INFO: main: *******************]
[2024-06-29 17:03:26,643: INFO: main: >>>>>> stage Model Evaluation started <<<<<<]
[2024-06-29 17:03:26,648: INFO: common: yaml file: config\config.yaml loaded successfully]
[2024-06-29 17:03:26,650: INFO: common: yaml file: params.yaml loaded successfully]
[2024-06-29 17:03:26,651: INFO: common: created directory at: artifacts]
[2024-06-29 17:09:00,924: INFO: common: json file saved at: scores.json]
[2024-06-29 17:09:00,924: INFO: common: json file saved at: scores.json]
[2024-06-29 17:09:00,924: INFO: main: >>>>>> stage Model Evaluation completed <<<<<<

x==========x]
[2024-06-29 17:13:44,551: INFO: main: >>>>>> stage Data Ingestion stage started <<<<<<]
[2024-06-29 17:13:44,551: INFO: main: >>>>>> stage Data Ingestion stage completed <<<<<<

x==========x]
[2024-06-29 17:13:44,551: INFO: main: >>>>>> stage Prepare base model started <<<<<<]
[2024-06-29 17:13:44,551: INFO: common: yaml file: config\config.yaml loaded successfully]
[2024-06-29 17:13:44,551: INFO: common: yaml file: params.yaml loaded successfully]
[2024-06-29 17:13:44,566: INFO: common: created directory at: artifacts]
[2024-06-29 17:13:44,566: INFO: common: created directory at: artifacts/prepare_base_model]
[2024-06-29 17:13:45,040: WARNING: saving_utils: Compiled the loaded model, but the compiled metrics have yet to be built. `model.compile_metrics` will be empty until you train or evaluate the model.]
[2024-06-29 17:13:45,263: INFO: main: >>>>>> stage Prepare base model completed <<<<<<

x==========x]
[2024-06-29 17:13:45,263: INFO: main: >>>>>> stage Model training started <<<<<<]
[2024-06-29 17:13:45,263: INFO: common: yaml file: config\config.yaml loaded successfully]
[2024-06-29 17:13:45,263: INFO: common: yaml file: params.yaml loaded successfully]
[2024-06-29 17:13:45,263: INFO: common: created directory at: artifacts]
[2024-06-29 17:13:45,277: INFO: common: created directory at: artifacts\training]
[2024-06-29 17:55:57,204: INFO: main: >>>>>> stage Model training completed <<<<<<

x==========x]
[2024-06-29 17:55:57,207: INFO: main: *******************]
[2024-06-29 17:55:57,207: INFO: main: >>>>>> stage Model Evaluation started <<<<<<]
[2024-06-29 17:55:57,212: INFO: common: yaml file: config\config.yaml loaded successfully]
[2024-06-29 17:55:57,214: INFO: common: yaml file: params.yaml loaded successfully]
[2024-06-29 17:55:57,215: INFO: common: created directory at: artifacts]
[2024-06-29 18:01:24,726: INFO: common: json file saved at: scores.json]
[2024-06-29 18:01:24,727: INFO: common: json file saved at: scores.json]
[2024-06-29 18:01:28,051: WARNING: save: Found untraced functions such as _jit_compiled_convolution_op, _jit_compiled_convolution_op, _jit_compiled_convolution_op, _jit_compiled_convolution_op, _jit_compiled_convolution_op while saving (showing 5 of 14). These functions will not be directly callable after loading.]
[2024-06-29 18:01:28,707: INFO: builder_impl: Assets written to: C:\Users\ASUS\AppData\Local\Temp\tmpmog50aft\model\data\model\assets]
[2024-06-29 18:03:38,992: INFO: main: >>>>>> stage Model Evaluation completed <<<<<<

x==========x]
[2024-06-30 12:44:44,365: INFO: stage_01_data_ingestion: >>>>>> stage Data Ingestion stage started <<<<<<]
[2024-06-30 12:44:44,368: INFO: common: yaml file: config\config.yaml loaded successfully]
[2024-06-30 12:44:44,371: INFO: common: yaml file: params.yaml loaded successfully]
[2024-06-30 12:44:44,371: INFO: common: created directory at: artifacts]
[2024-06-30 12:44:44,371: INFO: common: created directory at: artifacts/data_ingestion]
[2024-06-30 12:44:44,375: INFO: data_ingestion: Downloading data from https://drive.google.com/file/d/1yLiUUVor0xmtWE830IpivUwYUKS43jfV/view?usp=drive_link into file artifacts/data_ingestion/data.zip]
[2024-06-30 12:44:44,398: ERROR: stage_01_data_ingestion: HTTPSConnectionPool(host='drive.google.com', port=443): Max retries exceeded with url: /uc?/export=download&id=1yLiUUVor0xmtWE830IpivUwYUKS43jfV (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0x000001C2316E72E0>: Failed to establish a new connection: [Errno 11001] getaddrinfo failed'))]
Traceback (most recent call last):
  File "C:\Users\ASUS\anaconda3\envs\kidney\lib\site-packages\urllib3\connection.py", line 174, in _new_conn
    conn = connection.create_connection(
  File "C:\Users\ASUS\anaconda3\envs\kidney\lib\site-packages\urllib3\util\connection.py", line 72, in create_connection
    for res in socket.getaddrinfo(host, port, family, socket.SOCK_STREAM):
  File "C:\Users\ASUS\anaconda3\envs\kidney\lib\socket.py", line 918, in getaddrinfo
    for res in _socket.getaddrinfo(host, port, family, type, proto, flags):
socket.gaierror: [Errno 11001] getaddrinfo failed

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "C:\Users\ASUS\anaconda3\envs\kidney\lib\site-packages\urllib3\connectionpool.py", line 715, in urlopen
    httplib_response = self._make_request(
  File "C:\Users\ASUS\anaconda3\envs\kidney\lib\site-packages\urllib3\connectionpool.py", line 404, in _make_request
    self._validate_conn(conn)
  File "C:\Users\ASUS\anaconda3\envs\kidney\lib\site-packages\urllib3\connectionpool.py", line 1060, in _validate_conn
    conn.connect()
  File "C:\Users\ASUS\anaconda3\envs\kidney\lib\site-packages\urllib3\connection.py", line 363, in connect
    self.sock = conn = self._new_conn()
  File "C:\Users\ASUS\anaconda3\envs\kidney\lib\site-packages\urllib3\connection.py", line 186, in _new_conn
    raise NewConnectionError(
urllib3.exceptions.NewConnectionError: <urllib3.connection.HTTPSConnection object at 0x000001C2316E72E0>: Failed to establish a new connection: [Errno 11001] getaddrinfo failed

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "C:\Users\ASUS\anaconda3\envs\kidney\lib\site-packages\requests\adapters.py", line 667, in send
    resp = conn.urlopen(
  File "C:\Users\ASUS\anaconda3\envs\kidney\lib\site-packages\urllib3\connectionpool.py", line 801, in urlopen
    retries = retries.increment(
  File "C:\Users\ASUS\anaconda3\envs\kidney\lib\site-packages\urllib3\util\retry.py", line 594, in increment
    raise MaxRetryError(_pool, url, error or ResponseError(cause))
urllib3.exceptions.MaxRetryError: HTTPSConnectionPool(host='drive.google.com', port=443): Max retries exceeded with url: /uc?/export=download&id=1yLiUUVor0xmtWE830IpivUwYUKS43jfV (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0x000001C2316E72E0>: Failed to establish a new connection: [Errno 11001] getaddrinfo failed'))

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "src/cnnClassifier/pipeline/stage_01_data_ingestion.py", line 25, in <module>
    obj.main()
  File "src/cnnClassifier/pipeline/stage_01_data_ingestion.py", line 16, in main
    data_ingestion.download_file()
  File "d:\git\deeplearning_classification\src\cnnClassifier\components\data_ingestion.py", line 33, in download_file
    raise e
  File "d:\git\deeplearning_classification\src\cnnClassifier\components\data_ingestion.py", line 28, in download_file
    gdown.download(prefix+file_id,zip_download_dir)
  File "C:\Users\ASUS\anaconda3\envs\kidney\lib\site-packages\gdown\download.py", line 202, in download
    res = sess.get(url, stream=True, verify=verify)
  File "C:\Users\ASUS\anaconda3\envs\kidney\lib\site-packages\requests\sessions.py", line 602, in get
    return self.request("GET", url, **kwargs)
  File "C:\Users\ASUS\anaconda3\envs\kidney\lib\site-packages\requests\sessions.py", line 589, in request
    resp = self.send(prep, **send_kwargs)
  File "C:\Users\ASUS\anaconda3\envs\kidney\lib\site-packages\requests\sessions.py", line 703, in send
    r = adapter.send(request, **kwargs)
  File "C:\Users\ASUS\anaconda3\envs\kidney\lib\site-packages\requests\adapters.py", line 700, in send
    raise ConnectionError(e, request=request)
requests.exceptions.ConnectionError: HTTPSConnectionPool(host='drive.google.com', port=443): Max retries exceeded with url: /uc?/export=download&id=1yLiUUVor0xmtWE830IpivUwYUKS43jfV (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0x000001C2316E72E0>: Failed to establish a new connection: [Errno 11001] getaddrinfo failed'))
[2024-06-30 13:34:57,657: INFO: stage_01_data_ingestion: >>>>>> stage Data Ingestion stage started <<<<<<]
[2024-06-30 13:34:57,659: INFO: common: yaml file: config\config.yaml loaded successfully]
[2024-06-30 13:34:57,659: INFO: common: yaml file: params.yaml loaded successfully]
[2024-06-30 13:34:57,659: INFO: common: created directory at: artifacts]
[2024-06-30 13:34:57,659: INFO: common: created directory at: artifacts/data_ingestion]
[2024-06-30 13:34:57,659: INFO: data_ingestion: Downloading data from https://drive.google.com/file/d/1yLiUUVor0xmtWE830IpivUwYUKS43jfV/view?usp=drive_link into file artifacts/data_ingestion/data.zip]
[2024-06-30 13:37:47,097: INFO: data_ingestion: Downloaded data from https://drive.google.com/file/d/1yLiUUVor0xmtWE830IpivUwYUKS43jfV/view?usp=drive_link into file artifacts/data_ingestion/data.zip]
[2024-06-30 13:37:57,385: INFO: stage_01_data_ingestion: >>>>>> stage Data Ingestion stage completed <<<<<<

x==========x]
[2024-06-30 13:39:38,260: INFO: stage_02_prepare_base_model: >>>>>> stage Prepare base model started <<<<<<]
[2024-06-30 13:39:38,262: INFO: common: yaml file: config\config.yaml loaded successfully]
[2024-06-30 13:39:38,265: INFO: common: yaml file: params.yaml loaded successfully]
[2024-06-30 13:39:38,268: INFO: common: created directory at: artifacts]
[2024-06-30 13:39:38,269: INFO: common: created directory at: artifacts/prepare_base_model]
[2024-06-30 13:39:39,039: WARNING: saving_utils: Compiled the loaded model, but the compiled metrics have yet to be built. `model.compile_metrics` will be empty until you train or evaluate the model.]
[2024-06-30 13:39:39,361: INFO: stage_02_prepare_base_model: >>>>>> stage Prepare base model completed <<<<<<

x==========x]
[2024-06-30 13:39:51,020: INFO: stage_03_model_training: *******************]
[2024-06-30 13:39:51,020: INFO: stage_03_model_training: >>>>>> stage Training started <<<<<<]
[2024-06-30 13:39:51,020: INFO: common: yaml file: config\config.yaml loaded successfully]
[2024-06-30 13:39:51,025: INFO: common: yaml file: params.yaml loaded successfully]
[2024-06-30 13:39:51,025: INFO: common: created directory at: artifacts]
[2024-06-30 13:39:51,026: INFO: common: created directory at: artifacts\training]
[2024-06-30 13:56:16,566: INFO: stage_03_model_training: *******************]
[2024-06-30 13:56:16,567: INFO: stage_03_model_training: >>>>>> stage Training started <<<<<<]
[2024-06-30 13:56:16,569: INFO: common: yaml file: config\config.yaml loaded successfully]
[2024-06-30 13:56:16,572: INFO: common: yaml file: params.yaml loaded successfully]
[2024-06-30 13:56:16,574: INFO: common: created directory at: artifacts]
[2024-06-30 13:56:16,574: INFO: common: created directory at: artifacts\training]
[2024-06-30 14:40:16,018: INFO: stage_03_model_training: >>>>>> stage Training completed <<<<<<

x==========x]
[2024-06-30 14:40:34,300: INFO: stage_04_model_evaluation: *******************]
[2024-06-30 14:40:34,301: INFO: stage_04_model_evaluation: >>>>>> stage Model Evaluation started <<<<<<]
[2024-06-30 14:40:34,303: INFO: common: yaml file: config\config.yaml loaded successfully]
[2024-06-30 14:40:34,305: INFO: common: yaml file: params.yaml loaded successfully]
[2024-06-30 14:40:34,306: INFO: common: created directory at: artifacts]
[2024-06-30 14:46:27,421: INFO: common: json file saved at: scores.json]
[2024-06-30 14:46:27,422: INFO: common: json file saved at: scores.json]
[2024-06-30 14:46:27,423: INFO: stage_04_model_evaluation: >>>>>> stage Model Evaluation completed <<<<<<

x==========x]
[2024-06-30 14:56:06,033: INFO: _internal: [31m[1mWARNING: This is a development server. Do not use it in a production deployment. Use a production WSGI server instead.[0m
 * Running on all addresses (0.0.0.0)
 * Running on http://127.0.0.1:8080
 * Running on http://192.168.1.6:8080]
[2024-06-30 14:56:06,034: INFO: _internal: [33mPress CTRL+C to quit[0m]
[2024-06-30 14:56:55,451: INFO: _internal: 127.0.0.1 - - [30/Jun/2024 14:56:55] "GET / HTTP/1.1" 200 -]
[2024-06-30 14:57:17,577: ERROR: app: Exception on /predict [POST]]
Traceback (most recent call last):
  File "C:\Users\ASUS\anaconda3\envs\kidney\lib\site-packages\flask\app.py", line 2190, in wsgi_app
    response = self.full_dispatch_request()
  File "C:\Users\ASUS\anaconda3\envs\kidney\lib\site-packages\flask\app.py", line 1486, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "C:\Users\ASUS\anaconda3\envs\kidney\lib\site-packages\flask_cors\extension.py", line 178, in wrapped_function
    return cors_after_request(app.make_response(f(*args, **kwargs)))
  File "C:\Users\ASUS\anaconda3\envs\kidney\lib\site-packages\flask\app.py", line 1484, in full_dispatch_request
    rv = self.dispatch_request()
  File "C:\Users\ASUS\anaconda3\envs\kidney\lib\site-packages\flask\app.py", line 1469, in dispatch_request
    return self.ensure_sync(self.view_functions[rule.endpoint])(**view_args)
  File "C:\Users\ASUS\anaconda3\envs\kidney\lib\site-packages\flask_cors\decorator.py", line 130, in wrapped_function
    resp = make_response(f(*args, **kwargs))
  File "app.py", line 44, in predictRoute
    result = clApp.classifier.predict()
  File "d:\git\deeplearning_classification\src\cnnClassifier\pipeline\prediction.py", line 16, in predict
    model = load_model(os.path.join("model", "model.h5"))
  File "C:\Users\ASUS\anaconda3\envs\kidney\lib\site-packages\keras\saving\saving_api.py", line 212, in load_model
    return legacy_sm_saving_lib.load_model(
  File "C:\Users\ASUS\anaconda3\envs\kidney\lib\site-packages\keras\utils\traceback_utils.py", line 70, in error_handler
    raise e.with_traceback(filtered_tb) from None
  File "C:\Users\ASUS\anaconda3\envs\kidney\lib\site-packages\keras\saving\legacy\save.py", line 230, in load_model
    raise IOError(
OSError: No file or directory found at model\model.h5
[2024-06-30 14:57:17,590: INFO: _internal: 127.0.0.1 - - [30/Jun/2024 14:57:17] "[35m[1mPOST /predict HTTP/1.1[0m" 500 -]
[2024-06-30 15:05:31,330: INFO: _internal: [31m[1mWARNING: This is a development server. Do not use it in a production deployment. Use a production WSGI server instead.[0m
 * Running on http://127.0.0.1:5000]
[2024-06-30 15:05:31,330: INFO: _internal: [33mPress CTRL+C to quit[0m]
[2024-06-30 15:06:09,922: INFO: _internal: 127.0.0.1 - - [30/Jun/2024 15:06:09] "GET / HTTP/1.1" 200 -]
[2024-06-30 15:06:15,632: ERROR: app: Exception on /predict [POST]]
Traceback (most recent call last):
  File "C:\Users\ASUS\anaconda3\envs\kidney\lib\site-packages\flask\app.py", line 2190, in wsgi_app
    response = self.full_dispatch_request()
  File "C:\Users\ASUS\anaconda3\envs\kidney\lib\site-packages\flask\app.py", line 1486, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "C:\Users\ASUS\anaconda3\envs\kidney\lib\site-packages\flask_cors\extension.py", line 178, in wrapped_function
    return cors_after_request(app.make_response(f(*args, **kwargs)))
  File "C:\Users\ASUS\anaconda3\envs\kidney\lib\site-packages\flask\app.py", line 1484, in full_dispatch_request
    rv = self.dispatch_request()
  File "C:\Users\ASUS\anaconda3\envs\kidney\lib\site-packages\flask\app.py", line 1469, in dispatch_request
    return self.ensure_sync(self.view_functions[rule.endpoint])(**view_args)
  File "C:\Users\ASUS\anaconda3\envs\kidney\lib\site-packages\flask_cors\decorator.py", line 130, in wrapped_function
    resp = make_response(f(*args, **kwargs))
  File "D:\Git\DeepLearning_Classification\app.py", line 43, in predictRoute
    decodeImage(image, clApp.filename)
NameError: name 'clApp' is not defined
[2024-06-30 15:06:15,632: INFO: _internal: 127.0.0.1 - - [30/Jun/2024 15:06:15] "[35m[1mPOST /predict HTTP/1.1[0m" 500 -]
[2024-06-30 15:09:07,931: INFO: _internal: [31m[1mWARNING: This is a development server. Do not use it in a production deployment. Use a production WSGI server instead.[0m
 * Running on http://127.0.0.1:5000]
[2024-06-30 15:09:07,932: INFO: _internal: [33mPress CTRL+C to quit[0m]
[2024-06-30 15:09:13,551: INFO: _internal: 127.0.0.1 - - [30/Jun/2024 15:09:13] "GET / HTTP/1.1" 200 -]
[2024-06-30 15:09:20,746: INFO: _internal: 127.0.0.1 - - [30/Jun/2024 15:09:20] "POST /predict HTTP/1.1" 200 -]
[2024-06-30 15:09:31,633: INFO: _internal: 127.0.0.1 - - [30/Jun/2024 15:09:31] "POST /predict HTTP/1.1" 200 -]
[2024-06-30 15:09:51,371: INFO: _internal: 127.0.0.1 - - [30/Jun/2024 15:09:51] "POST /predict HTTP/1.1" 200 -]
[2024-06-30 15:10:14,680: INFO: _internal: 127.0.0.1 - - [30/Jun/2024 15:10:14] "POST /predict HTTP/1.1" 200 -]
[2024-06-30 15:10:25,232: WARNING: polymorphic_function: 5 out of the last 5 calls to <function Model.make_predict_function.<locals>.predict_function at 0x000001D59EDCB040> triggered tf.function retracing. Tracing is expensive and the excessive number of tracings could be due to (1) creating @tf.function repeatedly in a loop, (2) passing tensors with different shapes, (3) passing Python objects instead of tensors. For (1), please define your @tf.function outside of the loop. For (2), @tf.function has reduce_retracing=True option that can avoid unnecessary retracing. For (3), please refer to https://www.tensorflow.org/guide/function#controlling_retracing and https://www.tensorflow.org/api_docs/python/tf/function for  more details.]
[2024-06-30 15:10:25,232: INFO: _internal: 127.0.0.1 - - [30/Jun/2024 15:10:25] "POST /predict HTTP/1.1" 200 -]
[2024-06-30 15:10:39,450: WARNING: polymorphic_function: 6 out of the last 6 calls to <function Model.make_predict_function.<locals>.predict_function at 0x000001D59EDCBCA0> triggered tf.function retracing. Tracing is expensive and the excessive number of tracings could be due to (1) creating @tf.function repeatedly in a loop, (2) passing tensors with different shapes, (3) passing Python objects instead of tensors. For (1), please define your @tf.function outside of the loop. For (2), @tf.function has reduce_retracing=True option that can avoid unnecessary retracing. For (3), please refer to https://www.tensorflow.org/guide/function#controlling_retracing and https://www.tensorflow.org/api_docs/python/tf/function for  more details.]
[2024-06-30 15:10:39,450: INFO: _internal: 127.0.0.1 - - [30/Jun/2024 15:10:39] "POST /predict HTTP/1.1" 200 -]
[2024-06-30 15:10:50,087: INFO: _internal: 127.0.0.1 - - [30/Jun/2024 15:10:50] "POST /predict HTTP/1.1" 200 -]
[2024-06-30 15:11:08,508: INFO: _internal: 127.0.0.1 - - [30/Jun/2024 15:11:08] "POST /predict HTTP/1.1" 200 -]
[2024-06-30 15:11:18,061: INFO: _internal: 127.0.0.1 - - [30/Jun/2024 15:11:18] "POST /predict HTTP/1.1" 200 -]
[2024-06-30 15:11:28,597: INFO: _internal: 127.0.0.1 - - [30/Jun/2024 15:11:28] "POST /predict HTTP/1.1" 200 -]
[2024-06-30 15:11:42,984: INFO: _internal: 127.0.0.1 - - [30/Jun/2024 15:11:42] "POST /predict HTTP/1.1" 200 -]
[2024-06-30 15:11:52,853: INFO: _internal: 127.0.0.1 - - [30/Jun/2024 15:11:52] "POST /predict HTTP/1.1" 200 -]
[2024-06-30 15:34:54,933: INFO: stage_04_model_evaluation: *******************]
[2024-06-30 15:34:54,933: INFO: stage_04_model_evaluation: >>>>>> stage Model Evaluation started <<<<<<]
[2024-06-30 15:34:54,950: INFO: common: yaml file: config\config.yaml loaded successfully]
[2024-06-30 15:34:54,950: INFO: common: yaml file: params.yaml loaded successfully]
[2024-06-30 15:34:54,950: INFO: common: created directory at: artifacts]
[2024-06-30 15:35:44,175: INFO: main: >>>>>> stage Data Ingestion stage started <<<<<<]
[2024-06-30 15:35:44,175: INFO: main: >>>>>> stage Data Ingestion stage completed <<<<<<

x==========x]
[2024-06-30 15:35:44,176: INFO: main: >>>>>> stage Prepare base model started <<<<<<]
[2024-06-30 15:35:44,178: INFO: common: yaml file: config\config.yaml loaded successfully]
[2024-06-30 15:35:44,178: INFO: common: yaml file: params.yaml loaded successfully]
[2024-06-30 15:35:44,178: INFO: common: created directory at: artifacts]
[2024-06-30 15:35:44,178: INFO: common: created directory at: artifacts/prepare_base_model]
[2024-06-30 15:35:44,641: WARNING: saving_utils: Compiled the loaded model, but the compiled metrics have yet to be built. `model.compile_metrics` will be empty until you train or evaluate the model.]
[2024-06-30 15:35:44,896: INFO: main: >>>>>> stage Prepare base model completed <<<<<<

x==========x]
[2024-06-30 15:35:44,896: INFO: main: >>>>>> stage Model training started <<<<<<]
[2024-06-30 15:35:44,896: INFO: common: yaml file: config\config.yaml loaded successfully]
[2024-06-30 15:35:44,896: INFO: common: yaml file: params.yaml loaded successfully]
[2024-06-30 15:35:44,896: INFO: common: created directory at: artifacts]
[2024-06-30 15:35:44,903: INFO: common: created directory at: artifacts\training]
[2024-06-30 15:37:47,558: INFO: stage_03_model_training: *******************]
[2024-06-30 15:37:47,558: INFO: stage_03_model_training: >>>>>> stage Training started <<<<<<]
[2024-06-30 15:37:47,558: INFO: common: yaml file: config\config.yaml loaded successfully]
[2024-06-30 15:37:47,558: INFO: common: yaml file: params.yaml loaded successfully]
[2024-06-30 15:37:47,558: INFO: common: created directory at: artifacts]
[2024-06-30 15:37:47,571: INFO: common: created directory at: artifacts\training]
[2024-06-30 15:38:51,790: INFO: stage_03_model_training: *******************]
[2024-06-30 15:38:51,790: INFO: stage_03_model_training: >>>>>> stage Training started <<<<<<]
[2024-06-30 15:38:51,790: INFO: common: yaml file: config\config.yaml loaded successfully]
[2024-06-30 15:38:51,790: INFO: common: yaml file: params.yaml loaded successfully]
[2024-06-30 15:38:51,790: INFO: common: created directory at: artifacts]
[2024-06-30 15:38:51,790: INFO: common: created directory at: artifacts\training]
[2024-06-30 15:59:34,931: INFO: stage_03_model_training: >>>>>> stage Training completed <<<<<<

x==========x]
[2024-06-30 15:59:54,451: INFO: stage_04_model_evaluation: *******************]
[2024-06-30 15:59:54,451: INFO: stage_04_model_evaluation: >>>>>> stage Model Evaluation started <<<<<<]
[2024-06-30 15:59:54,458: INFO: common: yaml file: config\config.yaml loaded successfully]
[2024-06-30 15:59:54,458: INFO: common: yaml file: params.yaml loaded successfully]
[2024-06-30 15:59:54,458: INFO: common: created directory at: artifacts]
[2024-06-30 16:06:02,475: INFO: common: json file saved at: scores.json]
[2024-06-30 16:06:02,475: INFO: common: json file saved at: scores.json]
[2024-06-30 16:06:02,475: INFO: stage_04_model_evaluation: >>>>>> stage Model Evaluation completed <<<<<<

x==========x]
